defmodule Mix.Tasks.Barkpark.Preview.GenParity do
  @moduledoc """
  Generate the cross-surface **preview-parity fixture** and write it to all
  three mirror paths. ONE canonical preview manifest — the executable source of
  truth that every surface consuming `content["preview"]` must agree on: the
  papers reader (`BarkparkWeb.ShareMeta`), the v1 envelope (wire hoist), the web
  finder (`metadataFromPreview`), the Studio doc rows (`PaneBuilder`), and the
  Go TUI doc rows (`rowMeta`).

      mix barkpark.preview.gen_parity

  The manifest is produced by `Barkpark.Preview.project/3` ITSELF — the SAME
  pure function the write path stamps at `Projection.project/4` — so the fixture
  can never certify a manifest the projector would not have produced. Two
  variants ride in ONE fixture:

    * `rich` — a paper with a derived (inline-mark-flattened) description, a
      media-backed image (5-field object, relative url per D3), and the full
      D9 paper extension ring.
    * `core` — a title/type/url-only paper (no blocks): the DEGRADATION
      INVARIANT baseline — every surface must still render a valid BRANDED card
      (the `/images/og-default.jpg` fallback) from it.

  Emits pretty-printed JSON to three byte-identical mirrors:

    * `api/test/support/fixtures/preview-parity.json`
    * `web/__tests__/fixtures/preview-parity.json`
    * `cmd/barkpark/testdata/preview-parity.json`

  Do NOT hand-edit any mirror — re-run this task and re-verify all five
  surfaces. The freshness lock lives in
  `test/barkpark/preview_parity_fixture_test.exs` (asserts the committed api
  mirror equals `build/0` and that the three mirrors decode term-identical).

  `build/0` is PURE (only `Barkpark.Preview.project/3` with a stubbed, Repo-free
  media resolver) so the freshness test regenerates in-memory without a
  `Mix.Task` or app boot.
  """
  @shortdoc "Regenerate the cross-surface preview parity fixture (three mirrors)"

  use Mix.Task

  alias Barkpark.Preview

  # ── the canonical documents ─────────────────────────────────────────────────
  #
  # RICH: a paper whose description is DERIVED (no explicit excerpt) from the
  # first ingress block — whose inline-mark children (a `strong` run) must
  # flatten to plain text identically on every surface (the pc-w2b description-
  # marks class, pinned here as a cross-surface lock). A `role: "title"` heading,
  # and a `role: "featured"` MEDIA image (a `/media/files/...` src) resolved
  # through the stub to the constant-geometry `og` rendition → a 5-field image
  # object carrying a RELATIVE url (D3) each surface must absolutize itself.
  @rich_content %{
    "title" => "Theme System",
    "type" => "paper",
    "published_time" => "2026-07-09T10:00:00Z",
    "authors" => ["Kalle", "Fable"],
    "tags" => ["opengraph", "branding"],
    "section" => "Engineering"
  }

  @rich_blocks [
    %{"type" => "heading", "role" => "title", "text" => "Theme System"},
    %{
      "type" => "ingress",
      "content" => [
        %{"type" => "text", "value" => "How Barkpark's "},
        %{"type" => "text", "value" => "design tokens", "marks" => ["strong"]},
        %{"type" => "text", "value" => " fan out to every surface."}
      ]
    },
    %{
      "type" => "image",
      "role" => "featured",
      "src" => "/media/files/og/theme.jpg",
      "alt" => "The theme system card"
    }
  ]

  @rich_url "/papers/theme-system"

  # CORE-ONLY: no blocks, no excerpt, no extensions — the degradation baseline.
  # `Preview.project/3` yields title + type + url with a nil image and nil
  # description; every surface must still render a BRANDED card from it.
  @core_content %{"title" => "Release Checklist", "type" => "paper"}
  @core_blocks []
  @core_url "/papers/release-checklist"

  # The stub media resolver — Repo-FREE (a hardcoded closure, never
  # `Media.get_file_by_path`) so `build/0` stays pure. Mirrors exactly what
  # `Barkpark.Preview.media_resolver/1` returns for a resolvable file: the `og`
  # rendition url (RELATIVE, id-based per router.ex `/media/renditions/:id/:preset`)
  # at the constant 1200×630 geometry.
  @og_rendition_url "/media/renditions/theme-og/og"

  defp stub_resolver do
    fn
      "/media/files/og/theme.jpg" ->
        %{
          "url" => @og_rendition_url,
          "width" => 1200,
          "height" => 630,
          "type" => "image/jpeg"
        }

      _ ->
        nil
    end
  end

  @comment "Generated by `mix barkpark.preview.gen_parity` — DO NOT hand-edit. " <>
             "Cross-surface preview-manifest parity lock (papers reader ShareMeta + v1 " <>
             "envelope hoist + web finder metadata + Studio doc rows + Go TUI rows). " <>
             "The manifest is Barkpark.Preview.project/3 itself — regenerate, never edit."

  @api_path Path.expand("../../../test/support/fixtures/preview-parity.json", __DIR__)
  @web_path Path.expand("../../../../web/__tests__/fixtures/preview-parity.json", __DIR__)
  @go_path Path.expand("../../../../cmd/barkpark/testdata/preview-parity.json", __DIR__)

  @doc "The three mirror paths the fixture is written to (also read by the freshness test)."
  def mirror_paths, do: [@api_path, @web_path, @go_path]

  @impl Mix.Task
  def run(_args) do
    json = Jason.encode!(build(), pretty: true) <> "\n"

    for path <- mirror_paths() do
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, json)
      Mix.shell().info("wrote #{path}")
    end

    Mix.shell().info("gen_parity: 3 mirror(s) written — re-verify all five surfaces.")
  end

  @doc """
  Build the parity fixture data map (pure — `Barkpark.Preview.project/3` with a
  stubbed, Repo-free media resolver; no app boot). The freshness test
  regenerates through this and asserts term-equality with the committed api
  mirror.

  Every term is JSON-safe (string keys, lists not tuples) so a Jason encode →
  decode round-trip is the identity, and `build/0 == Jason.decode!(committed)`.
  """
  def build do
    rich_manifest =
      Preview.project(@rich_content, @rich_blocks, %{
        url: @rich_url,
        doc_type: "paper",
        media_resolver: stub_resolver()
      })

    core_manifest =
      Preview.project(@core_content, @core_blocks, %{url: @core_url, doc_type: "paper"})

    %{
      "_comment" => @comment,
      "rich" => %{
        "doc" => %{"content" => @rich_content, "blocks" => @rich_blocks},
        "manifest" => rich_manifest
      },
      "core" => %{
        "doc" => %{"content" => @core_content, "blocks" => @core_blocks},
        "manifest" => core_manifest
      }
    }
  end
end
