// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

/** Light-theme canvas colours for listings-map.tsx, mapped from design/tokens.json. */
export const canvas = {
  primary: "hsl(163 46% 22%)",
  mutedText: "hsl(240 3.8% 46.1%)",
  surface: "hsl(0 0% 100%)",
  primaryFg: "hsl(0 0% 100%)",
  text: "hsl(240 10% 3.9%)",
  mutedSurface: "hsl(240 4.8% 95.9%)",
} as const;

/** Categorical match-quality spectrum (7 ordered stops, fuzzy→exact) for
 *  finder.tsx's HighlightLegend gradient. Theme-invariant data-viz palette,
 *  NOT a status role — mirrors the presence / Sheets-CF categorical sets. */
export const matchQuality = [
  "hsl(0 55% 60%)",
  "hsl(24 70% 56%)",
  "hsl(48 82% 50%)",
  "hsl(72 86% 46%)",
  "hsl(100 88% 42%)",
  "hsl(130 90% 38%)",
  "hsl(162 95% 34%)",
] as const;
