// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

package taskboard

// GenLifecycleToken mirrors one design/tokens.json lifecycle state.
type GenLifecycleToken struct {
	Glyph      string
	ASCIIGlyph string
	Role       string
	ColorLight string
	ColorDark  string
}

// GenLifecycle is the generated 1:1 mirror of tokens.lifecycle (glyph + hue).
var GenLifecycle = map[string]GenLifecycleToken{
	"in_progress": {Glyph: "⠋", ASCIIGlyph: "~", Role: "info", ColorLight: "#2563eb", ColorDark: "#60a5fa"},
	"blocked":     {Glyph: "!", ASCIIGlyph: "!", Role: "warn", ColorLight: "#d97706", ColorDark: "#fbbf24"},
	"done":        {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
	"closed":      {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
	"cancelled":   {Glyph: "✕", ASCIIGlyph: "x", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
	"ready":       {Glyph: "○", ASCIIGlyph: "o", Role: "", ColorLight: "#18181b", ColorDark: "#e7edf2"},
	"open":        {Glyph: "○", ASCIIGlyph: ".", Role: "", ColorLight: "#71717a", ColorDark: "#5f6b78"},
	"considering": {Glyph: "◌", ASCIIGlyph: "?", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
	"researching": {Glyph: "◎", ASCIIGlyph: "R", Role: "", ColorLight: "#7c3aed", ColorDark: "#a78bfa"},
}

// GenLifecycleOrder is the canonical emission order (matches the source).
var GenLifecycleOrder = []string{"in_progress", "blocked", "done", "closed", "cancelled", "ready", "open", "considering", "researching"}

// GenBrailleFrames mirrors lifecycle.in_progress.frames (spinner.go).
var GenBrailleFrames = [10]string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"}

// GenBrailleStill is the reduced-motion steady frame.
var GenBrailleStill = "⠿"

// DefaultTheme is the built-in evergreen skin. Resolve defaults to it for an
// unknown/empty theme id; theme.go's buildPalette reads Resolve(theme).Lifecycle.
const DefaultTheme = "evergreen"

// ThemeLifecycle bundles one theme's lifecycle token map + braille frames.
type ThemeLifecycle struct {
	Lifecycle     map[string]GenLifecycleToken
	BrailleFrames [10]string
	BrailleStill  string
}

// genLifecycleThemes keys each theme's lifecycle set by id (evergreen REFERENCES
// GenLifecycle/GenBrailleFrames/GenBrailleStill — no re-typed literals).
var genLifecycleThemes = map[string]ThemeLifecycle{
	"evergreen": {Lifecycle: GenLifecycle, BrailleFrames: GenBrailleFrames, BrailleStill: GenBrailleStill},
	"charple": {
		Lifecycle: map[string]GenLifecycleToken{
			"in_progress": {Glyph: "⠋", ASCIIGlyph: "~", Role: "info", ColorLight: "#2563eb", ColorDark: "#60a5fa"},
			"blocked":     {Glyph: "!", ASCIIGlyph: "!", Role: "warn", ColorLight: "#d97706", ColorDark: "#fbbf24"},
			"done":        {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"closed":      {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"cancelled":   {Glyph: "✕", ASCIIGlyph: "x", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"ready":       {Glyph: "○", ASCIIGlyph: "o", Role: "", ColorLight: "#18181b", ColorDark: "#e7edf2"},
			"open":        {Glyph: "○", ASCIIGlyph: ".", Role: "", ColorLight: "#71717a", ColorDark: "#5f6b78"},
			"considering": {Glyph: "◌", ASCIIGlyph: "?", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"researching": {Glyph: "◎", ASCIIGlyph: "R", Role: "", ColorLight: "#7c3aed", ColorDark: "#a78bfa"},
		},
		BrailleFrames: [10]string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"},
		BrailleStill:  "⠿",
	},
	"ember": {
		Lifecycle: map[string]GenLifecycleToken{
			"in_progress": {Glyph: "⠋", ASCIIGlyph: "~", Role: "info", ColorLight: "#2563eb", ColorDark: "#60a5fa"},
			"blocked":     {Glyph: "!", ASCIIGlyph: "!", Role: "warn", ColorLight: "#d97706", ColorDark: "#fbbf24"},
			"done":        {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"closed":      {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"cancelled":   {Glyph: "✕", ASCIIGlyph: "x", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"ready":       {Glyph: "○", ASCIIGlyph: "o", Role: "", ColorLight: "#18181b", ColorDark: "#e7edf2"},
			"open":        {Glyph: "○", ASCIIGlyph: ".", Role: "", ColorLight: "#71717a", ColorDark: "#5f6b78"},
			"considering": {Glyph: "◌", ASCIIGlyph: "?", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"researching": {Glyph: "◎", ASCIIGlyph: "R", Role: "", ColorLight: "#7c3aed", ColorDark: "#a78bfa"},
		},
		BrailleFrames: [10]string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"},
		BrailleStill:  "⠿",
	},
	"fjord": {
		Lifecycle: map[string]GenLifecycleToken{
			"in_progress": {Glyph: "⠋", ASCIIGlyph: "~", Role: "info", ColorLight: "#2563eb", ColorDark: "#60a5fa"},
			"blocked":     {Glyph: "!", ASCIIGlyph: "!", Role: "warn", ColorLight: "#d97706", ColorDark: "#fbbf24"},
			"done":        {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"closed":      {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"cancelled":   {Glyph: "✕", ASCIIGlyph: "x", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"ready":       {Glyph: "○", ASCIIGlyph: "o", Role: "", ColorLight: "#18181b", ColorDark: "#e7edf2"},
			"open":        {Glyph: "○", ASCIIGlyph: ".", Role: "", ColorLight: "#71717a", ColorDark: "#5f6b78"},
			"considering": {Glyph: "◌", ASCIIGlyph: "?", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"researching": {Glyph: "◎", ASCIIGlyph: "R", Role: "", ColorLight: "#7c3aed", ColorDark: "#a78bfa"},
		},
		BrailleFrames: [10]string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"},
		BrailleStill:  "⠿",
	},
	"iris": {
		Lifecycle: map[string]GenLifecycleToken{
			"in_progress": {Glyph: "⠋", ASCIIGlyph: "~", Role: "info", ColorLight: "#2563eb", ColorDark: "#60a5fa"},
			"blocked":     {Glyph: "!", ASCIIGlyph: "!", Role: "warn", ColorLight: "#d97706", ColorDark: "#fbbf24"},
			"done":        {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"closed":      {Glyph: "✓", ASCIIGlyph: "v", Role: "ok", ColorLight: "#0d9488", ColorDark: "#2dd4bf"},
			"cancelled":   {Glyph: "✕", ASCIIGlyph: "x", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"ready":       {Glyph: "○", ASCIIGlyph: "o", Role: "", ColorLight: "#18181b", ColorDark: "#e7edf2"},
			"open":        {Glyph: "○", ASCIIGlyph: ".", Role: "", ColorLight: "#71717a", ColorDark: "#5f6b78"},
			"considering": {Glyph: "◌", ASCIIGlyph: "?", Role: "", ColorLight: "#a1a1aa", ColorDark: "#71717a"},
			"researching": {Glyph: "◎", ASCIIGlyph: "R", Role: "", ColorLight: "#7c3aed", ColorDark: "#a78bfa"},
		},
		BrailleFrames: [10]string{"⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"},
		BrailleStill:  "⠿",
	},
}

// Resolve returns a theme's lifecycle token set, defaulting to evergreen for an
// unknown or empty id.
func Resolve(theme string) ThemeLifecycle {
	if t, ok := genLifecycleThemes[theme]; ok {
		return t
	}
	return genLifecycleThemes[DefaultTheme]
}
