// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

package pdrender

import "github.com/charmbracelet/lipgloss"

// Generated semantic status tones (design/tokens.json color.status → hex).
var (
	GenToneInfo   = lipgloss.AdaptiveColor{Light: "#3b82f6", Dark: "#3b82f6"}
	GenToneOK     = lipgloss.AdaptiveColor{Light: "#137236", Dark: "#45c474"}
	GenToneWarn   = lipgloss.AdaptiveColor{Light: "#ba7008", Dark: "#f8ab25"}
	GenToneDanger = lipgloss.AdaptiveColor{Light: "#b42222", Dark: "#ef6161"}
)

// Generated reading tokens (design/tokens.json font.reading / type.reading).
const (
	GenReadingFontStack     = "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Charter, Georgia, \"Source Serif 4\", serif"
	GenReadingHeadingWeight = 600
	GenReadingBodySize      = 18
)
