// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

package pdrender

import "github.com/charmbracelet/lipgloss"

// Generated semantic status tones (design/tokens.json color.status → hex).
var (
	GenToneInfo   = lipgloss.AdaptiveColor{Light: "#3b82f6", Dark: "#3b82f6"}
	GenToneOK     = lipgloss.AdaptiveColor{Light: "#137236", Dark: "#45c474"}
	GenToneWarn   = lipgloss.AdaptiveColor{Light: "#ba7008", Dark: "#f8ab25"}
	GenToneDanger = lipgloss.AdaptiveColor{Light: "#b42222", Dark: "#ef6161"}
)

// Generated neutral callout tone (design/tokens.json color.cliCalloutNeutral).
var GenToneNeutral = lipgloss.AdaptiveColor{Light: "#374151", Dark: "#9ca3af"}

// Generated chrome + reading-accent tokens (design/tokens.json color.* → hex).
var (
	GenPrimary       = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenPrimaryFg     = lipgloss.AdaptiveColor{Light: "#ffffff", Dark: "#0b1e18"}
	GenInk           = lipgloss.AdaptiveColor{Light: "#09090b", Dark: "#f2f2f2"}
	GenDim           = lipgloss.AdaptiveColor{Light: "#6e6e77", Dark: "#a1a1aa"}
	GenRule          = lipgloss.AdaptiveColor{Light: "#e4e4e7", Dark: "#27272a"}
	GenReadingAccent = lipgloss.AdaptiveColor{Light: "#a23925", Dark: "#d98a6a"}
)

// Generated CLI-chrome tokens (design/tokens.json color.cliChrome → hex).
// pdrender's own copy (it can't import internal/semrole); referenced by the
// evergreen genPalette entry below and threaded through theme.go's buildTheme
// (pal.ChromeAccent/ChromeInk/ChromeTextSecondary/ChromeDim, via Resolve).
var (
	GenChromeAccent        = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenChromeInk           = lipgloss.AdaptiveColor{Light: "#18181b", Dark: "#e4e4e7"}
	GenChromeTextSecondary = lipgloss.AdaptiveColor{Light: "#3f3f46", Dark: "#a1a1aa"}
	GenChromeDim           = lipgloss.AdaptiveColor{Light: "#a1a1aa", Dark: "#52525b"}
)

// Generated code-block tones (design/tokens.json color.code → hex).
var (
	GenCodeFg = lipgloss.AdaptiveColor{Light: "#be123c", Dark: "#fda4af"}
	GenCodeBg = lipgloss.AdaptiveColor{Light: "#f4f4f5", Dark: "#27272a"}
)

// Generated reading tokens (design/tokens.json font.reading / type.reading).
const (
	GenReadingFontStack     = "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Charter, Georgia, \"Source Serif 4\", serif"
	GenReadingHeadingWeight = 600
	GenReadingBodySize      = 18
)

// Generated categorical viz palettes (design/tokens.json color.pdrenderChart /
// color.pdrenderHeatmap → hex). NOT status roles — theme-invariant categorical
// data-viz values (the presence / matchQuality passthrough precedent, D21).
// GenChartSeries is chart.go's per-series TrueColor cycle; GenHeatmapBase/Peak
// are heatmap.go's dark→bright gradient endpoints. Byte-faithful to the former
// hand literals, so the render is unchanged. GenHeatRamp is the 4 discrete shade
// steps (light→full) heatmap.go's quantile dual-encode paints as each glyph bin's
// Foreground — ramp[3] == GenHeatmapPeak so the discrete scale meets the gradient.
var GenChartSeries = []lipgloss.Color{
	lipgloss.Color("#60a5fa"),
	lipgloss.Color("#f472b6"),
	lipgloss.Color("#4ade80"),
	lipgloss.Color("#fbbf24"),
	lipgloss.Color("#a78bfa"),
	lipgloss.Color("#22d3ee"),
}

var GenHeatRamp = []lipgloss.Color{
	lipgloss.Color("#0e4429"),
	lipgloss.Color("#006d32"),
	lipgloss.Color("#26a641"),
	lipgloss.Color("#39d353"),
}

const (
	GenHeatmapBase = "#0d1117"
	GenHeatmapPeak = "#39d353"
)

// DefaultTheme is the built-in evergreen skin. Resolve defaults to it for any
// unknown/empty theme id, so today (evergreen-only) every id yields these exact
// bytes — the styleguide golden stays frozen. Adding theme N+1 grows genPalette
// (one keyed entry); theme.go's buildTheme already reads Resolve(themeID).
const DefaultTheme = "evergreen"

// Palette is one theme's resolved pdrender token set. The Chrome* roles are the
// zinc cliChrome family (ChromeInk/ChromeDim are NOT the warmer reading Ink/Dim —
// the decoy guard theme.go documents); ReadingMuted/ReadingAccent are the reading
// family; Tone* are the semantic status tones the Callout builder paints.
type Palette struct {
	ChromeAccent        lipgloss.AdaptiveColor
	ChromeInk           lipgloss.AdaptiveColor
	ChromeTextSecondary lipgloss.AdaptiveColor
	ChromeDim           lipgloss.AdaptiveColor
	Rule                lipgloss.AdaptiveColor
	CodeFg              lipgloss.AdaptiveColor
	CodeBg              lipgloss.AdaptiveColor
	ReadingMuted        lipgloss.AdaptiveColor
	ReadingAccent       lipgloss.AdaptiveColor
	ToneInfo            lipgloss.AdaptiveColor
	ToneOK              lipgloss.AdaptiveColor
	ToneWarn            lipgloss.AdaptiveColor
	ToneDanger          lipgloss.AdaptiveColor
	ToneNeutral         lipgloss.AdaptiveColor
}

// genPalette keys each theme's Palette by id. Values REFERENCE the Gen* vars
// above (no re-typed literals) so the evergreen skin is byte-identical to them.
var genPalette = map[string]Palette{
	"evergreen": {
		ChromeAccent:        GenChromeAccent,
		ChromeInk:           GenChromeInk,
		ChromeTextSecondary: GenChromeTextSecondary,
		ChromeDim:           GenChromeDim,
		Rule:                GenRule,
		CodeFg:              GenCodeFg,
		CodeBg:              GenCodeBg,
		ReadingMuted:        GenDim,
		ReadingAccent:       GenReadingAccent,
		ToneInfo:            GenToneInfo,
		ToneOK:              GenToneOK,
		ToneWarn:            GenToneWarn,
		ToneDanger:          GenToneDanger,
		ToneNeutral:         GenToneNeutral,
	},
	"charple": {
		ChromeAccent:        lipgloss.AdaptiveColor{Light: "#3431b4", Dark: "#6c52ff"},
		ChromeInk:           lipgloss.AdaptiveColor{Light: "#323138", Dark: "#d7d6dc"},
		ChromeTextSecondary: lipgloss.AdaptiveColor{Light: "#57565c", Dark: "#a1a0a6"},
		ChromeDim:           lipgloss.AdaptiveColor{Light: "#a7a6ab", Dark: "#6e6d73"},
		Rule:                lipgloss.AdaptiveColor{Light: "#dee0e5", Dark: "#131417"},
		CodeFg:              lipgloss.AdaptiveColor{Light: "#218bc4", Dark: "#52abff"},
		CodeBg:              lipgloss.AdaptiveColor{Light: "#f0eff4", Dark: "#35343b"},
		ReadingMuted:        lipgloss.AdaptiveColor{Light: "#67696f", Dark: "#9999a2"},
		ReadingAccent:       lipgloss.AdaptiveColor{Light: "#218bc4", Dark: "#52abff"},
		ToneInfo:            lipgloss.AdaptiveColor{Light: "#406bcd", Dark: "#76a2ff"},
		ToneOK:              lipgloss.AdaptiveColor{Light: "#08883e", Dark: "#53be70"},
		ToneWarn:            lipgloss.AdaptiveColor{Light: "#986600", Dark: "#db9400"},
		ToneDanger:          lipgloss.AdaptiveColor{Light: "#c43732", Dark: "#ff7266"},
		ToneNeutral:         lipgloss.AdaptiveColor{Light: "#67696f", Dark: "#9999a2"},
	},
	"ember": {
		ChromeAccent:        lipgloss.AdaptiveColor{Light: "#c34e13", Dark: "#f7993b"},
		ChromeInk:           lipgloss.AdaptiveColor{Light: "#342c28", Dark: "#dad5d0"},
		ChromeTextSecondary: lipgloss.AdaptiveColor{Light: "#59534f", Dark: "#a09b97"},
		ChromeDim:           lipgloss.AdaptiveColor{Light: "#aaa6a4", Dark: "#6a6561"},
		Rule:                lipgloss.AdaptiveColor{Light: "#e4dedc", Dark: "#161311"},
		CodeFg:              lipgloss.AdaptiveColor{Light: "#bf321d", Dark: "#f5855c"},
		CodeBg:              lipgloss.AdaptiveColor{Light: "#f5f3f2", Dark: "#2e2925"},
		ReadingMuted:        lipgloss.AdaptiveColor{Light: "#6e6764", Dark: "#a09993"},
		ReadingAccent:       lipgloss.AdaptiveColor{Light: "#bf321d", Dark: "#f5855c"},
		ToneInfo:            lipgloss.AdaptiveColor{Light: "#486ec0", Dark: "#7ba3f6"},
		ToneOK:              lipgloss.AdaptiveColor{Light: "#2c8647", Dark: "#68ba7b"},
		ToneWarn:            lipgloss.AdaptiveColor{Light: "#986600", Dark: "#d6962c"},
		ToneDanger:          lipgloss.AdaptiveColor{Light: "#ba453d", Dark: "#f27d72"},
		ToneNeutral:         lipgloss.AdaptiveColor{Light: "#6e6764", Dark: "#a09993"},
	},
	"fjord": {
		ChromeAccent:        lipgloss.AdaptiveColor{Light: "#2f56b1", Dark: "#68a2e8"},
		ChromeInk:           lipgloss.AdaptiveColor{Light: "#262b36", Dark: "#d0d5db"},
		ChromeTextSecondary: lipgloss.AdaptiveColor{Light: "#4e525b", Dark: "#969aa1"},
		ChromeDim:           lipgloss.AdaptiveColor{Light: "#a3a6ab", Dark: "#60646b"},
		Rule:                lipgloss.AdaptiveColor{Light: "#dde0e5", Dark: "#121417"},
		CodeFg:              lipgloss.AdaptiveColor{Light: "#0f8299", Dark: "#53d6ea"},
		CodeBg:              lipgloss.AdaptiveColor{Light: "#f2f3f5", Dark: "#24282f"},
		ReadingMuted:        lipgloss.AdaptiveColor{Light: "#66696f", Dark: "#959ba2"},
		ReadingAccent:       lipgloss.AdaptiveColor{Light: "#0f8299", Dark: "#53d6ea"},
		ToneInfo:            lipgloss.AdaptiveColor{Light: "#4a6ebc", Dark: "#82a4e9"},
		ToneOK:              lipgloss.AdaptiveColor{Light: "#32854a", Dark: "#74b783"},
		ToneWarn:            lipgloss.AdaptiveColor{Light: "#986600", Dark: "#cf9a4a"},
		ToneDanger:          lipgloss.AdaptiveColor{Light: "#b74941", Dark: "#e7857b"},
		ToneNeutral:         lipgloss.AdaptiveColor{Light: "#66696f", Dark: "#959ba2"},
	},
}

// Resolve returns the pdrender Palette for a theme id, defaulting to evergreen
// for an unknown or empty id (never a partial/zero palette).
func Resolve(theme string) Palette {
	if p, ok := genPalette[theme]; ok {
		return p
	}
	return genPalette[DefaultTheme]
}
