// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

package pdrender

import "github.com/charmbracelet/lipgloss"

// Generated semantic status tones (design/tokens.json color.status → hex).
var (
	GenToneInfo   = lipgloss.AdaptiveColor{Light: "#3b82f6", Dark: "#3b82f6"}
	GenToneOK     = lipgloss.AdaptiveColor{Light: "#137236", Dark: "#45c474"}
	GenToneWarn   = lipgloss.AdaptiveColor{Light: "#ba7008", Dark: "#f8ab25"}
	GenToneDanger = lipgloss.AdaptiveColor{Light: "#b42222", Dark: "#ef6161"}
)

// Generated neutral callout tone (design/tokens.json color.cliCalloutNeutral).
var GenToneNeutral = lipgloss.AdaptiveColor{Light: "#374151", Dark: "#9ca3af"}

// Generated chrome + reading-accent tokens (design/tokens.json color.* → hex).
var (
	GenPrimary       = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenPrimaryFg     = lipgloss.AdaptiveColor{Light: "#ffffff", Dark: "#0b1e18"}
	GenInk           = lipgloss.AdaptiveColor{Light: "#09090b", Dark: "#f2f2f2"}
	GenDim           = lipgloss.AdaptiveColor{Light: "#71717a", Dark: "#a1a1aa"}
	GenRule          = lipgloss.AdaptiveColor{Light: "#e4e4e7", Dark: "#27272a"}
	GenReadingAccent = lipgloss.AdaptiveColor{Light: "#a23925", Dark: "#d98a6a"}
)

// Generated CLI-chrome tokens (design/tokens.json color.cliChrome → hex).
// pdrender's own copy (it can't import internal/semrole); threaded by
// theme.go's pdAccent/pdInk/pdBody/pdDim chrome vars.
var (
	GenChromeAccent        = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenChromeInk           = lipgloss.AdaptiveColor{Light: "#18181b", Dark: "#e4e4e7"}
	GenChromeTextSecondary = lipgloss.AdaptiveColor{Light: "#3f3f46", Dark: "#a1a1aa"}
	GenChromeDim           = lipgloss.AdaptiveColor{Light: "#a1a1aa", Dark: "#52525b"}
)

// Generated code-block tones (design/tokens.json color.code → hex).
var (
	GenCodeFg = lipgloss.AdaptiveColor{Light: "#be123c", Dark: "#fda4af"}
	GenCodeBg = lipgloss.AdaptiveColor{Light: "#f4f4f5", Dark: "#27272a"}
)

// Generated reading tokens (design/tokens.json font.reading / type.reading).
const (
	GenReadingFontStack     = "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Charter, Georgia, \"Source Serif 4\", serif"
	GenReadingHeadingWeight = 600
	GenReadingBodySize      = 18
)

// DefaultTheme is the built-in evergreen skin. Resolve defaults to it for any
// unknown/empty theme id, so today (evergreen-only) every id yields these exact
// bytes — the styleguide golden stays frozen. Adding theme N+1 grows genPalette
// (one keyed entry); theme.go's buildTheme already reads Resolve(themeID).
const DefaultTheme = "evergreen"

// Palette is one theme's resolved pdrender token set. The Chrome* roles are the
// zinc cliChrome family (ChromeInk/ChromeDim are NOT the warmer reading Ink/Dim —
// the decoy guard theme.go documents); ReadingMuted/ReadingAccent are the reading
// family; Tone* are the semantic status tones the Callout builder paints.
type Palette struct {
	ChromeAccent        lipgloss.AdaptiveColor
	ChromeInk           lipgloss.AdaptiveColor
	ChromeTextSecondary lipgloss.AdaptiveColor
	ChromeDim           lipgloss.AdaptiveColor
	Rule                lipgloss.AdaptiveColor
	CodeFg              lipgloss.AdaptiveColor
	CodeBg              lipgloss.AdaptiveColor
	ReadingMuted        lipgloss.AdaptiveColor
	ReadingAccent       lipgloss.AdaptiveColor
	ToneInfo            lipgloss.AdaptiveColor
	ToneOK              lipgloss.AdaptiveColor
	ToneWarn            lipgloss.AdaptiveColor
	ToneDanger          lipgloss.AdaptiveColor
	ToneNeutral         lipgloss.AdaptiveColor
}

// genPalette keys each theme's Palette by id. Values REFERENCE the Gen* vars
// above (no re-typed literals) so the evergreen skin is byte-identical to them.
var genPalette = map[string]Palette{
	"evergreen": {
		ChromeAccent:        GenChromeAccent,
		ChromeInk:           GenChromeInk,
		ChromeTextSecondary: GenChromeTextSecondary,
		ChromeDim:           GenChromeDim,
		Rule:                GenRule,
		CodeFg:              GenCodeFg,
		CodeBg:              GenCodeBg,
		ReadingMuted:        GenDim,
		ReadingAccent:       GenReadingAccent,
		ToneInfo:            GenToneInfo,
		ToneOK:              GenToneOK,
		ToneWarn:            GenToneWarn,
		ToneDanger:          GenToneDanger,
		ToneNeutral:         GenToneNeutral,
	},
}

// Resolve returns the pdrender Palette for a theme id, defaulting to evergreen
// for an unknown or empty id (never a partial/zero palette).
func Resolve(theme string) Palette {
	if p, ok := genPalette[theme]; ok {
		return p
	}
	return genPalette[DefaultTheme]
}
