/**
 * Web leg of the cross-surface PAPER-COMPONENT golden-parity spine.
 *
 * `fixtures/<type>.golden.json` is generated by
 * `mix barkpark.paper_components.gen_golden_parity` and mirrored byte-for-byte
 * into the api + internal/pdrender trees. Each fixture carries the authored
 * `input` block plus an `expected` STRUCTURAL PROJECTION (node roles / column
 * labels / row titles / glyph-role / nesting). This suite proves the web reader's
 * task-board model (`taskBoardColumns` + the exported label/glyph constants that
 * `portable-doc.tsx` renders from) REALIZES that projection — the web half of the
 * shared contract.
 *
 * The web reader has no RTL/testing-library; like the sheet golden-parity web leg
 * it asserts the pure MODEL the component consumes, not the DOM. `portable-doc.tsx`
 * maps `taskBoardColumns(...).columns[key]` -> a labelled column with
 * `TASK_BOARD_GLYPHS[key]` and one card per row, so realizing the model realizes
 * the render.
 *
 * SCOPE (S1): task-board only. status-legend has NO web reader case yet — it is
 * the FIRST S2 item (see the skipped placeholder below); the harness is proven on
 * task-board for web.
 *
 * COVERAGE (honest scope — subset-parity, projection ⊆ native): for every column
 * PRESENT in the projection, all three surfaces agree on label + count + ordered
 * card titles + glyph-role (this leg asserts the web model at exact equality). NOT
 * COVERED, FILED not fixed: (a) task-board `open`-task DROP — the Elixir 4-column
 * omit-empty view drops `open` tasks this 5-column web view keeps; a ⊆-projection
 * cannot catch an omission, so the fixture input omits `open`; owned by
 * bug-taskboard-drops-open-tasks (which carries the open-inclusive test that
 * catches the real bug). (b) status/label PROSE ("in progress" vs "progress"); the
 * projection shares role + glyph, not meaning text; owned by
 * au-w5-status-prose-parity (also owns "board labels are two agreeing copies, not
 * one manifest source"). The harness never implies parity it does not hold.
 *
 * Run: `node --test __tests__/component-golden-parity.test.ts` (or `pnpm test`).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  taskBoardColumns,
  TASK_BOARD_COLUMN_LABELS,
  TASK_BOARD_GLYPHS,
  type TaskBoardColumnKey,
  type TaskBoardRow,
} from "../lib/task-board-columns.ts";

interface BoardProjection {
  container_role: string;
  columns: Array<{
    role: string;
    label: string;
    glyph_role: string;
    count: number;
    cards: Array<{ title: string }>;
  }>;
}

interface ComponentGolden {
  type: string;
  input: { type: string; snapshot?: TaskBoardRow[] };
  expected: BoardProjection;
}

const fixture: ComponentGolden = JSON.parse(
  readFileSync(
    new URL("./fixtures/task-board.golden.json", import.meta.url),
    "utf8",
  ),
);

/** The projection speaks the shared manifest role vocabulary (open/ready/progress/
 * blocked/done/cancel); the web column keys use `in_progress` for the progress
 * role. This maps a projection role to its web column key. */
const ROLE_TO_WEB_KEY: Record<string, TaskBoardColumnKey> = {
  open: "open",
  ready: "ready",
  progress: "in_progress",
  blocked: "blocked",
  done: "done",
};

/* ── floors — fail LOUD before any leg can go vacuous ── */

function floor(cond: boolean, msg: string): void {
  if (!cond) throw new Error(`component-golden floor violated: ${msg}`);
}

floor(fixture.type === "task-board", `fixture type is ${fixture.type}`);
floor(fixture.expected.container_role === "board", "container_role is not board");
floor(
  fixture.expected.columns.length >= 3,
  `projection has ${fixture.expected.columns.length} columns, need >= 3`,
);
floor(Array.isArray(fixture.input.snapshot), "input.snapshot missing");

const { columns } = taskBoardColumns(fixture.input.snapshot ?? []);

test("web task-board model realizes every projection column (key · label · count · card titles)", () => {
  for (const col of fixture.expected.columns) {
    const key = ROLE_TO_WEB_KEY[col.role];
    assert.ok(key, `projection role ${col.role} has no web column key`);

    // Label parity — the shared column header the reader renders.
    assert.equal(
      TASK_BOARD_COLUMN_LABELS[key],
      col.label,
      `label for ${col.role}/${key}`,
    );

    // Bucketing + count + ordered card titles all realize the projection.
    const rendered = columns[key];
    assert.equal(rendered.length, col.count, `count for ${col.role}`);
    assert.deepEqual(
      rendered.map((r) => String(r.title ?? "")),
      col.cards.map((c) => c.title),
      `card titles for ${col.role}`,
    );
  }
});

test("web task-board renders a glyph for every projection glyph-role", () => {
  for (const col of fixture.expected.columns) {
    const key = ROLE_TO_WEB_KEY[col.glyph_role];
    assert.ok(
      typeof TASK_BOARD_GLYPHS[key] === "string" && TASK_BOARD_GLYPHS[key].length > 0,
      `no web glyph for glyph-role ${col.glyph_role}`,
    );
  }
});

test("web glyph chars match the shared manifest for non-spinner roles (legend fixture)", () => {
  // Cross-fixture glyph parity: the status-legend fixture carries the Elixir/
  // manifest glyph char per role; the web board glyph for the same NON-spinner
  // role must be that exact codepoint (○ ready · ! blocked · ✓ done). The
  // spinner role (progress→in_progress) is surface-local and excluded.
  interface LegendRow {
    role: string;
    glyph: string;
    spinner: boolean;
  }
  const legend = JSON.parse(
    readFileSync(
      new URL("./fixtures/status-legend.golden.json", import.meta.url),
      "utf8",
    ),
  ) as { expected: { rows: LegendRow[] } };

  for (const row of legend.expected.rows) {
    if (row.spinner) continue;
    const key = ROLE_TO_WEB_KEY[row.role];
    if (!key) continue; // cancel is folded to a tally, not a rendered column
    assert.equal(
      TASK_BOARD_GLYPHS[key],
      row.glyph,
      `web glyph for ${row.role} must equal the manifest glyph`,
    );
  }
});

/* ══ S2: the task-tracking / composition component family ══════════════════════
 *
 * Each type's web PROJECTOR (`web/lib/component-projections.ts`, which
 * portable-doc.tsx renders FROM) must produce the SAME structural projection the
 * Elixir generator committed. deepEqual against the golden `expected` — EXACT,
 * never substring — so a web divergence from the shared truth reds here (matching
 * the task-board leg's exactness). status-legend leads (the S1 skip, now green);
 * the recursive containers (columns / terminal) come last. */

import {
  statusLegendProjection,
  notesProjection,
  noteProjection,
  cardsProjection,
  cardProjection,
  pipelineProjection,
  stageProjection,
  taskDetailProjection,
  roadmapProjection,
  columnsProjection,
  terminalProjection,
  type LegendProjection,
  type NotesProjection,
  type NoteProjection,
  type CardsProjection,
  type CardProjection,
  type PipelineProjection,
  type StageProjection,
  type TaskDetailProjection,
  type RoadmapProjection,
  type ColumnsProjection,
  type TerminalProjection,
} from "../lib/component-projections.ts";

/** Load a `<type>.golden.json` fixture (input + expected projection). */
function loadFixture(type: string): { input: Record<string, unknown>; expected: unknown } {
  return JSON.parse(
    readFileSync(new URL(`./fixtures/${type}.golden.json`, import.meta.url), "utf8"),
  );
}

/** Every S2 type: its web projector must realize the committed golden projection
 * EXACTLY. `input` is ignored by status-legend (static ladder), read by the rest. */
const S2_CASES: Array<{
  type: string;
  project: (input: Record<string, unknown>) => unknown;
}> = [
  { type: "status-legend", project: () => statusLegendProjection() },
  { type: "notes", project: notesProjection },
  { type: "note", project: noteProjection },
  { type: "cards", project: cardsProjection },
  { type: "card", project: cardProjection },
  { type: "pipeline", project: pipelineProjection },
  { type: "stage", project: stageProjection },
  { type: "task-detail", project: taskDetailProjection },
  { type: "roadmap", project: roadmapProjection },
  // recursive containers last — their projection expresses child NESTING.
  { type: "columns", project: columnsProjection },
  { type: "terminal", project: terminalProjection },
];

for (const { type, project } of S2_CASES) {
  test(`web ${type} projector realizes the golden projection (exact)`, () => {
    const fx = loadFixture(type);
    assert.deepEqual(project(fx.input), fx.expected);
  });
}

/* ══ S2 (LOAD-BEARING): the REAL RENDER realizes the projection ═══════════════
 *
 * The deepEqual loop above proves projector == golden — a valid SECOND layer.
 * THIS layer is the load-bearing one: it drives the ACTUAL reader render
 * (`renderBlock` from portable-doc.tsx) to static HTML exactly as the app lowers
 * it, then asserts the shared projection's fields (container role, labels, card
 * titles, glyph-role, container NESTING) appear in that rendered DOM. A JSX
 * regression — a dropped field, a mis-wired projector→DOM, a container that
 * re-derives its own structure (columns/terminal never import the projector) —
 * reds HERE even while the projector still matches the golden. Proven non-
 * vacuous: three render tampers (status-legend role, card title-drop, columns
 * nesting) each red this suite; each passed green under the projector-only leg.
 *
 * renderBlock is JSX + `@/` aliases behind a `next/script`/sheets import graph
 * node can't load bare, so support/tsx-loader.mjs transpiles the REAL source
 * with the app's `jsx: react-jsx` and stubs ONLY the two off-render-path client
 * components. No render logic under test is stubbed — every one of the 12
 * component cases runs for real. */

import { register } from "node:module";
import { renderToStaticMarkup } from "react-dom/server";
import type { Block } from "../lib/papers.ts";

register("./support/tsx-loader.mjs", import.meta.url);
const { renderBlock } = await import("../components/portable-doc.tsx");

function renderHtml(input: Record<string, unknown>): string {
  return renderToStaticMarkup(renderBlock(input as Block, "k"));
}

function present(html: string, needle: string, label: string): void {
  assert.ok(
    html.includes(needle),
    `${label}: rendered DOM is missing ${JSON.stringify(needle)}`,
  );
}

/** Leaf text of an authored child block (paragraph content / scalar) — used to
 * assert that a container (columns / terminal) actually NESTS its children's
 * rendered content, catching a dropped or mis-nested child. */
function leafText(node: unknown): string {
  if (!node || typeof node !== "object") return "";
  const n = node as { content?: unknown; value?: unknown; text?: unknown };
  if (Array.isArray(n.content)) return n.content.map(leafText).join("");
  if (typeof n.value === "string") return n.value;
  if (typeof n.text === "string") return n.text;
  return "";
}

/* ── per-type render assertions: the projection's fields MUST appear in the
 * rendered DOM. Field strings are exact (a rename/drop reds). ── */

const CARD_TONE_STRIPE: Record<string, string> = {
  info: "border-l-blue-400",
  ok: "border-l-emerald-400",
  warn: "border-l-amber-400",
  danger: "border-l-red-400",
};
const ROADMAP_ROLE_BAR: Record<string, string> = {
  open: "bg-zinc-400",
  ready: "bg-zinc-500",
  progress: "bg-blue-500",
  blocked: "bg-amber-500",
  done: "bg-teal-500",
  cancel: "bg-zinc-300",
};

test("web status-legend RENDER realizes the legend projection (role + glyph)", () => {
  const html = renderHtml({ type: "status-legend" });
  const exp = loadFixture("status-legend").expected as LegendProjection;
  for (const r of exp.rows) {
    present(html, `>${r.role}</dt>`, `legend role ${r.role}`);
    present(html, `>${r.spinner ? "⠋" : r.glyph}</span>`, `legend glyph ${r.role}`);
  }
});

test("web notes RENDER realizes every note row (label · lead · text)", () => {
  const input = loadFixture("notes").input;
  const html = renderHtml(input);
  const exp = loadFixture("notes").expected as NotesProjection;
  for (const row of exp.rows) {
    present(html, `>${row.label}</span>`, `notes label ${row.label}`);
    present(html, `>${row.lead}</b>`, `notes lead ${row.lead}`);
    present(html, row.text, `notes text ${row.text}`);
  }
});

test("web note RENDER realizes the single row (label · lead · text)", () => {
  const input = loadFixture("note").input;
  const html = renderHtml(input);
  const exp = loadFixture("note").expected as NoteProjection;
  present(html, `>${exp.label}</span>`, "note label");
  present(html, `>${exp.lead}</b>`, "note lead");
  present(html, exp.text, "note text");
});

test("web cards RENDER realizes every card (title · text · tone stripe)", () => {
  const input = loadFixture("cards").input;
  const html = renderHtml(input);
  const exp = loadFixture("cards").expected as CardsProjection;
  for (const c of exp.cards) {
    present(html, `>${c.title}</p>`, `cards title ${c.title}`);
    present(html, `>${c.text}</p>`, `cards text ${c.text}`);
    if (c.tone) present(html, CARD_TONE_STRIPE[c.tone], `cards tone ${c.tone}`);
  }
});

test("web card RENDER realizes title + body (model B: text present)", () => {
  const input = loadFixture("card").input;
  const html = renderHtml(input);
  const exp = loadFixture("card").expected as CardProjection;
  // Model B (au-w5-card-slot-parity): the card recurses its title slot to a
  // semantic <h_> and its body to a <p>, dropping the old flat <p> title chrome —
  // so this leg asserts the shared projection FLOOR (title/body TEXT present),
  // mirroring the Elixir substring relax in component_golden_parity_test.exs. The
  // model-B slot order + tone + image fast-path are the GRADUATION target, not yet
  // render-asserted here (the projection stays frozen this wave). Still reds if the
  // title/body TEXT is dropped from the render.
  present(html, exp.title, "card title");
  present(html, exp.body, "card body");
});

test("web pipeline RENDER realizes every node (kind · title · detail)", () => {
  const input = loadFixture("pipeline").input;
  const html = renderHtml(input);
  const exp = loadFixture("pipeline").expected as PipelineProjection;
  for (const n of exp.nodes) {
    present(html, `>${n.kind}</p>`, `pipeline kind ${n.kind}`);
    present(html, `>${n.title}</p>`, `pipeline title ${n.title}`);
    present(html, `>${n.detail}</p>`, `pipeline detail ${n.detail}`);
  }
});

test("web stage RENDER realizes kind · title · detail", () => {
  const input = loadFixture("stage").input;
  const html = renderHtml(input);
  const exp = loadFixture("stage").expected as StageProjection;
  present(html, `>${exp.kind}</p>`, "stage kind");
  present(html, `>${exp.title}</p>`, "stage title");
  present(html, `>${exp.detail}</p>`, "stage detail");
});

test("web task-detail RENDER realizes title + timeline + criteria tally", () => {
  const input = loadFixture("task-detail").input;
  const html = renderHtml(input);
  const exp = loadFixture("task-detail").expected as TaskDetailProjection;
  present(html, `>${exp.title}</p>`, "task-detail title");
  // Timeline is now COVERED: every ordered cell's label realizes in the render
  // (a dropped/renamed timeline cell reds here even while the projector matches).
  if (exp.sections.includes("timeline")) {
    assert.ok(exp.timeline.length > 0, "timeline section present but no entries");
    for (const seg of exp.timeline) {
      present(html, `>${seg.label}</span>`, `task-detail timeline label ${seg.label}`);
    }
  }
  if (exp.sections.includes("criteria")) {
    present(
      html,
      `Criteria · ${exp.criteria.met}/${exp.criteria.total}`,
      "task-detail criteria tally",
    );
  }
});

test("web roadmap RENDER realizes scale + every lane (title · role bar)", () => {
  const input = loadFixture("roadmap").input;
  const html = renderHtml(input);
  const exp = loadFixture("roadmap").expected as RoadmapProjection;
  for (const cell of exp.scale) present(html, `>${cell}</span>`, `roadmap scale ${cell}`);
  for (const lane of exp.lanes) {
    present(html, `>${lane.title}</span>`, `roadmap lane ${lane.title}`);
    present(html, ROADMAP_ROLE_BAR[lane.role], `roadmap role bar ${lane.role}`);
  }
});

test("web columns RENDER nests each column's children (count + content)", () => {
  const input = loadFixture("columns").input;
  const html = renderHtml(input);
  const exp = loadFixture("columns").expected as ColumnsProjection;
  // Column count is expressed in the grid template — a flatten/mis-nest reds.
  present(html, `repeat(${exp.columns.length}, `, "columns grid count");
  const cols = Array.isArray(input.columns) ? (input.columns as unknown[][]) : [];
  exp.columns.forEach((children, ci) => {
    children.forEach((_type, cj) => {
      const text = leafText(cols[ci]?.[cj]);
      if (text) present(html, text, `columns[${ci}] child ${cj}`);
    });
  });
});

test("web terminal RENDER realizes chrome (title · live · footer) + nests children", () => {
  const input = loadFixture("terminal").input;
  const html = renderHtml(input);
  const exp = loadFixture("terminal").expected as TerminalProjection;
  present(html, `>${exp.title}</span>`, "terminal title");
  present(html, exp.footer, "terminal footer");
  if (exp.live) present(html, ">live</span>", "terminal live badge");
  const kids = Array.isArray(input.children)
    ? (input.children as unknown[])
    : Array.isArray(input.blocks)
      ? (input.blocks as unknown[])
      : [];
  exp.children.forEach((_type, ci) => {
    const text = leafText(kids[ci]);
    if (text) present(html, text, `terminal child ${ci}`);
  });
});

test("web task-board RENDER realizes every projection column (label · card titles)", () => {
  const html = renderHtml(fixture.input as Record<string, unknown>);
  for (const col of fixture.expected.columns) {
    present(html, `${col.label}</span>`, `board label ${col.label}`);
    for (const card of col.cards) {
      present(html, `>${card.title}</p>`, `board card ${card.title}`);
    }
  }
});
