/**
 * Web leg of the cross-surface PAPER-COMPONENT golden-parity spine.
 *
 * `fixtures/<type>.golden.json` is generated by
 * `mix barkpark.paper_components.gen_golden_parity` and mirrored byte-for-byte
 * into the api + internal/pdrender trees. Each fixture carries the authored
 * `input` block plus an `expected` STRUCTURAL PROJECTION (node roles / column
 * labels / row titles / glyph-role / nesting). This suite proves the web reader's
 * task-board model (`taskBoardColumns` + the exported label/glyph constants that
 * `portable-doc.tsx` renders from) REALIZES that projection — the web half of the
 * shared contract.
 *
 * The web reader has no RTL/testing-library; like the sheet golden-parity web leg
 * it asserts the pure MODEL the component consumes, not the DOM. `portable-doc.tsx`
 * maps `taskBoardColumns(...).columns[key]` -> a labelled column with
 * `TASK_BOARD_GLYPHS[key]` and one card per row, so realizing the model realizes
 * the render.
 *
 * SCOPE (S1): task-board only. status-legend has NO web reader case yet — it is
 * the FIRST S2 item (see the skipped placeholder below); the harness is proven on
 * task-board for web.
 *
 * COVERAGE (honest scope — subset-parity, projection ⊆ native): for every column
 * PRESENT in the projection, all three surfaces agree on label + count + ordered
 * card titles + glyph-role (this leg asserts the web model at exact equality). NOT
 * COVERED, FILED not fixed: (a) task-board `open`-task DROP — the Elixir 4-column
 * omit-empty view drops `open` tasks this 5-column web view keeps; a ⊆-projection
 * cannot catch an omission, so the fixture input omits `open`; owned by
 * bug-taskboard-drops-open-tasks (which carries the open-inclusive test that
 * catches the real bug). (b) status/label PROSE ("in progress" vs "progress"); the
 * projection shares role + glyph, not meaning text; owned by
 * au-w5-status-prose-parity (also owns "board labels are two agreeing copies, not
 * one manifest source"). The harness never implies parity it does not hold.
 *
 * Run: `node --test __tests__/component-golden-parity.test.ts` (or `pnpm test`).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  taskBoardColumns,
  TASK_BOARD_COLUMN_LABELS,
  TASK_BOARD_GLYPHS,
  type TaskBoardColumnKey,
  type TaskBoardRow,
} from "../lib/task-board-columns.ts";

interface BoardProjection {
  container_role: string;
  columns: Array<{
    role: string;
    label: string;
    glyph_role: string;
    count: number;
    cards: Array<{ title: string }>;
  }>;
}

interface ComponentGolden {
  type: string;
  input: { type: string; snapshot?: TaskBoardRow[] };
  expected: BoardProjection;
}

const fixture: ComponentGolden = JSON.parse(
  readFileSync(
    new URL("./fixtures/task-board.golden.json", import.meta.url),
    "utf8",
  ),
);

/** The projection speaks the shared manifest role vocabulary (open/ready/progress/
 * blocked/done/cancel); the web column keys use `in_progress` for the progress
 * role. This maps a projection role to its web column key. */
const ROLE_TO_WEB_KEY: Record<string, TaskBoardColumnKey> = {
  open: "open",
  ready: "ready",
  progress: "in_progress",
  blocked: "blocked",
  done: "done",
};

/* ── floors — fail LOUD before any leg can go vacuous ── */

function floor(cond: boolean, msg: string): void {
  if (!cond) throw new Error(`component-golden floor violated: ${msg}`);
}

floor(fixture.type === "task-board", `fixture type is ${fixture.type}`);
floor(fixture.expected.container_role === "board", "container_role is not board");
floor(
  fixture.expected.columns.length >= 3,
  `projection has ${fixture.expected.columns.length} columns, need >= 3`,
);
floor(Array.isArray(fixture.input.snapshot), "input.snapshot missing");

const { columns } = taskBoardColumns(fixture.input.snapshot ?? []);

test("web task-board model realizes every projection column (key · label · count · card titles)", () => {
  for (const col of fixture.expected.columns) {
    const key = ROLE_TO_WEB_KEY[col.role];
    assert.ok(key, `projection role ${col.role} has no web column key`);

    // Label parity — the shared column header the reader renders.
    assert.equal(
      TASK_BOARD_COLUMN_LABELS[key],
      col.label,
      `label for ${col.role}/${key}`,
    );

    // Bucketing + count + ordered card titles all realize the projection.
    const rendered = columns[key];
    assert.equal(rendered.length, col.count, `count for ${col.role}`);
    assert.deepEqual(
      rendered.map((r) => String(r.title ?? "")),
      col.cards.map((c) => c.title),
      `card titles for ${col.role}`,
    );
  }
});

test("web task-board renders a glyph for every projection glyph-role", () => {
  for (const col of fixture.expected.columns) {
    const key = ROLE_TO_WEB_KEY[col.glyph_role];
    assert.ok(
      typeof TASK_BOARD_GLYPHS[key] === "string" && TASK_BOARD_GLYPHS[key].length > 0,
      `no web glyph for glyph-role ${col.glyph_role}`,
    );
  }
});

test("web glyph chars match the shared manifest for non-spinner roles (legend fixture)", () => {
  // Cross-fixture glyph parity: the status-legend fixture carries the Elixir/
  // manifest glyph char per role; the web board glyph for the same NON-spinner
  // role must be that exact codepoint (○ ready · ! blocked · ✓ done). The
  // spinner role (progress→in_progress) is surface-local and excluded.
  interface LegendRow {
    role: string;
    glyph: string;
    spinner: boolean;
  }
  const legend = JSON.parse(
    readFileSync(
      new URL("./fixtures/status-legend.golden.json", import.meta.url),
      "utf8",
    ),
  ) as { expected: { rows: LegendRow[] } };

  for (const row of legend.expected.rows) {
    if (row.spinner) continue;
    const key = ROLE_TO_WEB_KEY[row.role];
    if (!key) continue; // cancel is folded to a tally, not a rendered column
    assert.equal(
      TASK_BOARD_GLYPHS[key],
      row.glyph,
      `web glyph for ${row.role} must equal the manifest glyph`,
    );
  }
});

// S2 FIRST ITEM: status-legend has no web reader case in portable-doc.tsx. When
// S2 adds it, drop `{ skip: ... }` and assert the six-rung ladder realizes the
// status-legend projection here.
test("status-legend web reader case (S2 — not yet implemented)", { skip: "S2: portable-doc.tsx has no status-legend case yet" }, () => {});
