/**
 * Web leg of the cross-surface PAPER-COMPONENT golden-parity spine.
 *
 * `fixtures/<type>.golden.json` is generated by
 * `mix barkpark.paper_components.gen_golden_parity` and mirrored byte-for-byte
 * into the api + internal/pdrender trees. Each fixture carries the authored
 * `input` block plus an `expected` STRUCTURAL PROJECTION (node roles / column
 * labels / row titles / glyph-role / nesting). This suite proves the web reader
 * REALIZES that projection — the web half of the shared contract. The web render
 * path is the canonical `@barkpark/react` `renderPortableDocument` (the old web
 * fork `portable-doc.tsx` and its orphaned model `task-board-columns.ts` are
 * both deleted), so the task-board leg asserts the CANONICAL RENDER — label,
 * count, ordered card titles, glyph — directly against the golden projection.
 *
 * The web reader has no RTL/testing-library; the S2 projector legs assert the
 * pure MODEL (`component-projections.ts`) and the render legs assert the
 * canonical HTML string emitter — still no browser and no DOM library.
 *
 * SCOPE (S1): task-board only. status-legend has NO web reader case yet — it is
 * the FIRST S2 item (see the skipped placeholder below); the harness is proven on
 * task-board for web.
 *
 * COVERAGE (honest scope — subset-parity, projection ⊆ native): for every column
 * PRESENT in the projection, all three surfaces agree on label + count + ordered
 * card titles + glyph-role (the task-board leg asserts the canonical RENDER at
 * exact equality). NOT
 * COVERED, FILED not fixed: (a) task-board `open`-task DROP — the Elixir 4-column
 * omit-empty view drops `open` tasks this 5-column web view keeps; a ⊆-projection
 * cannot catch an omission, so the fixture input omits `open`; owned by
 * bug-taskboard-drops-open-tasks (which carries the open-inclusive test that
 * catches the real bug). COVERED since au-w5-status-prose-parity: the status LABEL
 * prose is ONE manifest source; the legend projection asserts the canonical label
 * TEXT ("in progress"/"cancelled") and the web RENDER realizes it (the
 * status-legend RENDER leg below asserts `>${label}</dt>`); board LABELS are
 * asserted against the canonical render, which derives them from the ONE
 * manifest ladder (`@barkpark/react` STATUS_ROLES) — web keeps no hand copy.
 * Legend MEANING is not rendered by the web reader (name-only web parity, a
 * SUPERSET the Elixir/TUI legends carry). The harness never implies parity it does
 * not hold.
 *
 * Run: `node --test __tests__/component-golden-parity.test.ts` (or `pnpm test`).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

interface BoardProjection {
  container_role: string;
  columns: Array<{
    role: string;
    label: string;
    glyph_role: string;
    count: number;
    cards: Array<{ title: string }>;
  }>;
}

interface ComponentGolden {
  type: string;
  input: { type: string; snapshot?: Array<Record<string, unknown>> };
  expected: BoardProjection;
}

const fixture: ComponentGolden = JSON.parse(
  readFileSync(
    new URL("./fixtures/task-board.golden.json", import.meta.url),
    "utf8",
  ),
);

/* ── floors — fail LOUD before any leg can go vacuous ── */

function floor(cond: boolean, msg: string): void {
  if (!cond) throw new Error(`component-golden floor violated: ${msg}`);
}

floor(fixture.type === "task-board", `fixture type is ${fixture.type}`);
floor(fixture.expected.container_role === "board", "container_role is not board");
floor(
  fixture.expected.columns.length >= 3,
  `projection has ${fixture.expected.columns.length} columns, need >= 3`,
);
floor(Array.isArray(fixture.input.snapshot), "input.snapshot missing");

/* ══ S2: the task-tracking / composition component family ══════════════════════
 *
 * Each type's web PROJECTOR (`web/lib/component-projections.ts`, which
 * the deleted portable-doc.tsx fork once rendered FROM) must produce the SAME structural projection the
 * Elixir generator committed. deepEqual against the golden `expected` — EXACT,
 * never substring — so a web divergence from the shared truth reds here (matching
 * the task-board leg's exactness). status-legend leads (the S1 skip, now green);
 * the recursive containers (columns / terminal) come last. */

import {
  statusLegendProjection,
  notesProjection,
  noteProjection,
  cardsProjection,
  cardProjection,
  pipelineProjection,
  stageProjection,
  taskDetailProjection,
  roadmapProjection,
  columnsProjection,
  terminalProjection,
  sectionProjection,
  type LegendProjection,
  type NotesProjection,
  type NoteProjection,
  type CardsProjection,
  type CardProjection,
  type PipelineProjection,
  type StageProjection,
  type TaskDetailProjection,
  type RoadmapProjection,
  type ColumnsProjection,
  type TerminalProjection,
  type SectionProjection,
} from "../lib/component-projections.ts";

/** Load a `<type>.golden.json` fixture (input + expected projection). */
function loadFixture(type: string): { input: Record<string, unknown>; expected: unknown } {
  return JSON.parse(
    readFileSync(new URL(`./fixtures/${type}.golden.json`, import.meta.url), "utf8"),
  );
}

/** Every S2 type: its web projector must realize the committed golden projection
 * EXACTLY. `input` is ignored by status-legend (static ladder), read by the rest. */
const S2_CASES: Array<{
  type: string;
  project: (input: Record<string, unknown>) => unknown;
}> = [
  { type: "status-legend", project: () => statusLegendProjection() },
  { type: "notes", project: notesProjection },
  { type: "note", project: noteProjection },
  { type: "cards", project: cardsProjection },
  { type: "card", project: cardProjection },
  { type: "pipeline", project: pipelineProjection },
  { type: "stage", project: stageProjection },
  { type: "task-detail", project: taskDetailProjection },
  { type: "roadmap", project: roadmapProjection },
  // recursive containers last — their projection expresses child NESTING.
  { type: "columns", project: columnsProjection },
  { type: "terminal", project: terminalProjection },
  // section (cd-12): the projector leg C1 ONLY — the deepEqual proof that the web
  // projector realizes the golden layout projection (mode · tracks · gap ·
  // authored-echo cells). The web RENDER leg (now the canonical @barkpark/react
  // renderer — the portable-doc.tsx fork is deleted) is cd-12b — filed, not
  // built here; NO section render-assert is added below.
  { type: "section", project: sectionProjection },
];

for (const { type, project } of S2_CASES) {
  test(`web ${type} projector realizes the golden projection (exact)`, () => {
    const fx = loadFixture(type);
    assert.deepEqual(project(fx.input), fx.expected);
  });
}

/* ══ S2 (LOAD-BEARING): the REAL RENDER realizes the projection ═══════════════
 *
 * The deepEqual loop above proves projector == golden — a valid SECOND layer.
 * THIS layer is the load-bearing one: it drives the ACTUAL canonical reader
 * render (`renderPortableDocument([block])` from `@barkpark/react`) to its `bp-*`
 * HTML string, then asserts the shared projection's fields (container role,
 * labels, card titles, glyph-role, container NESTING) appear in that rendered DOM.
 * A render regression — a dropped field, a mis-wired projector→DOM, a container
 * that re-derives its own structure (columns/terminal never import the projector)
 * — reds HERE even while the projector still matches the golden. Proven non-
 * vacuous: three render tampers (status-legend role, card title-drop, columns
 * nesting) each red this suite; each passed green under the projector-only leg.
 *
 * The render is the CANONICAL `@barkpark/react` surface now (W5 fork-retirement):
 * `renderPortableDocument([block])` emits the same `bp-*` article markup the
 * Phoenix reader and Go TUI produce, so the assertions below key off the `bp-*`
 * DOM (container class + the projection's label/title/text/glyph fields), NOT the
 * retired web fork's Tailwind classes. Pure string emitter — no browser, no JSX
 * transpile, no loader. Every one of the 12 component cases runs for real. */

import { renderPortableDocument, type Block } from "@barkpark/react";

function renderHtml(input: Record<string, unknown>): string {
  return renderPortableDocument([input as Block]);
}

function present(html: string, needle: string, label: string): void {
  assert.ok(
    html.includes(needle),
    `${label}: rendered DOM is missing ${JSON.stringify(needle)}`,
  );
}

/** Leaf text of an authored child block (paragraph content / scalar) — used to
 * assert that a container (columns / terminal) actually NESTS its children's
 * rendered content, catching a dropped or mis-nested child. */
function leafText(node: unknown): string {
  if (!node || typeof node !== "object") return "";
  const n = node as { content?: unknown; value?: unknown; text?: unknown };
  if (Array.isArray(n.content)) return n.content.map(leafText).join("");
  if (typeof n.value === "string") return n.value;
  if (typeof n.text === "string") return n.text;
  return "";
}

/* ── per-type render assertions: the projection's fields MUST appear in the
 * rendered DOM. Field strings are exact (a rename/drop reds). ── */

test("web status-legend RENDER realizes the legend projection (label + glyph)", () => {
  const html = renderHtml({ type: "status-legend" });
  const exp = loadFixture("status-legend").expected as LegendProjection;
  for (const r of exp.rows) {
    // GRADUATED (au-w5-status-prose-parity): the RENDER realizes the canonical
    // LABEL text (progress→"in progress", cancel→"cancelled"), not the raw role
    // slug — a wrong label render reds this leg (S2 render-assert discipline).
    present(html, `>${r.label}</span>`, `legend label ${r.label}`);
    // The spinner role emits an EMPTY CSS-animated glyph span (aria-labelled),
    // never a braille char; every other role prints its literal glyph.
    if (r.spinner) {
      present(html, `bp-g--${r.role}`, `legend spinner glyph role ${r.role}`);
      present(html, `aria-label="${r.label}"`, `legend spinner aria-label ${r.role}`);
    } else {
      present(html, `>${r.glyph}</span>`, `legend glyph ${r.role}`);
    }
  }
});

test("web notes RENDER realizes every note row (label · lead · text)", () => {
  const input = loadFixture("notes").input;
  const html = renderHtml(input);
  const exp = loadFixture("notes").expected as NotesProjection;
  for (const row of exp.rows) {
    present(html, `>${row.label}</span>`, `notes label ${row.label}`);
    present(html, `>${row.lead}</b>`, `notes lead ${row.lead}`);
    present(html, row.text, `notes text ${row.text}`);
  }
});

test("web note RENDER realizes the single row (label · lead · text)", () => {
  const input = loadFixture("note").input;
  const html = renderHtml(input);
  const exp = loadFixture("note").expected as NoteProjection;
  present(html, `>${exp.label}</span>`, "note label");
  present(html, `>${exp.lead}</b>`, "note lead");
  present(html, exp.text, "note text");
});

test("web cards RENDER realizes every card (title · text · tone class)", () => {
  const input = loadFixture("cards").input;
  const html = renderHtml(input);
  const exp = loadFixture("cards").expected as CardsProjection;
  for (const c of exp.cards) {
    present(html, `>${c.title}</div>`, `cards title ${c.title}`);
    present(html, `>${c.text}</div>`, `cards text ${c.text}`);
    // Canonical tone rides a `bp-card--<tone>` class (skinned by paper-surface.css),
    // not an inlined Tailwind stripe — a dropped tone loses the class and reds.
    if (c.tone) present(html, `bp-card--${c.tone}`, `cards tone ${c.tone}`);
  }
});

/** The authored render marker for one card slot, DERIVED from the fixture input
 * (never hand-typed): the media image alt attr, the title heading text, the body
 * paragraph plain text, the action label. */
function cardSlotMarker(input: Record<string, unknown>, slot: string): string {
  const s = (v: unknown): string =>
    typeof v === "string" ? v : typeof v === "number" ? String(v) : "";
  const slots = (input.slots ?? {}) as Record<string, Array<Record<string, unknown>>>;
  const first = (slots[slot] ?? [])[0] ?? {};
  switch (slot) {
    case "media":
      return `alt="${s(first.alt)}"`;
    case "title":
      return s(first.text);
    case "body": {
      const content = Array.isArray(first.content) ? first.content : [];
      return content.map((n) => s((n as Record<string, unknown>).value)).join("");
    }
    case "action":
      return s(first.label);
    default:
      return "";
  }
}

test("web card RENDER realizes the MODEL-B projection (ordered slots · tone tint · image · action)", () => {
  const input = loadFixture("card").input;
  const html = renderHtml(input);
  const exp = loadFixture("card").expected as CardProjection;

  // The projection's PRESENT slots realize IN ORDER in the rendered DOM — a
  // dropped or reordered slot in the @barkpark/react card emitter (projector
  // untouched) reds this ordered-spine check (the load-bearing non-vacuous proof).
  assert.deepEqual(
    exp.slots,
    ["media", "title", "body", "action"],
    "projection floor: card must exercise all four model-B slots",
  );
  let prev = -1;
  for (const slot of exp.slots) {
    const marker = cardSlotMarker(input, slot);
    const idx = html.indexOf(marker);
    assert.ok(idx >= 0, `card slot ${slot}: rendered DOM is missing ${JSON.stringify(marker)}`);
    assert.ok(idx > prev, `card slot ${slot} rendered out of model-B order (idx ${idx} <= ${prev})`);
    prev = idx;
  }

  // tone rides the canonical `bp-card--<tone>` class; media fast-path renders <img>.
  if (exp.tone) present(html, `bp-card--${exp.tone}`, `card tone class ${exp.tone}`);
  if (exp.media_fastpath) present(html, "<img", "card media image fast-path");
});

test("web pipeline RENDER realizes every node (kind · title · detail · source_role)", () => {
  const input = loadFixture("pipeline").input;
  const html = renderHtml(input);
  const exp = loadFixture("pipeline").expected as PipelineProjection;
  const roles = exp.nodes.map((n) => n.source_role);
  // non-vacuous: the fixture must exercise BOTH coercion branches.
  assert.ok(roles.includes("origin"), "fixture lost its source:true (origin) node");
  assert.ok(
    roles.includes("provenance"),
    'fixture lost its source:"text" (provenance) node',
  );
  for (const n of exp.nodes) {
    present(html, `>${n.kind}</div>`, `pipeline kind ${n.kind}`);
    present(html, `>${n.title}</div>`, `pipeline title ${n.title}`);
    present(html, `>${n.detail}</div>`, `pipeline detail ${n.detail}`);
    // source_role realizes: origin → the `bp-pnode--src` accent; provenance → the
    // `bp-pnode__src` text line.
    if (n.source_role === "origin") {
      present(html, "bp-pnode--src", "pipeline origin accent");
    } else if (n.source_role === "provenance") {
      present(html, `>${n.source_text}</div>`, `pipeline provenance ${n.source_text}`);
    }
  }
});

test("web stage RENDER realizes kind · title · detail · source_role", () => {
  const input = loadFixture("stage").input;
  const html = renderHtml(input);
  const exp = loadFixture("stage").expected as StageProjection;
  present(html, `>${exp.kind}</div>`, "stage kind");
  present(html, `>${exp.title}</div>`, "stage title");
  present(html, `>${exp.detail}</div>`, "stage detail");
  if (exp.source_role === "origin") {
    present(html, "bp-pnode--src", "stage origin accent");
  } else if (exp.source_role === "provenance") {
    present(html, `>${exp.source_text}</div>`, "stage provenance line");
  }
});

// ── source coercion regression (au-w5-pipeline-source-parity) ─────────────────
// The web reader used to DROP `source` entirely (no accent, no line, any value).
// These pin the ratified coercion RENDERS a signal; each reds if reverted to the drop.
test("web stage source:true → origin accent renders (was dropped)", () => {
  const html = renderHtml({ type: "stage", title: "Ingest", source: true });
  present(html, "bp-pnode--src", "stage source:true accent");
});

test('web stage source:"text" → provenance line renders the text (was dropped)', () => {
  const html = renderHtml({ type: "stage", title: "Ingest", source: "queue.ex:42" });
  present(html, ">queue.ex:42</div>", "stage source:string provenance");
  assert.ok(!html.includes("bp-pnode--src"), "a string must not flip the origin accent");
});

test("web stage source:false / absent → NO signal", () => {
  for (const block of [
    { type: "stage", title: "Ingest", source: false },
    { type: "stage", title: "Ingest" },
  ]) {
    const html = renderHtml(block);
    assert.ok(!html.includes("bp-pnode--src"), "source:false/absent must not accent");
    assert.ok(!html.includes(">queue.ex</div>"), "no provenance line for false/absent");
  }
});

test("web task-detail RENDER realizes title + timeline + criteria tally", () => {
  const input = loadFixture("task-detail").input;
  const html = renderHtml(input);
  const exp = loadFixture("task-detail").expected as TaskDetailProjection;
  present(html, `>${exp.title}</div>`, "task-detail title");
  // Timeline is now COVERED: every ordered cell's label realizes in the render
  // (a dropped/renamed timeline cell reds here even while the projector matches).
  if (exp.sections.includes("timeline")) {
    assert.ok(exp.timeline.length > 0, "timeline section present but no entries");
    for (const seg of exp.timeline) {
      present(html, `>${seg.label}</span>`, `task-detail timeline label ${seg.label}`);
    }
  }
  if (exp.sections.includes("criteria")) {
    present(
      html,
      `Criteria · ${exp.criteria.met}/${exp.criteria.total}`,
      "task-detail criteria tally",
    );
  }
});

test("web roadmap RENDER realizes scale + every lane (title · role bar)", () => {
  const input = loadFixture("roadmap").input;
  const html = renderHtml(input);
  const exp = loadFixture("roadmap").expected as RoadmapProjection;
  for (const cell of exp.scale) present(html, `>${cell}</span>`, `roadmap scale ${cell}`);
  for (const lane of exp.lanes) {
    present(html, `>${lane.title}</span>`, `roadmap lane ${lane.title}`);
    present(html, `bp-rm__bar--${lane.role}`, `roadmap role bar ${lane.role}`);
  }
});

test("web columns RENDER nests each column's children (count + content)", () => {
  const input = loadFixture("columns").input;
  const html = renderHtml(input);
  const exp = loadFixture("columns").expected as ColumnsProjection;
  // Column count is expressed via the `--bp-cols` custom prop — a flatten/mis-nest reds.
  present(html, `--bp-cols:${exp.columns.length}`, "columns grid count");
  const cols = Array.isArray(input.columns) ? (input.columns as unknown[][]) : [];
  exp.columns.forEach((children, ci) => {
    children.forEach((_type, cj) => {
      const text = leafText(cols[ci]?.[cj]);
      if (text) present(html, text, `columns[${ci}] child ${cj}`);
    });
  });
});

test("web section RENDER realizes the grid + nests authored cells in order", () => {
  const input = loadFixture("section").input;
  const html = renderHtml(input);
  const exp = loadFixture("section").expected as SectionProjection;

  present(html, 'class="bp-section__grid"', "section grid");
  // The `repeat()` grid-template ships in paper-surface.css (not the DOM); the
  // canonical renderer emits only the `--bp-tracks` custom prop the rule reads.
  present(html, `--bp-tracks:${exp.tracks}`, "section track count");

  const authored = Array.isArray(input.blocks)
    ? (input.blocks as Array<{ slots?: { title?: unknown[] } }>)
    : [];
  const renderedCells = html.split('<div class="bp-section__cell"').slice(1);
  assert.equal(renderedCells.length, exp.cells.length, "section cell count");

  exp.cells.forEach((cell, i) => {
    const segment = renderedCells[i] ?? "";
    const title = (authored[i]?.slots?.title ?? []).map(leafText).join("");
    assert.ok(title, `section authored cell ${i} has no title text`);
    present(segment, title, `section cell ${i} authored content`);

    if (cell.span == null) {
      assert.doesNotMatch(segment, /grid-column:span /, `section cell ${i} span`);
    } else {
      present(segment, `grid-column:span ${cell.span}`, `section cell ${i} span`);
    }

    if (cell.order == null) {
      assert.doesNotMatch(segment, /order:-?\d+/, `section cell ${i} order`);
    } else {
      present(segment, `order:${cell.order}`, `section cell ${i} order`);
    }
  });
});

test("web terminal RENDER realizes chrome (title · live · footer) + nests children", () => {
  const input = loadFixture("terminal").input;
  const html = renderHtml(input);
  const exp = loadFixture("terminal").expected as TerminalProjection;
  present(html, `>${exp.title}</span>`, "terminal title");
  present(html, exp.footer, "terminal footer");
  if (exp.live) present(html, ">live</span>", "terminal live badge");
  const kids = Array.isArray(input.children)
    ? (input.children as unknown[])
    : Array.isArray(input.blocks)
      ? (input.blocks as unknown[])
      : [];
  exp.children.forEach((_type, ci) => {
    const text = leafText(kids[ci]);
    if (text) present(html, text, `terminal child ${ci}`);
  });
});

test("web task-board RENDER realizes every projection column (role order · label · count · ordered card titles · manifest glyph)", () => {
  const html = renderHtml(fixture.input as Record<string, unknown>);
  // Cross-fixture glyph-char source: the status-legend golden carries the
  // manifest glyph per role. The canonical render derives BOTH surfaces from
  // one ladder — this asserts that derivation instead of a web hand copy
  // (the deleted `task-board-columns.ts` model was that hand copy).
  const legend = loadFixture("status-legend").expected as LegendProjection;
  const legendByRole = new Map(legend.rows.map((r) => [r.role, r]));

  // One rendered column per projection column, in projection order. The golden
  // input populates EXACTLY the projected columns (empty columns collapse), so
  // an extra, dropped, or reordered rendered column reds here.
  const segments = html.split('<div class="bp-board__col ').slice(1);
  assert.equal(
    segments.length,
    fixture.expected.columns.length,
    "rendered board column count",
  );

  fixture.expected.columns.forEach((col, i) => {
    const seg = segments[i] ?? "";
    assert.ok(
      seg.startsWith(`bp-board__col--${col.role}`),
      `column ${i} must be ${col.role} (white-ladder order parity)`,
    );
    present(
      seg,
      `<span class="bp-board__label">${col.label}</span>`,
      `board label ${col.role}`,
    );
    present(
      seg,
      `<span class="bp-board__count">${col.count}</span>`,
      `board count ${col.role}`,
    );

    // Ordered card titles — presence AND order within the column segment.
    let prev = -1;
    for (const card of col.cards) {
      const marker = `<span class="bp-bcard__t">${card.title}</span>`;
      const idx = seg.indexOf(marker);
      assert.ok(
        idx >= 0,
        `board card ${JSON.stringify(card.title)} missing from ${col.role}`,
      );
      assert.ok(
        idx > prev,
        `board card ${JSON.stringify(card.title)} out of order in ${col.role}`,
      );
      prev = idx;
    }

    // The glyph-role realizes at the MANIFEST glyph char. Spinner roles emit
    // the empty CSS-animated span (aria-labelled), never a literal char.
    const lrow = legendByRole.get(col.glyph_role);
    assert.ok(lrow, `legend fixture has no row for glyph role ${col.glyph_role}`);
    if (lrow!.spinner) {
      present(
        seg,
        `<span class="bp-g bp-g--${col.glyph_role}" aria-label=`,
        `board spinner glyph ${col.glyph_role}`,
      );
    } else {
      present(
        seg,
        `<span class="bp-g bp-g--${col.glyph_role}">${lrow!.glyph}</span>`,
        `board glyph ${col.glyph_role}`,
      );
    }
  });
});
