/**
 * Web golden-parity leg — the renderer answers to the cross-surface golden
 * fixture cell-by-cell.
 *
 * `fixtures/sheet-golden-parity.json` is generated by
 * `mix barkpark.sheets.gen_golden_parity` from the REAL server snapshot
 * (`Core.snapshot_for/2`) and mirrored to api tests + internal/pdrender. Until
 * now NOTHING in web/ consumed it — which is exactly how the frozen-head
 * fmt-loss class shipped green. This suite makes the TS render pipeline
 * (`densifyTab` → `toRenderModel` → `formatDisplay`) reproduce the fixture's
 * `expected` map ref-by-ref, and locks head/spans/error/right-align geometry.
 *
 * Legs:
 *   A — independent-twin parity: formatDisplay(v, fmt) from the render model
 *       equals fixture.expected[ref] for every ref (head refs via model.head).
 *   B — snapshot geometry: fixture.snapshot.rows carries the expected value at
 *       every body ref; model.merges ⇄ fixture.spans / fixture.snapshot.merges.
 *   C — head band equality against fixture.head (fixture truth).
 *   D — right-align lock: every fixture.right_aligned display string reads
 *       numeric; text + header controls read false.
 *   E — isEngineError true at every fixture.error_refs position.
 *   F — CF-composed snapshot styles: the server-composed snapshot.styles map
 *       (manual `"s"` merged per-key with the matching conditional-format rule)
 *       carries the pure-CF, CF-over-manual, and head-dropped entries the
 *       charter's CF-D3/CF-AM2 decisions prescribe. Closes CF-2 caveat 3 (web).
 *
 * Run: `pnpm test` (or `node --test __tests__/sheet-golden-parity.test.ts`).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  colToLetters,
  densifyTab,
  formatDisplay,
  isEngineError,
  looksNumericDisplay,
  parseA1,
  toRenderModel,
  type CellStyle,
  type SheetTab,
} from "../lib/sheets.ts";

interface GoldenFixture {
  content: { tabs: SheetTab[] };
  snapshot: {
    rows: string[][];
    head: string[];
    merges: number[][];
    styles: Record<string, CellStyle>;
  };
  expected: Record<string, string>;
  head: string[];
  spans: Record<string, number[]>;
  right_aligned: string[];
  error_refs: string[];
  fmt_vocabulary: string[];
}

const fixture: GoldenFixture = JSON.parse(
  readFileSync(
    new URL("./fixtures/sheet-golden-parity.json", import.meta.url),
    "utf8",
  ),
);

/* ── floors — fail LOUD on fixture key drift, before any leg can go vacuous ── */

function floor(cond: boolean, msg: string): void {
  if (!cond) throw new Error(`golden-fixture floor violated: ${msg}`);
}

floor(
  Object.keys(fixture.expected).length >= 20,
  `expected map has ${Object.keys(fixture.expected).length} refs, need >= 20`,
);
floor(fixture.head.length >= 3, `head has ${fixture.head.length} cols, need >= 3`);
floor(
  fixture.error_refs.length >= 3,
  `error_refs has ${fixture.error_refs.length} refs, need >= 3`,
);
floor(Object.keys(fixture.spans).length > 0, "spans must be non-empty");
floor(
  fixture.fmt_vocabulary.includes("checkbox") &&
    fixture.fmt_vocabulary.includes("datetime"),
  "fmt_vocabulary lost checkbox/datetime — regenerate the fixture",
);
floor(
  Object.keys(fixture.snapshot.styles ?? {}).length >= 6,
  `snapshot.styles has ${Object.keys(fixture.snapshot.styles ?? {}).length} ` +
    "entries, need >= 6 (CF composition dropped from the fixture?)",
);

/* ── the render model under test (raw content → TS pipeline, no server) ────── */

const model = toRenderModel(densifyTab(fixture.content.tabs[0]));

// The fixture tab freezes row 1, so the model MUST split off a head band; every
// body-ref index below assumes dataStart = 1. Fail loud if that ever drifts.
if (!model.head) {
  throw new Error(
    "golden-fixture floor violated: model has no head band (frozen_rows drifted?)",
  );
}
const head = model.head;

/** 0-based body-grid position for a full-grid A1 ref (row 1 is the head). */
function bodyPos(ref: string): { r: number; c: number } {
  const pos = parseA1(ref);
  assert.ok(pos, `fixture ref ${ref} must parse as A1`);
  assert.ok(pos.row >= 1, `${ref} is a head ref, not a body ref`);
  return { r: pos.row - 1, c: pos.col };
}

/* ── leg A: independent-twin parity ─────────────────────────────────────────── */

test("leg A: formatDisplay over the render model reproduces every expected ref", () => {
  for (const [ref, want] of Object.entries(fixture.expected)) {
    const pos = parseA1(ref);
    assert.ok(pos, `fixture ref ${ref} must parse as A1`);
    if (pos.row === 0) {
      // Head refs: toRenderModel already ran formatDisplay with the row-0 fmt.
      assert.equal(head[pos.col], want, `head ref ${ref}`);
    } else {
      const r = pos.row - 1;
      const v = model.rows[r]?.[pos.col];
      const fmt = model.fmts[`${r},${pos.col}`];
      assert.equal(formatDisplay(v, fmt), want, `body ref ${ref} (fmt=${fmt})`);
    }
  }
});

/* ── leg B: snapshot geometry ───────────────────────────────────────────────── */

test("leg B1: the server snapshot carries the expected value at every body ref", () => {
  let bodyRefs = 0;
  for (const [ref, want] of Object.entries(fixture.expected)) {
    const pos = parseA1(ref);
    assert.ok(pos, `fixture ref ${ref} must parse as A1`);
    if (pos.row === 0) continue; // head refs are leg C's job
    bodyRefs++;
    assert.equal(
      fixture.snapshot.rows[pos.row - 1]?.[pos.col],
      want,
      `snapshot ref ${ref}`,
    );
  }
  assert.ok(bodyRefs >= 15, `only ${bodyRefs} body refs checked — fixture drifted`);
});

test("leg B2: model merges equal fixture.spans (anchor → [colspan, rowspan])", () => {
  const got: Record<string, number[]> = {};
  for (const m of model.merges) {
    // Body row → 1-based full-grid row: +1 for the head band, +1 for 1-basing.
    const anchor = `${colToLetters(m.c)}${m.r + 2}`;
    got[anchor] = [m.cs, m.rs];
  }
  assert.deepEqual(got, fixture.spans);
});

test("leg B3: model merges equal the snapshot's body-based [r,c,rs,cs] tuples", () => {
  const byPos = (a: number[], b: number[]) => a[0] - b[0] || a[1] - b[1];
  assert.deepEqual(
    model.merges.map((m) => [m.r, m.c, m.rs, m.cs]).sort(byPos),
    [...fixture.snapshot.merges].sort(byPos),
  );
});

/* ── leg C: head band ───────────────────────────────────────────────────────── */

test("leg C: the model head band equals fixture.head exactly", () => {
  assert.deepEqual(head, fixture.head);
  // And the server snapshot's own head agrees with the top-level key.
  assert.deepEqual(fixture.snapshot.head, fixture.head);
});

/* ── leg D: right-align lock ────────────────────────────────────────────────── */

test("leg D: every right_aligned ref's display string reads numeric", () => {
  for (const ref of fixture.right_aligned) {
    const shown = fixture.expected[ref];
    assert.equal(
      typeof shown,
      "string",
      `right_aligned ref ${ref} missing from expected`,
    );
    assert.equal(looksNumericDisplay(shown), true, `${ref} → ${JSON.stringify(shown)}`);
  }
});

test("leg D control: text and header displays do NOT read numeric", () => {
  const controls = ["A2", "A1"]; // "Revenue" (text body cell), "Metric" (header)
  for (const ref of controls) {
    const shown = fixture.expected[ref];
    assert.equal(typeof shown, "string", `control ref ${ref} missing from expected`);
    assert.ok(
      !fixture.right_aligned.includes(ref),
      `control ${ref} unexpectedly listed right_aligned`,
    );
    assert.equal(looksNumericDisplay(shown), false, `${ref} → ${JSON.stringify(shown)}`);
  }
});

/* ── leg E: engine-error refs ───────────────────────────────────────────────── */

test("leg E: isEngineError is true at every fixture error ref position", () => {
  for (const ref of fixture.error_refs) {
    const { r, c } = bodyPos(ref);
    const v = model.rows[r]?.[c];
    assert.equal(isEngineError(v), true, `${ref} → ${JSON.stringify(v)}`);
    // Value parity: the raw error code is exactly what every surface shows.
    assert.equal(v, fixture.expected[ref], `${ref} expected-map parity`);
  }
});

test("leg E control: an ordinary numeric cell is not an engine error", () => {
  const { r, c } = bodyPos("C10"); // v: 5
  assert.equal(isEngineError(model.rows[r]?.[c]), false);
});

/* ── leg F: CF-composed snapshot styles (CF-2 caveat 3, web half) ─────────────
 *
 * `snapshot.styles` is server-composed (Core.build_snapshot → CondFormat
 * style_for/compose): each cell's manual `"s"` styling merged PER-KEY with the
 * one matching conditional-format rule — CF wins `bg`/`b`/`i`, manual wins `al`
 * (charter CF-D3). The TS render model (densifyTab → toRenderModel) collects
 * MANUAL styles only; it never evaluates `cond_formats`. So the CF-composed
 * VALUES are asserted against the snapshot map directly here — the model-level
 * CF render assertion is sp-cf-verify's job. Keys are "bodyRow,col" (the frozen
 * head band is dropped — CF-AM2); the block below locks that convention. */

const styles = fixture.snapshot.styles;
{
  // Key-convention lock: the pure-CF entry MUST sit at B2's body position, or
  // every ref-derived assertion below would silently target the wrong cell.
  const b2 = bodyPos("B2");
  floor(
    `${b2.r},${b2.c}` === "0,1",
    `styles key convention drifted: B2 → "${b2.r},${b2.c}", expected "0,1"`,
  );
}

test("leg F1: pure CF match — B2 earns a CF-only bg, absent from the manual model", () => {
  // B2 = 1200 > 1000 (rule cf-gt), no manual "s" → the entry is purely CF-set.
  // This deepEqual ALSO pins first-match-wins (CF-D4): B2 matches BOTH cf-gt
  // (#ff0000, first) and cf-overlap (#00ff00, later) — only cf-gt may land.
  assert.deepEqual(styles["0,1"], { bg: "#ff0000" });
  // The manual-only TS model has NO entry at B2 — CF is a server-side overlay.
  assert.equal(model.styles["0,1"], undefined);
});

test("leg F2: CF-over-manual compose — manual al survives, CF wins bg (CF-D3)", () => {
  // A4 manual "s" = {al:right, b, bg:#e0f0ff, i}; cf-compose (contains "ote")
  // overrides only bg → the composed entry keeps al/b/i and takes the CF bg.
  assert.deepEqual(styles["2,0"], {
    al: "right",
    b: true,
    bg: "#123456",
    i: true,
  });
  assert.equal(styles["2,0"].al, "right", "manual al must survive compose");
  assert.equal(styles["2,0"].bg, "#123456", "CF bg must win over manual");
  // The pre-compose manual bg is what the manual-only TS model still carries —
  // proof the snapshot's #123456 is a genuine server-side CF override.
  assert.equal(model.styles["2,0"]?.bg, "#e0f0ff");
});

test("leg F3: head-drop — no head-row CF contribution reaches the snapshot (CF-AM2)", () => {
  // Rule cf-head (bg #abcdef, contains "Q") WOULD paint B1/C1 in the frozen
  // head, but the head band is dropped from the body-indexed styles map, so its
  // colour must appear nowhere and every style key must land in the body grid.
  const bodyRows = fixture.snapshot.rows.length;
  const bodyCols = fixture.snapshot.head.length;
  for (const [key, s] of Object.entries(styles)) {
    assert.notEqual(s.bg, "#abcdef", `head CF colour leaked into ${key}`);
    const [r, c] = key.split(",").map(Number);
    assert.ok(r >= 0 && r < bodyRows, `styles key ${key} is not a body row`);
    assert.ok(c >= 0 && c < bodyCols, `styles key ${key} is not a body col`);
  }
});

test("leg F4: no ghost styles — an unstyled, CF-untouched ref stays absent", () => {
  // D4 ("has note"): no manual "s", and col 3 is outside every cond_format
  // range — the composed map must carry no phantom entry for it.
  const { r, c } = bodyPos("D4");
  assert.equal(styles[`${r},${c}`], undefined);
});
