/**
 * Display-parity tests for `formatDisplay` / `numberToDisplay` / `displayValue`
 * — the TS twins of `Fmt.display/2` and `Core.number_to_display/1`.
 *
 * The core of the suite is a SHARED fixture table
 * (`fixtures/fmt-display-parity.json`) generated by running the Elixir
 * functions; the ExUnit block in `api/test/barkpark/plugins/sheets/fmt_test.exs`
 * reads the same file, so any Elixir↔TS drift reds a gate on both runtimes.
 *
 * Run: `pnpm test` (or `cd web && node --test __tests__/sheets-display.test.ts`).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  displayValue,
  formatDisplay,
  numberToDisplay,
} from "../lib/sheets.ts";

interface ParityRow {
  v: unknown;
  fmt: string | null;
  out: string;
}

const fixture: ParityRow[] = JSON.parse(
  readFileSync(
    new URL("./fixtures/fmt-display-parity.json", import.meta.url),
    "utf8",
  ),
);

test("shared fixture table: formatDisplay matches Elixir Fmt.display for every row", () => {
  assert.ok(fixture.length > 0, "fixture must not be empty");
  for (const { v, fmt, out } of fixture) {
    const got = formatDisplay(v, fmt ?? undefined);
    assert.equal(
      got,
      out,
      `formatDisplay(${JSON.stringify(v)}, ${JSON.stringify(fmt)}) → ${JSON.stringify(got)}, expected ${JSON.stringify(out)}`,
    );
  }
});

test("shared fixture: fmt-less numeric rows also match numberToDisplay directly", () => {
  for (const { v, fmt, out } of fixture) {
    if (fmt == null && typeof v === "number") {
      assert.equal(numberToDisplay(v), out);
    }
  }
});

test("numberToDisplay: Excel-General shapes (integral, decimal, exponent bands)", () => {
  assert.equal(numberToDisplay(1234567), "1234567");
  assert.equal(numberToDisplay(0.1), "0.1");
  assert.equal(numberToDisplay(1234567.5), "1234567.5");
  assert.equal(numberToDisplay(0.000001), "0.000001");
  assert.equal(numberToDisplay(1e15), "1.0e15");
  assert.equal(numberToDisplay(1e-7), "1.0e-7");
  assert.equal(numberToDisplay(-1e15), "-1.0e15");
});

test("displayValue: null → '', booleans → TRUE/FALSE, objects → JSON", () => {
  assert.equal(displayValue(null), "");
  assert.equal(displayValue(undefined), "");
  assert.equal(displayValue(true), "TRUE");
  assert.equal(displayValue(false), "FALSE");
  assert.equal(displayValue("plain"), "plain");
  assert.equal(displayValue(42), "42");
  assert.equal(displayValue({ a: 1 }), '{"a":1}');
  assert.equal(displayValue([1, 2]), "[1,2]");
});

test("formatDisplay: general path and mismatches fall back to displayValue", () => {
  // number + unknown fmt → numberToDisplay
  assert.equal(formatDisplay(1234.5, "bogus"), "1234.5");
  // string + numeric fmt → the string verbatim
  assert.equal(formatDisplay("hello", "percent"), "hello");
  // boolean always wins
  assert.equal(formatDisplay(true, "currency"), "TRUE");
  // null → ''
  assert.equal(formatDisplay(null, "percent"), "");
});
