defmodule BarkparkWeb.Contract.PDSRequestEchoDifferentialTest do
  @moduledoc """
  PDS wave 40 — the FOUR live request-echo receipts wave 39's six left behind.

  THE LAW, unchanged since wave 22 and quoted from #9114's own commit message:
  A RECEIPT LIES WHEN THE VALUE IT EMITS DOES NOT DESCEND FROM THE WRITE RETURN.
  Each site below was already handed a `{:ok, row}` and threw it away, answering
  instead with a path param, an assign, or a literal — a sentence that stays
  identical whatever the store did.

  Sites covered (all repaired by RENDERING the row the callee already returns —
  zero callee widening was needed here either):

    * v1/media_controller.ex:401             DELETE /v1/media/:dataset/:id
    * v1/media_collections_controller.ex:94  DELETE /v1/media/:ds/collections/:id/share
    * app_token_controller.ex:141            DELETE /v1/auth/app-tokens/current
    * app_token_controller.ex:164            DELETE /v1/auth/app-tokens  {"token": raw}
    * token_controller.ex:45                 POST   /w/:ws/p/:proj/v1/tokens

  THE DIFFERENTIAL: every test asserts a field the REQUEST CANNOT PRODUCE — the
  store's generated filename, the persisted `shareLink.enabled` flag, the
  `revoked_at` stamp, the insert's autogenerated `binary_id` and `inserted_at`.
  Revert a receipt to its old form and the key is simply absent (or the literal
  cannot equal the store's value), so the assertion reds. A test that passes over
  BOTH shapes proves nothing.

  ## The trap this file exists to catch — v1 media DELETE

  `v1/media_controller.ex` binds `file` at :403 from a PRE-WRITE
  `Media.get_file/2` read. Emitting `file.filename` would be store-SHAPED and
  would pass every assertion below, while still not descending from the write.
  The delete's own `{:ok, deleted}` is bound instead; the pre-write read is left
  where it is (it feeds `ensure_dataset/2`, not the receipt). A structural test
  cannot distinguish the two bindings — that judgment is recorded on the task and
  in the RECEIPT LAW comment at the site, and the post-condition assertion below
  (the row is gone) at least pins that the emitted values name a row that the
  write actually removed.

  Stored state is read DIRECTLY through `Repo` (the wave-39 precedent in
  `pds_delete_receipt_differential_test.exs`) — reading it back through a second
  HTTP endpoint would only prove receipt-vs-receipt.
  """
  use BarkparkWeb.ConnCase, async: false

  import Barkpark.RateLimiterSandbox

  # `:barkpark_rate_limiter` is a :named_table — WHOLE-NODE state no sandbox owns
  # and nothing used to reset, so a bucket one test spent stayed spent for the
  # rest of the run. Start from an unspent table.
  setup :reset_rate_limiter!

  alias Barkpark.Auth
  alias Barkpark.Auth.ApiToken
  alias Barkpark.Content
  alias Barkpark.Content.Document
  alias Barkpark.Media
  alias Barkpark.Media.Storage.MediaFile
  alias Barkpark.Repo
  alias Barkpark.Tenancy
  alias Barkpark.Tenancy.Auth, as: TenancyAuth

  @dataset "production"

  # 1x1 transparent PNG, inline — no fixture file needed (mirrors media_test.exs).
  @png_b64 "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgAAIAAAUAAeImBZsAAAAASUVORK5CYII="

  setup do
    if :ets.whereis(:barkpark_rate_limiter) != :undefined do
      :ets.delete_all_objects(:barkpark_rate_limiter)
    end

    admin = "pds-w40-admin-#{System.unique_integer([:positive])}"
    {:ok, _} = Auth.create_token(admin, "pds-w40", @dataset, ["read", "write", "admin"])

    %{admin: admin}
  end

  defp as(conn, raw) do
    conn
    |> put_req_header("authorization", "Bearer #{raw}")
    |> put_req_header("content-type", "application/json")
  end

  defp uniq(prefix), do: "#{prefix}#{System.unique_integer([:positive])}"

  # ── v1/media_controller.ex:401 ────────────────────────────────────────────

  describe "DELETE /v1/media/:dataset/:id" do
    test "the receipt carries the DELETED ROW's stored filename, not the :id path param",
         %{conn: conn, admin: admin} do
      created =
        conn
        |> as(admin)
        |> delete_content_type()
        |> post("/v1/media/#{@dataset}/upload", %{"file" => png_upload()})
        |> json_response(201)

      id = created["result"]["id"]
      stored = Repo.get(MediaFile, id)
      assert %MediaFile{} = stored

      # The proof field: the STORED filename is generated on upload and the
      # DELETE request carries nothing but `:dataset` and `:id`.
      assert is_binary(stored.filename)
      refute stored.filename == id

      body =
        conn |> as(admin) |> delete("/v1/media/#{@dataset}/#{id}") |> json_response(200)

      assert body["result"]["deleted"] == id

      assert body["result"]["filename"] == stored.filename,
             "receipt did not descend from the write return — it echoed the :id path param"

      assert body["result"]["dataset"] == stored.dataset

      assert Repo.get(MediaFile, id) == nil,
             "receipt reported a delete but the media row survived"

      rm_uploaded(created["result"])
    end
  end

  # ── v1/media_collections_controller.ex:94 ─────────────────────────────────

  describe "DELETE /v1/media/:dataset/collections/:id/share" do
    test "the receipt's revoked state descends from the UPSERTED document, not the :id path param",
         %{conn: conn, admin: admin} do
      collection = create_collection!()

      share =
        conn
        |> as(admin)
        |> post("/v1/media/#{@dataset}/collections/#{collection.doc_id}/share")
        |> json_response(200)

      assert is_binary(share["result"]["token"])

      before_row = Repo.get_by(Document, doc_id: collection.doc_id, dataset: @dataset)
      assert get_in(before_row.content, ["shareLink", "enabled"]) == true

      body =
        conn
        |> as(admin)
        |> delete("/v1/media/#{@dataset}/collections/#{collection.doc_id}/share")
        |> json_response(200)

      after_row = Repo.get_by(Document, doc_id: collection.doc_id, dataset: @dataset)

      assert get_in(after_row.content, ["shareLink", "enabled"]) == false,
             "receipt said revoked but the stored shareLink was never disabled"

      assert body["result"]["revoked"] == collection.doc_id

      # The proof field: `shareEnabled` is read off the document
      # `Share.revoke/3` -> `Content.upsert_document/4` RETURNED. The old body
      # (`%{revoked: id}`) had no key that could disagree with the store, so the
      # value flips with the store and nothing else.
      assert body["result"]["shareEnabled"] == false,
             "receipt did not descend from the write return — it echoed the :id path param"

      assert body["result"]["shareEnabled"] ==
               get_in(after_row.content, ["shareLink", "enabled"])

      cleanup_collection(collection)
    end
  end

  # ── app_token_controller.ex:141 (self-revoke) ─────────────────────────────

  describe "DELETE /v1/auth/app-tokens/current" do
    test "the receipt's `revoked` descends from the stamped row, not from a literal `true`",
         %{admin: admin} do
      ws = create_ws!()
      raw = mint_app_token(admin, ws)
      before_row = Auth.get_api_token_by_raw(raw)
      assert is_nil(before_row.revoked_at)

      body =
        build_conn() |> as(raw) |> delete("/v1/auth/app-tokens/current") |> json_response(200)

      after_row = Repo.get(ApiToken, before_row.id)
      refute is_nil(after_row.revoked_at), "receipt said revoked but revoked_at was never stamped"

      assert body["revoked"] == true

      # The proof fields: the row's id and its freshly stamped `revoked_at`.
      # The self-revoke request carries NO body at all — only the bearer.
      assert body["id"] == after_row.id,
             "receipt did not descend from the write return — `revoked: true` was a literal"

      assert body["revoked_at"] == DateTime.to_iso8601(after_row.revoked_at),
             "receipt did not descend from the write return — `revoked: true` was a literal"
    end
  end

  # ── app_token_controller.ex:164 (admin revoke-by-raw) ─────────────────────

  describe "DELETE /v1/auth/app-tokens with {token}" do
    test "the receipt's `revoked` descends from the stamped row, not from a literal `true`",
         %{admin: admin} do
      ws = create_ws!()
      raw = mint_app_token(admin, ws)
      before_row = Auth.get_api_token_by_raw(raw)
      assert is_nil(before_row.revoked_at)

      body =
        build_conn()
        |> as(admin)
        |> delete("/v1/auth/app-tokens", Jason.encode!(%{token: raw}))
        |> json_response(200)

      after_row = Repo.get(ApiToken, before_row.id)
      refute is_nil(after_row.revoked_at), "receipt said revoked but revoked_at was never stamped"

      assert body["revoked"] == true

      # The proof fields: the request named the token by its RAW secret and
      # never carried the row id or any timestamp.
      assert body["id"] == after_row.id,
             "receipt did not descend from the write return — `revoked: true` was a literal"

      assert body["revoked_at"] == DateTime.to_iso8601(after_row.revoked_at),
             "receipt did not descend from the write return — `revoked: true` was a literal"
    end
  end

  # ── token_controller.ex:45 (the 201 credential receipt) ───────────────────

  describe "POST /w/:workspace_slug/p/:project_slug/v1/tokens" do
    test "the 201 carries the INSERTED row's id and inserted_at, and still returns the raw secret",
         %{conn: conn} do
      slug = uniq("pdsw40ws")
      {:ok, ws} = Tenancy.create_workspace(%{slug: slug, name: "PDS W40"})
      {:ok, _proj} = Tenancy.create_project(ws, %{slug: "default", name: "Default"})

      minter = uniq("pds-w40-minter-")

      {:ok, minter_token} =
        Auth.create_token(minter, "minter", @dataset, ["read", "write", "admin"])

      {:ok, _} = TenancyAuth.create_membership(ws.id, minter_token.id, "admin")

      body =
        conn
        |> as(minter)
        |> post(
          "/w/#{slug}/p/default/v1/tokens",
          Jason.encode!(%{"label" => "pds-w40-site", "permissions" => ["public-read"]})
        )
        |> json_response(201)

      # The raw secret is still returned — this is the ONLY moment it is visible.
      assert is_binary(body["token"]) and byte_size(body["token"]) > 0

      stored = Repo.get_by(ApiToken, token_hash: ApiToken.hash_token(body["token"]))
      assert %ApiToken{} = stored

      # The proof fields: BOTH are autogenerated by the insert — the request
      # carried only label/permissions/dataset, and `raw` was generated in the
      # controller BEFORE the insert.
      assert body["id"] == stored.id,
             "201 did not descend from the write return — every field was request-derived"

      assert body["inserted_at"] == DateTime.to_iso8601(stored.inserted_at),
             "201 did not descend from the write return — every field was request-derived"

      assert body["label"] == "pds-w40-site"
      assert body["workspace"] == slug
    end
  end

  # ── helpers ───────────────────────────────────────────────────────────────

  # A multipart upload must NOT carry the json content-type `as/2` sets.
  defp delete_content_type(conn),
    do: %{conn | req_headers: Enum.reject(conn.req_headers, &(elem(&1, 0) == "content-type"))}

  defp png_upload do
    tmp = Path.join(System.tmp_dir!(), "pds-w40-#{System.unique_integer([:positive])}.png")
    File.write!(tmp, Base.decode64!(@png_b64))
    %Plug.Upload{path: tmp, filename: "pixel.png", content_type: "image/png"}
  end

  # The sandbox rolls back the row; the BYTES on disk outlive it.
  defp rm_uploaded(%{"url" => "/media/files/" <> relative}),
    do: File.rm(Path.join(Media.upload_dir(), relative))

  defp rm_uploaded(_), do: :ok

  defp create_collection! do
    id = uniq("pdsw40col-")

    {:ok, doc} =
      Content.upsert_document(
        "mediaCollection",
        %{
          "doc_id" => id,
          "title" => "PDS W40",
          "content" => %{"kind" => "folder", "slug" => id}
        },
        @dataset,
        source: :api
      )

    doc
  end

  defp cleanup_collection(%Document{doc_id: id}),
    do: Content.delete_document(id, "mediaCollection", @dataset)

  defp create_ws! do
    {:ok, ws} = Tenancy.create_workspace(%{slug: uniq("pdsw40appws"), name: "PDS W40 App"})
    ws
  end

  # Mint through the REAL endpoint — the revoke path must kill exactly what the
  # exchange mints, so no fixture shortcut.
  defp mint_app_token(admin, ws) do
    build_conn()
    |> as(admin)
    |> post(
      "/v1/auth/app-tokens",
      Jason.encode!(%{email: uniq("pds-w40-") <> "@example.com", workspace: ws.slug})
    )
    |> json_response(201)
    |> Map.fetch!("token")
  end
end
