defmodule BarkparkWeb.Admin.PluginsLive do
  @moduledoc """
  Task barkpark-otv — admin LiveView at `/studio/:dataset/_plugins`.

  Closes the "why doesn't my plugin work?" debug loop: lists every
  registered plugin, surfaces which `Barkpark.Plugin` callbacks the
  module overrides vs. inherits the no-op default, shows the last
  bootstrap and last codelist-seed result + timestamp from
  `Barkpark.Plugins.RunStatus`, and exposes per-plugin and all-plugin
  Reload buttons that re-run schema upserts + codelist seeders without
  an SSH or `systemctl restart`.

  ## Auth

  Mounted inside the `live_session :admin_studio_dataset` block in
  `BarkparkWeb.Router`. The session uses the `BarkparkWeb.LiveAuth.:admin`
  on_mount hook — same gate as `/studio/settings`. Tokens without the
  `"admin"` permission redirect to `/studio` with a flash.

  ## Reload semantics

  Both Reload buttons are idempotent — `register_all_schemas/0` /
  `install_by_name/1` route through `Content.upsert_schema/2`, which
  reads first and updates existing rows in place; codelist seeders are
  themselves idempotent UPSERTs. Reload does NOT restart Phoenix — the
  whole flow is in-process.
  """

  use BarkparkWeb, :live_view

  require Logger

  alias Barkpark.Plugins.Bootstrap
  alias Barkpark.Plugins.Registry
  alias Barkpark.Plugins.RunStatus

  # All `Barkpark.Plugin` callbacks excluding `manifest/0`, which is
  # auto-generated by `use Barkpark.Plugin` and always implemented.
  # Order matches the mockup in the task brief.
  @callbacks [
    {:register_schemas, 1},
    {:action_handlers, 0},
    {:external_sync_entries, 0},
    {:codelist_seeders, 0},
    {:register_routes, 1},
    {:register_workers, 1},
    {:validate_settings, 1},
    {:checkers, 0}
  ]

  @impl true
  def mount(%{"dataset" => dataset}, _session, socket) do
    {:ok,
     socket
     |> assign(
       page_title: "Plugins",
       dataset: dataset,
       plugins: load_plugin_rows()
     )}
  end

  # ── events ──────────────────────────────────────────────────────────

  @impl true
  def handle_event("refresh", _params, socket) do
    {:noreply,
     socket
     |> assign(plugins: load_plugin_rows())
     |> put_flash(:info, "Refreshed.")}
  end

  def handle_event("reload-plugin", %{"name" => name}, socket) do
    schemas_result = Bootstrap.install_by_name(name)
    seed_result = Registry.run_codelist_seeders_by_name(name)

    flash =
      case {schemas_result, seed_result} do
        {{:ok, n}, :ok} ->
          {:info, "Reloaded #{name}: #{n} schema(s), seeds re-run."}

        {{:ok, n}, {:error, _}} ->
          {:info, "Reloaded #{name}: #{n} schema(s); some seeds errored — see card."}

        {{:error, :unknown_plugin}, _} ->
          {:error, "Plugin #{name} is not registered."}

        {{:error, reason}, _} ->
          {:error, "Reload failed for #{name}: #{inspect(reason)}"}
      end

    {kind, msg} = flash

    {:noreply,
     socket
     |> assign(plugins: load_plugin_rows())
     |> put_flash(kind, msg)}
  end

  def handle_event("reload-all", _params, socket) do
    bootstrap_result = Bootstrap.register_all_schemas()
    :ok = Registry.run_all_codelist_seeders()

    {kind, msg} =
      case bootstrap_result do
        {:ok, n} -> {:info, "Reloaded all plugins: #{n} schema(s), seeds re-run."}
        {:error, errors} -> {:error, "Reload-all completed with errors: #{inspect(errors)}"}
      end

    {:noreply,
     socket
     |> assign(plugins: load_plugin_rows())
     |> put_flash(kind, msg)}
  end

  # Fall-through: a stale/unknown phx event must not FunctionClauseError-crash
  # the session. Keep LAST among handle_event/3 clauses.
  def handle_event(event, _params, socket) do
    Logger.warning("admin/plugins: unhandled event #{inspect(event)}")
    {:noreply, socket}
  end

  # Fall-through: an unexpected message (e.g. a late PubSub delivery) must not
  # FunctionClauseError-crash the LiveView. Keep LAST among handle_info/2.
  @impl true
  def handle_info(msg, socket) do
    Logger.debug("admin/plugins: unhandled info #{inspect(msg)}")
    {:noreply, socket}
  end

  # ── render ──────────────────────────────────────────────────────────

  @impl true
  def render(assigns) do
    ~H"""
    <div class="bp-plugins-admin" data-test-id="plugins-admin">
      <div class="bp-plugins-header">
        <h1 class="h1">Plugins</h1>
        <div class="bp-plugins-actions">
          <button type="button" class="btn btn-sm" phx-click="refresh" data-test-action="refresh">
            Refresh
          </button>
          <button
            type="button"
            class="btn btn-sm btn-primary"
            phx-click="reload-all"
            data-test-action="reload-all"
          >
            Reload all plugins
          </button>
        </div>
      </div>

      <p class="bp-plugins-meta text-muted">
        Registered plugins for dataset <strong>{@dataset}</strong>.
        Reload re-runs <code>register_schemas/1</code> + codelist seeders in-process —
        no Phoenix restart required.
      </p>

      <%= if @plugins == [] do %>
        <p class="bp-plugins-empty" data-test-id="plugins-empty">
          No plugins registered.
        </p>
      <% else %>
        <div class="bp-plugin-cards" data-test-id="plugin-cards">
          <%= for row <- @plugins do %>
            <section
              class="bp-plugin-card"
              data-test-plugin={row.name}
            >
              <header class="bp-plugin-card-header">
                <div class="bp-plugin-card-title">
                  <strong>{row.name}</strong>
                  <span class="bp-plugin-card-version">{row.version}</span>
                </div>
                <div class="bp-plugin-card-header-actions">
                  <%= if row.has_settings do %>
                    <.link
                      navigate={~p"/studio/#{@dataset}/_plugins/#{row.name}/settings"}
                      class="btn btn-sm"
                      data-test-action="open-settings"
                    >
                      Settings
                    </.link>
                  <% end %>
                  <button
                    type="button"
                    class="btn btn-sm"
                    phx-click="reload-plugin"
                    phx-value-name={row.name}
                    data-test-action="reload-plugin"
                  >
                    Reload this plugin
                  </button>
                </div>
              </header>

              <dl class="bp-plugin-rows">
                <div class="bp-plugin-row">
                  <dt>Module</dt>
                  <dd><code>{inspect(row.module)}</code></dd>
                </div>
                <div class="bp-plugin-row">
                  <dt>Manifest</dt>
                  <dd>
                    <%= if row.manifest_description do %>
                      <span class="bp-plugin-desc">{row.manifest_description}</span>
                    <% else %>
                      <span class="text-dim">—</span>
                    <% end %>
                  </dd>
                </div>
              </dl>

              <div class="bp-plugin-callbacks">
                <h3 class="h3">Callbacks implemented</h3>
                <ul class="bp-callback-list" data-test-id="callback-list">
                  <%= for cb <- row.callbacks do %>
                    <li
                      class={"bp-callback-item " <> callback_class(cb.status)}
                      data-test-callback={cb.name}
                      data-test-callback-status={Atom.to_string(cb.status)}
                    >
                      <span class="bp-callback-name">
                        <code>{cb.name}/{cb.arity}</code>
                      </span>
                      <span class="bp-callback-mark">{cb.mark}</span>
                      <span class="bp-callback-detail">{cb.detail}</span>
                    </li>
                  <% end %>
                </ul>
              </div>

              <div class="bp-plugin-runs">
                <div class="bp-plugin-run-row" data-test-id="last-bootstrap">
                  <span class="bp-plugin-run-label">Last bootstrap:</span>
                  <span class="bp-plugin-run-value">{row.last_bootstrap}</span>
                </div>
                <div class="bp-plugin-run-row" data-test-id="last-seed">
                  <span class="bp-plugin-run-label">Last codelist seed:</span>
                  <span class="bp-plugin-run-value">{row.last_seed}</span>
                </div>
              </div>
            </section>
          <% end %>
        </div>
      <% end %>
    </div>
    """
  end

  # ── data loaders ────────────────────────────────────────────────────

  defp load_plugin_rows do
    Registry.all()
    |> Enum.sort_by(& &1.name)
    |> Enum.map(&row_for_plugin/1)
  end

  defp row_for_plugin(%{name: name, module: module, manifest: manifest}) do
    status_map = RunStatus.get(name)

    %{
      name: name,
      module: module,
      version: Map.get(manifest, "version", "?"),
      manifest_description: Map.get(manifest, "description"),
      callbacks: Enum.map(@callbacks, &callback_row(module, &1)),
      last_bootstrap: format_entry(Map.get(status_map, :bootstrap), :bootstrap),
      last_seed: format_entry(Map.get(status_map, :seed), :seed),
      has_settings: plugin_has_settings?(module)
    }
  end

  # True iff the plugin's optional `settings_schema/0` callback returns a
  # non-empty list. Raises are treated as "no settings" so a broken
  # callback can't crash the admin LV.
  defp plugin_has_settings?(module) do
    cond do
      not Code.ensure_loaded?(module) ->
        false

      not function_exported?(module, :settings_schema, 0) ->
        false

      true ->
        try do
          case module.settings_schema() do
            [_ | _] -> true
            _ -> false
          end
        rescue
          _ -> false
        end
    end
  end

  # Plugin-module callback introspection.
  #
  # `defoverridable` machinery: when a plugin overrides a callback the
  # module's compiled bytecode replaces the default function. We can't
  # distinguish "default" vs "override" by `function_exported?/3` alone
  # — both shapes export the function. Instead, compare the callback's
  # default return (e.g. `register_schemas/1` -> `[]`,
  # `action_handlers/0` -> `%{}`, `codelist_seeders/0` -> `[]`) against
  # what the module returns. Non-default return -> override.
  #
  # The detail summary mirrors the mockup in the task brief — count of
  # entries plus a peek at the first few names.
  defp callback_row(module, {fun, arity}) do
    {status, detail} = invoke_and_classify(module, fun, arity)
    mark = if status == :implemented, do: "✓", else: "—"

    %{
      name: fun,
      arity: arity,
      status: status,
      mark: mark,
      detail: detail
    }
  end

  defp invoke_and_classify(module, fun, arity) do
    cond do
      not Code.ensure_loaded?(module) ->
        {:default, "module not loaded"}

      not function_exported?(module, fun, arity) ->
        {:default, "not exported"}

      true ->
        try do
          value = apply(module, fun, default_args(arity))
          classify(fun, arity, value)
        rescue
          e -> {:default, "raised: " <> Exception.message(e)}
        catch
          kind, reason -> {:default, "threw #{kind} #{inspect(reason)}"}
        end
    end
  end

  defp default_args(0), do: []
  defp default_args(1), do: [nil]

  # Per-callback default-vs-override discrimination. The shapes here
  # mirror `Barkpark.Plugin.__using__/1`'s generated bodies.
  defp classify(:register_schemas, 1, []), do: {:default, "default (no schemas)"}

  defp classify(:register_schemas, 1, schemas) when is_list(schemas) do
    names = schemas |> Enum.map(&schema_name/1) |> Enum.reject(&is_nil/1)
    {:implemented, summary("schema", length(schemas), names)}
  end

  defp classify(:register_routes, 1, []), do: {:default, "default (no routes)"}

  defp classify(:register_routes, 1, routes) when is_list(routes) do
    {:implemented, summary("route", length(routes), [])}
  end

  defp classify(:register_routes, 1, _), do: {:implemented, "registers routes"}

  defp classify(:register_workers, 1, []), do: {:default, "default (no workers)"}

  defp classify(:register_workers, 1, workers) when is_list(workers) do
    {:implemented, summary("worker", length(workers), [])}
  end

  defp classify(:validate_settings, 1, :ok),
    do: {:default, "default (no settings validation)"}

  defp classify(:validate_settings, 1, _), do: {:implemented, "validates settings"}

  defp classify(:checkers, 0, []), do: {:default, "default (no checkers)"}

  defp classify(:checkers, 0, checkers) when is_list(checkers) do
    names = checkers |> Enum.map(&checker_name/1) |> Enum.reject(&is_nil/1)
    {:implemented, summary("checker", length(checkers), names)}
  end

  defp classify(:action_handlers, 0, m) when is_map(m) and map_size(m) == 0,
    do: {:default, "default (no handlers)"}

  defp classify(:action_handlers, 0, m) when is_map(m) do
    {:implemented, summary("handler", map_size(m), Map.keys(m))}
  end

  defp classify(:external_sync_entries, 0, m) when is_map(m) and map_size(m) == 0,
    do: {:default, "default (no systems)"}

  defp classify(:external_sync_entries, 0, m) when is_map(m) do
    {:implemented, summary("system", map_size(m), Map.keys(m))}
  end

  defp classify(:codelist_seeders, 0, []), do: {:default, "default (no seeders)"}

  defp classify(:codelist_seeders, 0, seeders) when is_list(seeders) do
    names = seeders |> Enum.map(&seeder_name/1) |> Enum.reject(&is_nil/1)
    {:implemented, summary("seeder", length(seeders), names)}
  end

  defp classify(_fun, _arity, _other), do: {:implemented, "non-default return"}

  defp summary(label, 0, _), do: "no " <> label <> "s"
  defp summary(label, 1, []), do: "1 " <> label
  defp summary(label, n, []), do: "#{n} #{label}s"

  defp summary(label, 1, [name]), do: "1 #{label} — #{to_display(name)}"

  defp summary(label, n, names) do
    preview = names |> Enum.take(3) |> Enum.map(&to_display/1) |> Enum.join(", ")
    suffix = if length(names) > 3, do: ", …", else: ""
    "#{n} #{label}s — #{preview}#{suffix}"
  end

  defp to_display(name) when is_binary(name), do: name
  defp to_display(name) when is_atom(name), do: Atom.to_string(name)
  defp to_display({k, _}), do: to_display(k)
  defp to_display(other), do: inspect(other)

  defp schema_name(%{name: name}), do: name
  defp schema_name(%{"name" => name}), do: name
  defp schema_name(_), do: nil

  defp checker_name({k, _mod}), do: k
  defp checker_name(_), do: nil

  defp seeder_name(fun) when is_function(fun) do
    info = :erlang.fun_info(fun)
    mod = Keyword.get(info, :module)
    name = Keyword.get(info, :name)
    arity = Keyword.get(info, :arity)

    if mod && name && arity do
      "#{inspect(mod)}.#{name}/#{arity}"
    else
      "anonymous"
    end
  end

  defp seeder_name(_), do: nil

  # ── presentation helpers ────────────────────────────────────────────

  defp callback_class(:implemented), do: "bp-callback-impl"
  defp callback_class(:default), do: "bp-callback-default"

  defp format_entry(nil, _kind), do: "never"

  defp format_entry(%{at: at, result: result}, _kind) do
    mark =
      case result do
        {:ok, _} -> "✓"
        :ok -> "✓"
        _ -> "✗"
      end

    suffix =
      case result do
        {:ok, n} when is_integer(n) -> " (#{n})"
        {:error, reason} -> " — error: " <> truncated_inspect(reason)
        _ -> ""
      end

    DateTime.to_string(DateTime.truncate(at, :second)) <> " " <> mark <> suffix
  end

  defp truncated_inspect(term) do
    str = inspect(term)
    if String.length(str) > 80, do: String.slice(str, 0, 79) <> "…", else: str
  end
end
