defmodule BarkparkWeb.TokenController do
  @moduledoc """
  Admin-gated mint of a READ-ONLY, workspace-bound API token.

  `POST /w/:workspace_slug/p/:project_slug/v1/tokens` — wired under the
  `:scoped_admin` pipeline (RequireToken + RequireWorkspaceRole), so only an
  owner/admin of the resolved `current_workspace` can reach it. The endpoint
  exists to mint the `public-read` token a new site needs (see
  `templates/DEPLOYING.md` — non-Default workspaces 403 anonymous reads, so the
  Next.js app needs a token holding a `workspace_membership` row for THIS
  workspace). It replaces the old ssh `mix run --no-start` mint.

  SECURITY — this is NOT a privilege-mint. The mintable permission set is a
  fixed, READ-ONLY allowlist (`public-read`, `read`). Any request asking for
  `write`/`admin`/`ops` — or any permission outside the allowlist — is rejected
  with `422` BEFORE a token is created. Combined with the `:scoped_admin` gate
  (admin authority is the membership ROLE, not the token's global perms), a
  workspace member cannot mint here, and an admin cannot escalate beyond
  read-only.

  The plaintext token is returned ONCE in the 201 body and is never recoverable
  after (only its SHA256 hash is persisted). The raw token is NEVER logged.
  """
  use BarkparkWeb, :controller

  alias Barkpark.Auth
  alias Barkpark.Auth.TokenExpiry
  alias BarkparkWeb.ErrorResponse

  # The ONLY permissions this endpoint will mint. Read-only by construction —
  # anything else (write/admin/ops/…) is a 422, never silently dropped.
  @allowed_permissions ~w(public-read read)

  @doc """
  Mint a read-only token bound to the resolved workspace.

  Body: `{"label": string, "permissions": ["public-read"], "dataset": "production"}`.

    * `label` is required and must be a non-empty string.
    * `permissions` defaults to `["public-read"]`; every entry must be in
      `#{inspect(@allowed_permissions)}` or the request 422s.
    * `dataset` defaults to `"production"`.
    * `expires_at` (optional, ISO-8601) — must be in the future and within the
      kind's max age (`public-read` → share, 30 days; `read` → api, 365 days),
      else 422 naming the max. Never clamped.
    * `no_expiry: true` (optional) — the audited opt-out from any configured
      default expiry. Instance-admin only (the caller's token must hold the
      flat `admin` permission), else 403.
    * Neither → the configured per-kind default (`:token_default_expiry_days`,
      shipped nil = no expiry, i.e. exactly the pre-policy mint).

  201 → `{"token": raw, "label": ..., "permissions": [...], "dataset": ...,
  "workspace": <workspace_slug>}`.
  """
  def create(conn, params) do
    workspace = conn.assigns[:current_workspace]

    with {:ok, label} <- fetch_label(params),
         {:ok, perms} <- fetch_permissions(params),
         dataset when is_binary(dataset) <- fetch_dataset(params),
         {:ok, expiry} <- fetch_expiry(params),
         %{id: ws_id, slug: ws_slug} <- workspace do
      raw = :crypto.strong_rand_bytes(32) |> Base.url_encode64(padding: false)
      mint_opts = [expires_at: expiry, actor: conn.assigns[:api_token]]

      case Auth.create_token(raw, label, dataset, perms, ws_id, mint_opts) do
        {:ok, token} ->
          # RECEIPT LAW (pds w40): BOTH branches of `Auth.create_token/5`
          # (auth.ex:302-320 → `Repo.insert/1`, or `insert_token_with_membership/3`
          # at auth.ex:434-445 whose transaction returns the inserted struct)
          # return `{:ok, %ApiToken{}}`. Every field of this 201 used to be
          # request- or pre-write-derived — `raw` is generated at :52, BEFORE the
          # insert — so the body proved nothing was stored. `id` and
          # `inserted_at` are autogenerated by the insert and cannot be produced
          # from the request. `token: raw` stays: this is the ONLY moment the
          # plaintext secret is ever visible.
          conn
          |> put_status(:created)
          |> json(%{
            token: raw,
            id: token.id,
            inserted_at: token.inserted_at,
            label: label,
            permissions: perms,
            dataset: dataset,
            workspace: ws_slug,
            expires_at: token.expires_at
          })

        {:error, :no_expiry_requires_admin} ->
          ErrorResponse.emit(
            conn,
            {:error, :forbidden},
            TokenExpiry.message(:no_expiry_requires_admin)
          )

        {:error, {:expiry_exceeds_max, _, _} = reason} ->
          expiry_refused(conn, reason)

        {:error, :expiry_not_in_future = reason} ->
          expiry_refused(conn, reason)

        {:error, _reason} ->
          unprocessable(conn, "could not mint token")
      end
    else
      {:error, :invalid_expiry} ->
        unprocessable(
          conn,
          "expires_at must be an ISO-8601 datetime and no_expiry must be true; " <>
            "send at most one of them"
        )

      {:error, :missing_label} ->
        unprocessable(conn, "label is required and must be a non-empty string")

      {:error, {:forbidden_permissions, bad}} ->
        unprocessable(
          conn,
          "permissions #{inspect(bad)} not allowed — this endpoint mints read-only " <>
            "tokens only (#{Enum.join(@allowed_permissions, ", ")})"
        )

      nil ->
        # current_workspace assign missing — the scoped pipeline should have set
        # it; fail closed rather than mint an unbound token.
        unprocessable(conn, "workspace could not be resolved")
    end
  end

  defp fetch_label(%{"label" => label}) when is_binary(label) do
    case String.trim(label) do
      "" -> {:error, :missing_label}
      trimmed -> {:ok, trimmed}
    end
  end

  defp fetch_label(_), do: {:error, :missing_label}

  # Default to ["public-read"]; reject any permission outside the read-only
  # allowlist. A non-list `permissions` value collapses to the forbidden path —
  # and so does a list holding a non-STRING element. `is_list/1` only checks the
  # container: a list of maps (JSON `[{"a":"b"}]`, or the query form
  # `?permissions[][a]=b`) satisfies it, and coercing such an element with
  # `to_string/1` raised Protocol.UndefinedError — a 500 where this module
  # promises a 422. Element shape is checked here so the element rule matches
  # the container rule.
  defp fetch_permissions(%{"permissions" => perms}) when is_list(perms) do
    if Enum.all?(perms, &is_binary/1) do
      perms = Enum.uniq(perms)

      case Enum.reject(perms, &(&1 in @allowed_permissions)) do
        [] when perms == [] -> {:ok, ["public-read"]}
        [] -> {:ok, perms}
        bad -> {:error, {:forbidden_permissions, bad}}
      end
    else
      {:error, {:forbidden_permissions, [:invalid]}}
    end
  end

  defp fetch_permissions(%{"permissions" => _}),
    do: {:error, {:forbidden_permissions, [:invalid]}}

  defp fetch_permissions(_), do: {:ok, ["public-read"]}

  defp fetch_dataset(%{"dataset" => dataset}) when is_binary(dataset) do
    case String.trim(dataset) do
      "" -> "production"
      trimmed -> trimmed
    end
  end

  defp fetch_dataset(_), do: "production"

  # `expires_at` (ISO-8601) XOR `no_expiry: true`; neither → nil (the configured
  # default decides). Anything else is a 422 before a token exists.
  defp fetch_expiry(params) do
    case {Map.get(params, "expires_at"), Map.get(params, "no_expiry")} do
      {nil, nil} ->
        {:ok, nil}

      {nil, true} ->
        {:ok, :no_expiry}

      {at, nil} when is_binary(at) ->
        case DateTime.from_iso8601(at) do
          {:ok, dt, _offset} -> {:ok, dt}
          _ -> {:error, :invalid_expiry}
        end

      _ ->
        {:error, :invalid_expiry}
    end
  end

  defp expiry_refused(conn, reason) do
    ErrorResponse.emit_fields(conn, :unprocessable_entity, %{
      code: "unprocessable",
      message: TokenExpiry.message(reason),
      details: TokenExpiry.details(reason)
    })
  end

  defp unprocessable(conn, message) do
    conn
    |> ErrorResponse.emit_fields(:unprocessable_entity, %{code: "unprocessable", message: message})
  end
end
