defmodule Barkpark.Media.RenditionsTest do
  # async: false — toggles the global :image_backend Application env.
  # DataCase (not ExUnit.Case) because fixtures are now PERSISTED MediaFile rows:
  # the in-fence post-generate `Media.get_file/1` recheck reads the DB, and a
  # non-persisted struct with no sandbox connection raises "cannot find
  # ownership process".
  use Barkpark.DataCase, async: false

  import ExUnit.CaptureLog

  alias Barkpark.Media
  alias Barkpark.Media.Renditions
  alias Barkpark.Media.Storage.MediaFile

  # Stub backend that always succeeds by writing a placeholder byte to `dest`.
  defmodule OkBackend do
    @behaviour Barkpark.Media.ImageBackend
    @impl true
    def render(_src, dest, _spec, _watermark) do
      File.write!(dest, "rendition")
      :ok
    end

    @impl true
    def available?, do: true
  end

  # Stub backend that records the spec it was handed (in the test process, keyed
  # by preset) so a test can assert the og preset flows an exact-crop spec.
  defmodule SpyBackend do
    @behaviour Barkpark.Media.ImageBackend
    @impl true
    def render(_src, dest, spec, _watermark) do
      send(self(), {:rendered, spec})
      File.write!(dest, "rendition")
      :ok
    end

    @impl true
    def available?, do: true
  end

  # Stub backend that reproduces the libvips/ARM failure the gate must avoid
  # ever reaching for non-raster mimes.
  defmodule FailBackend do
    @behaviour Barkpark.Media.ImageBackend
    @impl true
    def render(_src, _dest, _spec, _watermark),
      do: {:error, %{__struct__: Image.Error, message: "Failed to find load"}}

    @impl true
    def available?, do: true
  end

  setup do
    original = Application.get_env(:barkpark, :image_backend)

    on_exit(fn ->
      case original do
        nil -> Application.delete_env(:barkpark, :image_backend)
        val -> Application.put_env(:barkpark, :image_backend, val)
      end
    end)

    :ok
  end

  # Persist the fixture: the post-generate recheck reads `Media.get_file/1`, so
  # the row must exist in the sandbox connection. The id is autogenerated by the
  # :binary_id primary key (NOT cast from attrs) — use the RETURNED struct's id.
  # The blob path is keyed on a random token (not the id, which we don't have
  # until after insert).
  defp file(mime, ext) do
    token = Ecto.UUID.generate()
    rel = Path.join("test-blobs", "#{token}.#{ext}")
    abs = Media.file_path(rel)
    File.mkdir_p!(Path.dirname(abs))
    File.write!(abs, "blob-bytes")

    {:ok, media_file} =
      %MediaFile{}
      |> MediaFile.changeset(%{
        mime_type: mime,
        path: rel,
        original_name: "x.#{ext}",
        filename: "x.#{ext}"
      })
      |> Repo.insert()

    on_exit(fn ->
      File.rm(abs)
      Renditions.delete_for_file(media_file.id)
    end)

    media_file
  end

  describe "generate_all/2 gates on the raster set" do
    test "SVG blob generates no rendition and logs no 'Failed to find load'" do
      Application.put_env(:barkpark, :image_backend, FailBackend)
      svg = file("image/svg+xml", "svg")

      log =
        capture_log(fn ->
          assert Renditions.generate_all(svg) == :ok
        end)

      refute log =~ "Failed to find load"
      # No preset file was written (the backend was never invoked).
      for preset <- Renditions.presets() do
        assert Renditions.relative_path(svg, preset) == nil
      end
    end

    test "TIFF blob is skipped cleanly (no backend call, no error log)" do
      Application.put_env(:barkpark, :image_backend, FailBackend)
      tiff = file("image/tiff", "tiff")

      log = capture_log(fn -> assert Renditions.generate_all(tiff) == :ok end)

      refute log =~ "Failed to find load"
    end

    test "PNG blob generates renditions for every preset" do
      Application.put_env(:barkpark, :image_backend, OkBackend)
      png = file("image/png", "png")

      assert Renditions.generate_all(png) == :ok

      for preset <- Renditions.presets() do
        assert Renditions.relative_path(png, preset) != nil
      end
    end

    test "PNG whose entire rendition set fails returns {:error, :all_renditions_failed}" do
      Application.put_env(:barkpark, :image_backend, FailBackend)
      png = file("image/png", "png")

      log =
        capture_log(fn ->
          assert Renditions.generate_all(png) == {:error, :all_renditions_failed}
        end)

      # A raster image that truly fails DOES surface the warning — that path is
      # legitimate; the fix is only that non-raster mimes never reach it.
      assert log =~ "Failed to find load"
    end
  end

  describe "the og preset is a fixed 1200x630 exact crop" do
    test "og flows an exact-crop spec (1200x630, crop: :attention) to the backend" do
      Application.put_env(:barkpark, :image_backend, SpyBackend)
      png = file("image/png", "png")

      assert {:ok, _rel} = Renditions.ensure(png, "og")

      assert_received {:rendered, spec}
      assert spec.max_width == 1200
      assert spec.max_height == 630
      assert spec.format == "jpg"
      assert spec.quality == 85
      # The crop key is what turns the max-fit box into an exact-fill crop, so the
      # og rendition is a constant 1200x630 whatever the source aspect (D4).
      assert spec.crop == :attention
    end

    test "a FIT preset (thumb) carries NO crop key — only og is an exact crop" do
      Application.put_env(:barkpark, :image_backend, SpyBackend)
      png = file("image/png", "png")

      assert {:ok, _rel} = Renditions.ensure(png, "thumb")

      assert_received {:rendered, spec}
      refute Map.has_key?(spec, :crop)
    end
  end
end
