# Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
# Regenerate: node design/emit.mjs --write

defmodule BarkparkWeb.Studio.TokensGen do
  @moduledoc """
  Unified Aesthetic Studio-surface tokens, generated from design/tokens.json.
  Regenerate with `node design/emit.mjs --write`; never hand-edit.

  Two families live here, both as returned VALUES (not CSS vars):

    * CATEGORICAL identity swatches (presence + Sheets-CF hex lists): presence
      hues index by a phash2 of the user id, and the Sheets-CF swatches are
      PERSISTED DATA (stored on the cell/rule/tab, compared for selection,
      echoed in data-test-id) — the concrete hex must survive.
    * The LIFECYCLE mirror (glyph / ascii / adaptive hue per state) — the
      Studio twin of the ONE lifecycle source (tokens.lifecycle) the Go board
      + paper-surface CSS also emit from. It feeds the living styleguide's
      lifecycle row (glyph + braille + colour label); the applied glyph COLOUR
      comes from the emitted --life-<state> CSS var, so no hex is ever painted
      inline. design/check.mjs §6 gates this mirror against Go + CSS + tokens.
  """

  # Presence-avatar palette (presence_state.ex @colors) — 8 fixed categorical
  # hues; a phash2 of the user id picks one.
  def presence_palette, do: ~w(#3b82f6 #ef4444 #10b981 #f59e0b #8b5cf6 #ec4899 #06b6d4 #f97316)

  # Sheets conditional-format cell/rule backgrounds — the pastel fills
  # (sheet_grid.ex bg-swatch loop). PERSISTED as phx-value-bg.
  def sheet_cf_backgrounds, do: ~w(#fde68a #bbf7d0 #bfdbfe #fecaca #e9d5ff #e5e7eb)

  # Sheets per-tab colors — the saturated dot strip (sheet_grid.ex tab-color
  # picker). Read best more vivid than the pastel cell backgrounds.
  def sheet_tab_colors, do: ~w(#ef4444 #f59e0b #eab308 #22c55e #3b82f6 #8b5cf6)

  # Public status-page health-severity DATA tones (status_controller.ex
  # @labels + component dots) — inline-style hex conveying OUTAGE SEVERITY,
  # NOT a CSS role. partial_outage is an out-of-model tone between warn-amber
  # (degraded) and danger-red (major_outage): the severity distinction must
  # survive, so it is NOT recolored onto --warn/--danger.
  def status_health,
    do: %{
      operational: "#16a34a",
      degraded: "#d97706",
      partial_outage: "#ea580c",
      major_outage: "#dc2626"
    }

  # Neutral gray fallback for an unrecognised / missing status.
  def status_health_unknown, do: "#6b7280"

  # Personal Dev Fleet listener-status DATA tones (fleet_live.ex @pills dot +
  # track tint at /admin/fleet) — the PDF-D23 vocabulary as inline-style hex,
  # categorical listener-liveness DATA, not a CSS role. STRING keys: the
  # consumer keys by the runtime status string; an unrecognised status falls
  # back to "idle" in FleetLive.pill/1.
  def fleet_status,
    do: %{
      "working" => "#16a34a",
      "idle" => "#64748b",
      "blocked" => "#dc2626",
      "provisioning" => "#7c3aed",
      "offline" => "#94a3b8"
    }

  # Lifecycle mirror — one row per state, canonical emission order. glyph +
  # ascii are text CONTENT; light/dark are the adaptive hue LABELS (the applied
  # colour is var(--life-<state>) from the GENERATED CSS block). Mirrors
  # tokens.lifecycle 1:1; done/closed stay TEAL, distinct from status.ok green.
  def lifecycle do
    [
      %{state: "in_progress", glyph: "⠋", ascii: "~", light: "#2563eb", dark: "#60a5fa"},
      %{state: "blocked", glyph: "!", ascii: "!", light: "#d97706", dark: "#fbbf24"},
      %{state: "done", glyph: "✓", ascii: "v", light: "#0d9488", dark: "#2dd4bf"},
      %{state: "closed", glyph: "✓", ascii: "v", light: "#0d9488", dark: "#2dd4bf"},
      %{state: "cancelled", glyph: "✕", ascii: "x", light: "#a1a1aa", dark: "#71717a"},
      %{state: "ready", glyph: "○", ascii: "o", light: "#18181b", dark: "#e7edf2"},
      %{state: "open", glyph: "○", ascii: ".", light: "#71717a", dark: "#5f6b78"},
      %{state: "considering", glyph: "◌", ascii: "?", light: "#a1a1aa", dark: "#71717a"},
      %{state: "researching", glyph: "◎", ascii: "R", light: "#7c3aed", dark: "#a78bfa"}
    ]
  end

  # in_progress braille spinner frames (spinner.go / tokens.lifecycle frames).
  def lifecycle_frames, do: ~w(⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏)
end
