# Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
# Regenerate: node design/emit.mjs --write

defmodule BarkparkWeb.Studio.TokensGen do
  @moduledoc """
  Unified Aesthetic CATEGORICAL palettes for the Studio surface, generated
  from design/tokens.json. Regenerate with `node design/emit.mjs --write`;
  never hand-edit.

  These are categorical identity swatches (hex value lists), NOT status
  roles and NOT CSS vars: presence hues index by a phash2 of the user id,
  and the Sheets-CF swatches are PERSISTED DATA (stored on the cell/rule/tab,
  compared for selection, echoed in data-test-id) — the concrete hex must
  survive, so it lives here as returned values rather than in emitted CSS.
  """

  # Presence-avatar palette (presence_state.ex @colors) — 8 fixed categorical
  # hues; a phash2 of the user id picks one.
  def presence_palette, do: ~w(#3b82f6 #ef4444 #10b981 #f59e0b #8b5cf6 #ec4899 #06b6d4 #f97316)

  # Sheets conditional-format cell/rule backgrounds — the pastel fills
  # (sheet_grid.ex bg-swatch loop). PERSISTED as phx-value-bg.
  def sheet_cf_backgrounds, do: ~w(#fde68a #bbf7d0 #bfdbfe #fecaca #e9d5ff #e5e7eb)

  # Sheets per-tab colors — the saturated dot strip (sheet_grid.ex tab-color
  # picker). Read best more vivid than the pastel cell backgrounds.
  def sheet_tab_colors, do: ~w(#ef4444 #f59e0b #eab308 #22c55e #3b82f6 #8b5cf6)
end
