// AUTO-GENERATED by scripts/gen-showcase-content.mjs — DO NOT hand-edit.
//
// The full 64-type PortableDocument grammar, one block per registered
// non-plugin type, lifted verbatim from @barkpark/react's pd-golden parity
// fixtures. This is the flagship demo post's body: it renders through the
// canonical PortableDoc renderer (index + post pages) and hydrates its media
// mount points (mermaid diagram + asciicast) via @barkpark/react/client.
//
// Regenerate with: node scripts/gen-showcase-content.mjs

import type { Block } from '@barkpark/react'

/** The 64 canonical block types, concatenated from the parity goldens. */
export const showcaseContent: Block[] = [
  {
    "href": "https://example.com/docs",
    "label": "Read the docs",
    "priority": "primary",
    "type": "action"
  },
  {
    "method": "POST",
    "params": [
      {
        "in": "path",
        "name": "dataset",
        "required": true,
        "type": "string"
      }
    ],
    "path": "/v1/data/mutate",
    "type": "api-endpoint"
  },
  {
    "caption": "A terminal walkthrough",
    "poster": "npt:0:12",
    "src": "https://example.com/casts/demo.cast",
    "type": "asciicast"
  },
  {
    "bars": [
      {
        "label": "paragraph",
        "value": 40
      },
      {
        "label": "heading",
        "value": 25
      },
      {
        "label": "list",
        "value": 10
      }
    ],
    "type": "bar-chart",
    "values": true
  },
  {
    "cite": "Alan Kay",
    "content": [
      {
        "type": "text",
        "value": "The best way to predict the future is to invent it."
      }
    ],
    "type": "blockquote"
  },
  {
    "items": [
      "Jane Rae",
      "2026-07-16"
    ],
    "type": "byline"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "This is a warning callout body."
      }
    ],
    "title": "Heads up",
    "tone": "warn",
    "type": "callout"
  },
  {
    "slots": {
      "action": [
        {
          "href": "https://example.com/board",
          "label": "Open the board",
          "type": "action"
        }
      ],
      "body": [
        {
          "content": [
            {
              "type": "text",
              "value": "Card body text."
            }
          ],
          "type": "paragraph"
        }
      ],
      "title": [
        {
          "text": "Card title",
          "type": "heading"
        }
      ]
    },
    "tone": "info",
    "type": "card"
  },
  {
    "items": [
      {
        "text": "The first rule body.",
        "title": "Rule one",
        "tone": "info"
      },
      {
        "text": "The second rule body.",
        "title": "Rule two",
        "tone": "warn"
      }
    ],
    "type": "cards"
  },
  {
    "axes": {
      "xLabels": [
        "W1",
        "W2",
        "W3",
        "W4"
      ]
    },
    "caption": "Coverage over time",
    "kind": "line",
    "series": [
      {
        "label": "Covered",
        "points": [
          10,
          20,
          35,
          42
        ]
      }
    ],
    "type": "chart"
  },
  {
    "approval_status": "pending",
    "summary": "rm -rf api/_build/prod",
    "tool_name": "Bash",
    "type": "chat-approval"
  },
  {
    "approval_status": "pending",
    "preview": "Collapse five renderers to three, prove parity per block.",
    "title": "Unify the renderers",
    "type": "chat-plan"
  },
  {
    "approval_status": "pending",
    "questions": [
      {
        "options": [
          "Elixir",
          "Go",
          "JS"
        ],
        "question": "Which renderer is canonical?"
      }
    ],
    "type": "chat-question"
  },
  {
    "tokens": 1200,
    "type": "chat-thinking"
  },
  {
    "todos": [
      {
        "content": "Author the array",
        "status": "completed"
      },
      {
        "active_form": "Wiring the generator",
        "content": "Wire the generator",
        "status": "in_progress"
      },
      {
        "content": "Prove parity",
        "status": "pending"
      }
    ],
    "type": "chat-todo"
  },
  {
    "input": {
      "file_path": "lib/foo.ex",
      "new_string": "def hello do\n  :new\nend",
      "old_string": "def hello do\n  :old\nend"
    },
    "type": "chat-tool-diff"
  },
  {
    "syncKey": "lang",
    "tabs": [
      {
        "label": "JS",
        "language": "js",
        "value": "console.log(1)"
      },
      {
        "label": "Go",
        "language": "go",
        "value": "fmt.Println(1)"
      }
    ],
    "type": "code-tabs"
  },
  {
    "type": "code",
    "value": "def hello do\n  :world\nend"
  },
  {
    "columns": [
      [
        {
          "content": [
            {
              "type": "text",
              "value": "Left column body."
            }
          ],
          "type": "paragraph"
        }
      ],
      [
        {
          "content": [
            {
              "type": "text",
              "value": "Right column body."
            }
          ],
          "type": "paragraph"
        }
      ]
    ],
    "type": "columns"
  },
  {
    "rows": [
      {
        "label": "Survey every corpus chapter",
        "met": 2,
        "total": 5
      },
      {
        "label": "File child tasks",
        "met": 5,
        "total": 5
      }
    ],
    "type": "criteria-progress"
  },
  {
    "caption": "The three-stage pipeline",
    "source": "graph TD; A[Ingest] --> B[Render] --> C[Publish]",
    "type": "diagram"
  },
  {
    "diff": "diff --git a/lib/render/compose.ex b/lib/render/compose.ex\nindex 3f9c2d1..8a41b7e 100644\n--- a/lib/render/compose.ex\n+++ b/lib/render/compose.ex\n@@ -1,4 +1,5 @@\n defmodule Render.Compose do\n-  def compose(block), do: starter(block)\n+  def compose(block), do: grown(block)\n+  defp grown(block), do: block\n end",
    "file": "lib/render/compose.ex",
    "lang": "elixir",
    "type": "diff"
  },
  {
    "type": "divider"
  },
  {
    "legendA": "Med katalogen",
    "legendB": "Bare hendene",
    "rows": [
      {
        "delta": "−30 %",
        "label": "add-error-shape",
        "valueA": "1 478",
        "valueB": "2 121"
      },
      {
        "delta": "−34,8 %",
        "label": "add-oban-worker",
        "source": "task:jdf-bl-historiene",
        "valueA": "1 788",
        "valueB": "2 743"
      }
    ],
    "sourceDefault": "commit:591fdcd53",
    "type": "duel"
  },
  {
    "display": true,
    "tex": "E = mc^2",
    "type": "equation"
  },
  {
    "blocks": [
      {
        "content": [
          {
            "type": "text",
            "value": "Hidden detail."
          }
        ],
        "type": "paragraph"
      }
    ],
    "open": false,
    "summary": "Show the full trace",
    "type": "expandable"
  },
  {
    "text": "Dispatches",
    "type": "eyebrow"
  },
  {
    "caption": "Figure with a captioned child",
    "child": {
      "content": [
        {
          "type": "text",
          "value": "The figure body."
        }
      ],
      "type": "paragraph"
    },
    "type": "figure"
  },
  {
    "legend": "● created · ○ injected · ✕ removed",
    "text": "api/lib/barkpark/portable_doc/render/\n├── components.ex ● diff_html/1 + filetree_html/1\n├── compose.ex ○ grew the diff + filetree clauses\n└── starter_stub.ex ✕ removed",
    "type": "filetree"
  },
  {
    "notes": [
      {
        "id": "fn1",
        "text": "The board updates live."
      },
      {
        "id": "fn2",
        "text": "You always feel progress."
      }
    ],
    "type": "footnote"
  },
  {
    "kind": "grill",
    "questions": [
      {
        "id": "q1",
        "prompt": "Ship it?",
        "type": "yesno"
      },
      {
        "id": "q2",
        "options": [
          "Next",
          "Astro",
          "Phoenix"
        ],
        "prompt": "Pick a surface",
        "type": "single"
      },
      {
        "id": "q3",
        "options": [
          "Elixir",
          "Go",
          "JS"
        ],
        "prompt": "Which renderers to keep",
        "type": "multi"
      },
      {
        "id": "q4",
        "prompt": "Confidence",
        "scale": {
          "max": 5,
          "min": 1
        },
        "type": "scale"
      },
      {
        "id": "q5",
        "prompt": "Anything else?",
        "type": "text"
      }
    ],
    "type": "form"
  },
  {
    "rows": [
      {
        "label": "Elixir",
        "note": "source of truth",
        "value": 2
      },
      {
        "label": "Go",
        "value": 1
      },
      {
        "label": "JS",
        "value": 1
      }
    ],
    "title": "Coverage by surface",
    "type": "gauge-list"
  },
  {
    "level": 2,
    "text": "The render path",
    "type": "heading"
  },
  {
    "cells": [
      [
        0.1,
        0.4,
        0.9
      ],
      [
        0.6,
        0.2,
        0.5
      ]
    ],
    "type": "heatmap"
  },
  {
    "alt": "Cover art",
    "height": 360,
    "src": "https://cdn.example.com/cover.png",
    "type": "image",
    "width": 640
  },
  {
    "content": [
      {
        "type": "text",
        "value": "A lead paragraph that opens the article."
      }
    ],
    "type": "ingress"
  },
  {
    "nodes": [
      {
        "body": "Et kveldsprosjekt med én forfatter.",
        "overline": "jan–sep 2025",
        "title": "nextgen-go-cli",
        "unit": "commits",
        "value": "335"
      },
      {
        "body": "Idéen ble født på nytt.",
        "overline": "2026",
        "title": "Navnebyttet: Scaffy"
      },
      {
        "overline": "i dag",
        "source": "https://jarl.no/prosjekter/scaffy",
        "title": "Kommandoer som innhold",
        "unit": "kommandoer",
        "value": "22"
      }
    ],
    "sourceDefault": "paper:scaffy-benchmark",
    "type": "lineage"
  },
  {
    "items": [
      [
        {
          "type": "text",
          "value": "First point"
        }
      ],
      [
        {
          "type": "text",
          "value": "Second point"
        }
      ]
    ],
    "ordered": false,
    "type": "list"
  },
  {
    "label": "Note",
    "lead": "Run-in",
    "text": "A single annotated row.",
    "type": "note"
  },
  {
    "items": [
      {
        "label": "Upgrade",
        "lead": "Instant",
        "text": "The board updates live."
      },
      {
        "label": "Why",
        "lead": "Trust",
        "text": "You always feel progress."
      }
    ],
    "type": "notes"
  },
  {
    "description": "Papers with useful context for this change.",
    "refs": [
      {
        "description": "A practical guide to publishing clear, useful Papers.",
        "reason": "See the principles behind this example.",
        "slug": "paper-authoring-excellence",
        "title": "Paper authoring excellence"
      }
    ],
    "title": "Continue reading",
    "type": "paper-links"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "A body paragraph with "
      },
      {
        "marks": [
          {
            "type": "bold"
          }
        ],
        "type": "text",
        "value": "bold emphasis"
      },
      {
        "type": "text",
        "value": " inside it."
      }
    ],
    "type": "paragraph"
  },
  {
    "nodes": [
      {
        "detail": "reads the queue",
        "kind": "source",
        "source": true,
        "title": "Ingest"
      },
      {
        "detail": "maps the rows",
        "kind": "emit",
        "source": "queue.ex:42",
        "title": "Transform"
      },
      {
        "detail": "writes the board",
        "kind": "gate",
        "title": "Publish"
      }
    ],
    "type": "pipeline"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "The best interface is no interface."
      }
    ],
    "type": "pullquote"
  },
  {
    "questions": [
      {
        "id": "q1",
        "prompt": "Ready to review?",
        "type": "yesno"
      },
      {
        "id": "q2",
        "prompt": "Notes",
        "type": "text"
      }
    ],
    "type": "questionnaire"
  },
  {
    "scale": [
      "Q1",
      "Q2",
      "Q3"
    ],
    "snapshot": [
      {
        "left": 0,
        "phase_row": true,
        "status": "done",
        "title": "Foundation",
        "width": 40
      },
      {
        "left": 40,
        "status": "in_progress",
        "title": "Ship the board",
        "width": 35
      }
    ],
    "type": "roadmap"
  },
  {
    "caption": "Testrunden",
    "distance": "4.2 km",
    "duration": "12m",
    "elevation": "61 m",
    "polyline": "}ujlJgxgcAyPqOgO~JsLc[wF{aAdJ{[hSeE~MzTbInh@aB~e@",
    "sport": "sykling",
    "type": "route"
  },
  {
    "blocks": [
      {
        "slots": {
          "title": [
            {
              "text": "Alpha cell",
              "type": "heading"
            }
          ]
        },
        "type": "card"
      },
      {
        "slots": {
          "title": [
            {
              "text": "Beta cell",
              "type": "heading"
            }
          ]
        },
        "span": 2,
        "type": "card"
      }
    ],
    "layout": {
      "gap": "md",
      "mode": "grid",
      "tracks": 2
    },
    "type": "section"
  },
  {
    "ref": "budget-2026",
    "snapshot": {
      "col_widths": [
        12,
        8
      ],
      "head": [
        "Item",
        "Cost"
      ],
      "rows": [
        [
          "Hosting",
          "42"
        ],
        [
          "Domains",
          "18"
        ]
      ]
    },
    "type": "sheet"
  },
  {
    "detail": "checks the criteria",
    "kind": "gate",
    "source": true,
    "title": "Review",
    "type": "stage"
  },
  {
    "items": [
      {
        "label": "Renderers today",
        "value": "5"
      },
      {
        "label": "Renderers target",
        "value": "3"
      }
    ],
    "type": "stat-grid"
  },
  {
    "body": "Hver blokk består sine egne mekaniske porter.",
    "denom": "118",
    "label": "Blocks covered",
    "max": 118,
    "source": "commit:591fdcd53",
    "spark": [
      3,
      5,
      8,
      13,
      21
    ],
    "type": "stat",
    "unit": "blokker",
    "value": "71"
  },
  {
    "items": [
      {
        "label": "In-scope types",
        "value": "42"
      },
      {
        "label": "Renderers",
        "source": "task:jdf-bl-historiene",
        "value": "3"
      }
    ],
    "sourceDefault": "paper:scaffy-benchmark",
    "type": "stats"
  },
  {
    "type": "status-legend"
  },
  {
    "steps": [
      {
        "blocks": [
          {
            "content": [
              {
                "type": "text",
                "value": "Run bp task next."
              }
            ],
            "type": "paragraph"
          }
        ],
        "title": "Claim the task"
      },
      {
        "title": "Stamp evidence"
      }
    ],
    "type": "steps"
  },
  {
    "head": [
      [
        {
          "type": "text",
          "value": "Surface"
        }
      ],
      [
        {
          "type": "text",
          "value": "Renderer"
        }
      ]
    ],
    "rows": [
      [
        [
          {
            "type": "text",
            "value": "Phoenix"
          }
        ],
        [
          {
            "type": "text",
            "value": "Elixir"
          }
        ]
      ],
      [
        [
          {
            "type": "text",
            "value": "Next"
          }
        ],
        [
          {
            "type": "text",
            "value": "React"
          }
        ]
      ]
    ],
    "type": "table"
  },
  {
    "tabs": [
      {
        "blocks": [
          {
            "content": [
              {
                "type": "text",
                "value": "brew install barkpark"
              }
            ],
            "type": "paragraph"
          }
        ],
        "label": "macOS"
      },
      {
        "blocks": [
          {
            "content": [
              {
                "type": "text",
                "value": "curl -fsSL install.sh | sh"
              }
            ],
            "type": "paragraph"
          }
        ],
        "label": "Linux"
      }
    ],
    "type": "tabs"
  },
  {
    "snapshot": [
      {
        "status": "open",
        "title": "Backlog groom"
      },
      {
        "priority": "1",
        "status": "ready",
        "title": "Wire the harness"
      },
      {
        "priority": "0",
        "status": "in_progress",
        "title": "Render the board"
      },
      {
        "status": "blocked",
        "title": "Await review"
      },
      {
        "criteria": {
          "met": 2,
          "total": 2
        },
        "status": "done",
        "title": "Ship the legend"
      }
    ],
    "type": "task-board"
  },
  {
    "task": {
      "criteria": [
        {
          "met": true,
          "text": "Gen emits fixtures"
        },
        {
          "met": false,
          "text": "JS realizes the golden"
        }
      ],
      "labels": [
        "parity",
        "w1"
      ],
      "priority": "1",
      "status": "in_progress",
      "timeline": [
        {
          "label": "Filed",
          "status": "open"
        },
        {
          "label": "Building",
          "status": "in_progress"
        },
        {
          "label": "Shipped",
          "status": "done"
        }
      ],
      "title": "Wire the harness"
    },
    "type": "task-detail"
  },
  {
    "snapshot": [
      {
        "status": "ready",
        "title": "Seed the renderer"
      },
      {
        "status": "open",
        "title": "Close the gaps"
      }
    ],
    "type": "task-list"
  },
  {
    "snapshot": [
      {
        "status": "done",
        "title": "Author the array"
      },
      {
        "priority": "0",
        "status": "in_progress",
        "title": "Wire the generator"
      },
      {
        "status": "ready",
        "title": "Prove parity"
      }
    ],
    "type": "tasks"
  },
  {
    "children": [
      {
        "content": [
          {
            "type": "text",
            "value": "Inside the frame."
          }
        ],
        "type": "paragraph"
      }
    ],
    "footer": "q to quit",
    "live": true,
    "title": "bp tasks",
    "type": "terminal"
  },
  {
    "depth": 2,
    "items": [
      {
        "anchor": "getting-started",
        "level": 2,
        "text": "Getting started"
      },
      {
        "anchor": "installation",
        "level": 3,
        "text": "Installation"
      },
      {
        "anchor": "advanced-usage",
        "level": 2,
        "text": "Advanced usage"
      }
    ],
    "numbered": true,
    "type": "toc"
  },
  {
    "captions": [
      {
        "lang": "en",
        "src": "https://ex.com/en.vtt"
      }
    ],
    "poster": "https://ex.com/demo-poster.jpg",
    "src": "https://ex.com/demo.mp4",
    "type": "video"
  }
]

export default showcaseContent
