package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/FRIKKern/barkpark/internal/cloudclient"
)

// `bp make workflow <site>` — the GitHub Actions BUILDER TEMPLATE, client #2 of
// the prebuilt lane (ssw9-bl-gh-actions-builder-template).
//
// WHAT THIS IS, AND WHAT IT IS NOT. The YAML emitted here is TEMPLATE CONTENT:
// it is scaffolded into the USER'S repository as `.github/workflows/…`, and it
// is not — ever — part of this repository's own CI. Nothing under this repo's
// `.github/` is written, read or referenced by this file.
//
// WHY IT LIVES HERE AND NOWHERE ELSE (the single-source rule). There are two
// near-identical starter-template trees in this monorepo —
// `cloud/priv/templates/` and `js/packages/create-barkpark-app/templates/` —
// and shipping a deploy workflow into BOTH is how the two copies diverge. A
// workflow is also not a starter's content: every starter deploys the same way,
// because the wire contract it encodes belongs to the prebuilt lane, not to a
// blog vs a website. So the template is a CLI emitter with ONE owner (the CLI
// lane) and no copy in either tree; `TestWorkflowTemplateIsNotDuplicated` is the
// mechanical half of that sentence.
//
// WHY curl AND NOT bp. The workflow shells out to curl on purpose, so a CI job
// needs no bp binary, no SDK and no install step — the two calls take a JSON
// body and a raw `application/octet-stream` body respectively. That choice is
// now a CONVENIENCE rather than a necessity: `BARKPARK_CLOUD_TOKEN`
// (CloudTokenEnv, config.go) is a real env override on the CLI today, so a
// bp-based workflow would authenticate fine. curl still wins for a template
// because it has zero install cost and pins the wire contract in the open where
// a reader can see it.
//
// THE ORDER IS FORCED, and it is the same order runCloudSitePrebuiltDeploy
// documents: MINT first (the 201 carries the build_id the bytes must be stamped
// with — HEALTH asserts that marker BY VALUE), then BUILD with the minted ids
// exported, then UPLOAD, then FOLLOW. A workflow is the one place the two-run
// `--deployment <id>` loop collapses honestly into one motion, because the build
// happens BETWEEN the two calls in the same job rather than in a shell bp did
// not launch.

// workflowDefaults are the knobs the emitted workflow exposes as job-level env.
// They are env rather than baked literals so the same file works for a repo that
// builds with something other than npm, and so the template can be EXERCISED by
// a test that points BARKPARK_API at a fake control plane.
const (
	workflowDefaultDist     = "dist"
	workflowDefaultBuildCmd = "npm run build"
	// workflowStepPrefix marks the steps that are the Barkpark deploy itself.
	// The test enrols steps BY THIS PREFIX rather than by a hand-kept list, so a
	// step added later is exercised without anyone remembering to enrol it.
	workflowStepPrefix = "Barkpark: "
	// patDefaultValidityDays MIRRORS the control plane's
	// @pat_default_validity_days (cloud/lib/barkpark_cloud/accounts/user_token.ex).
	// It is repeated here because the number is the whole point of the warning
	// the template prints, and a stale number is a warning that lies —
	// TestWorkflowPatValidityMatchesTheControlPlane reads the Elixir source and
	// fails if the two drift.
	patDefaultValidityDays = 30
)

// workflowOptions is the emitter's input.
type workflowOptions struct {
	Site   string
	Dist   string
	Branch string
}

// renderDeployWorkflow returns the GitHub Actions workflow YAML for <site>.
//
// Every `run:` block is self-contained shell that reads only job env — no
// `${{ … }}` interpolation inside a script — which is what makes the steps
// runnable outside GitHub, and therefore testable.
// @canonical capability:gh-actions-builder-template aka:make-workflow,prebuilt-workflow,deploy-workflow-template doc:docs/cards/cli.md
func renderDeployWorkflow(o workflowOptions) string {
	dist := strings.TrimSpace(o.Dist)
	if dist == "" {
		dist = workflowDefaultDist
	}
	branch := strings.TrimSpace(o.Branch)
	if branch == "" {
		branch = "main"
	}
	var b strings.Builder
	p := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	p("# Deploy %s to Barkpark Cloud — the PREBUILT lane.", o.Site)
	p("#")
	p("# This job builds the site HERE and ships only the output; nothing is built")
	p("# on the serving box. It is curl-only on purpose: no bp binary, no SDK, no")
	p("# install step. Generated by `bp make workflow %s` — re-run it to refresh.", o.Site)
	p("#")
	p("# ONE REPO SECRET: BARKPARK_CLOUD_TOKEN, a Barkpark Cloud PAT with the")
	p("# `deploy` ability. Mint it with:")
	p("#")
	p("#   bp cloud token mint --name gh-actions --ability deploy --expires-days 365 --out pat.txt")
	p("#")
	p("# VALIDITY IS THE TRAP. A PAT minted with no expiry window defaults to")
	p("# %d DAYS (cloud/lib/barkpark_cloud/accounts/user_token.ex,", patDefaultValidityDays)
	p("# @pat_default_validity_days), so an unattended workflow starts 401-ing a")
	p("# month after it was set up, with no other symptom. Pass --expires-days")
	p("# explicitly (7|30|60|90|365|never) and put the renewal date in a calendar.")
	p("#")
	p("# PREREQUISITE: the site must have opted in to off-box builds, or the mint")
	p("# below is refused with 422 prebuilt_not_enabled:")
	p("#")
	p("#   bp cloud site settings %s --prebuilt-enabled true", o.Site)
	p("#")
	p("# STATIC ONLY. The box stages the uploaded tree and flips a symlink; nothing")
	p("# starts a server for these bytes. A node/SSR site must build on its box.")
	p("")
	p("name: Deploy to Barkpark")
	p("")
	p("on:")
	p("  push:")
	p("    branches: [%s]", branch)
	p("  workflow_dispatch:")
	p("")
	p("# A prebuilt mint is NONCED: two concurrent runs mint two build ids and the")
	p("# loser uploads bytes stamped with an id its deployment never minted.")
	p("concurrency:")
	p("  group: barkpark-deploy-%s", o.Site)
	p("  cancel-in-progress: false")
	p("")
	p("jobs:")
	p("  deploy:")
	p("    runs-on: ubuntu-latest")
	p("    env:")
	p("      BARKPARK_SITE: %s", o.Site)
	p("      BARKPARK_API: %s", cloudclient.DefaultBaseURL)
	p("      BARKPARK_DIST: %s", dist)
	p("      BARKPARK_BUILD_CMD: %s", workflowDefaultBuildCmd)
	p("      BARKPARK_CLOUD_TOKEN: ${{ secrets.BARKPARK_CLOUD_TOKEN }}")
	p("    steps:")
	p("      - uses: actions/checkout@v4")
	p("      - uses: actions/setup-node@v4")
	p("        with:")
	p("          node-version: '20'")
	p("      - run: npm ci")
	p("")

	step := func(name, script string) {
		// QUOTED, and it has to be: the prefix ends in ": ", and a colon-space
		// inside an unquoted YAML scalar makes the line a mapping. An unquoted
		// step name here is not a style nit, it is a workflow GitHub refuses to
		// load — TestWorkflowStepNamesAreQuoted is the arm on that.
		p("      - name: %q", workflowStepPrefix+name)
		p("        run: |")
		for _, line := range strings.Split(strings.TrimRight(script, "\n"), "\n") {
			if line == "" {
				p("")
				continue
			}
			p("          %s", line)
		}
		p("")
	}

	// 1. MINT. POST /v1/sites/:id/deploy {"source":"prebuilt"} answers 201 with
	// the deployment row; build_id is what the bytes must carry.
	step("mint a prebuilt deployment", `set -euo pipefail
: "${BARKPARK_CLOUD_TOKEN:?set the BARKPARK_CLOUD_TOKEN repo secret to a PAT with the deploy ability}"
resp="$(curl -sS --fail-with-body -X POST \
  -H "Authorization: Bearer $BARKPARK_CLOUD_TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{"source":"prebuilt"}' \
  "$BARKPARK_API/v1/sites/$BARKPARK_SITE/deploy")"
deployment_id="$(printf '%s' "$resp" | jq -r '.deployment.id // ""')"
build_id="$(printf '%s' "$resp" | jq -r '.deployment.build_id // ""')"
content_rev="$(printf '%s' "$resp" | jq -r '.deployment.content_rev // ""')"
if [ -z "$deployment_id" ] || [ -z "$build_id" ]; then
  echo "the control plane minted no build_id — nothing to stamp the bytes with, so the upload would be rejected at HEALTH" >&2
  printf '%s\n' "$resp" >&2
  exit 1
fi
echo "minted deployment $deployment_id (build $build_id)"
# The build MUST see these: HEALTH asserts bp-build-id by VALUE, and
# BARKPARK_SITE_BASE is a PATH (an absolute URL here 404s every asset href).
{
  echo "BARKPARK_DEPLOYMENT_ID=$deployment_id"
  echo "BARKPARK_BUILD_ID=$build_id"
  echo "BARKPARK_CONTENT_REV=$content_rev"
  echo "BARKPARK_SITE_BASE=/sites/$BARKPARK_SITE/"
} >> "$GITHUB_ENV"`)

	// 2. BUILD, with the minted ids in the environment, and verify the marker
	// landed — the same check runCloudSitePrebuiltDeploy makes before it packs.
	step("build with the minted ids exported", `set -euo pipefail
env -u BARKPARK_TOKEN sh -c "$BARKPARK_BUILD_CMD"
if [ ! -f "$BARKPARK_DIST/index.html" ]; then
  echo "$BARKPARK_DIST/index.html does not exist — BARKPARK_DIST does not point at the build output" >&2
  exit 1
fi
marker="$(sed -n 's/.*name=["'"'"']bp-build-id["'"'"'][^>]*content=["'"'"']\([^"'"'"']*\).*/\1/p' "$BARKPARK_DIST/index.html" | head -n1)"
if [ "$marker" != "$BARKPARK_BUILD_ID" ]; then
  echo "$BARKPARK_DIST/index.html carries build id '${marker:-(none)}', not the '$BARKPARK_BUILD_ID' this deployment minted." >&2
  echo "HEALTH asserts that marker by value, so these bytes would be rejected on the box." >&2
  echo "Your framework adapter must bake <meta name=\"bp-build-id\" content=\"\$BARKPARK_BUILD_ID\"> into <head>." >&2
  exit 1
fi`)

	// 3. UPLOAD. --data-binary @file sends a REAL Content-Length, which is the
	// whole reason the artifact is written to disk before the connection opens:
	// the size and the digest both exist before the first byte travels.
	step("upload the artifact", `set -euo pipefail
art="${RUNNER_TEMP:-/tmp}/barkpark-artifact.tar.gz"
# The archive ROOT is the dist directory: index.html lands at the root with no
# dist/ prefix, because the box extracts it straight into the release dir.
# The dotenv family is excluded — a secret a framework wrote next to the assets
# must never travel. A symlink is refused by the box (a staged symlink is SERVED).
tar --exclude='.git' --exclude='.DS_Store' --exclude='.env' --exclude='.env.*' \
  -czf "$art" -C "$BARKPARK_DIST" .
if command -v sha256sum >/dev/null 2>&1; then
  sha="$(sha256sum "$art" | awk '{print $1}')"
else
  sha="$(shasum -a 256 "$art" | awk '{print $1}')"
fi
echo "packed $BARKPARK_DIST — sha256 $sha"
up="$(curl -sS --fail-with-body -X POST \
  -H "Authorization: Bearer $BARKPARK_CLOUD_TOKEN" \
  -H 'Content-Type: application/octet-stream' \
  -H "X-Artifact-Sha256: $sha" \
  --data-binary "@$art" \
  "$BARKPARK_API/v1/sites/$BARKPARK_SITE/deployments/$BARKPARK_DEPLOYMENT_ID/artifact")"
stored="$(printf '%s' "$up" | jq -r '.artifact_sha256 // ""')"
# The box re-verifies against the CONTROL PLANE's digest, not ours — a silent
# divergence would make every downstream check agree on the wrong bytes.
if [ -n "$stored" ] && [ "$stored" != "$sha" ]; then
  echo "the control plane stored sha256 $stored for this deployment, but these bytes hash to $sha" >&2
  exit 1
fi`)

	// 4. FOLLOW. Poll the deployment until a terminal status; anything but
	// "live" fails the job, so a red deploy is a red build.
	step("follow the deploy", `set -euo pipefail
deadline=$(( $(date +%s) + 900 ))
while :; do
  dep="$(curl -sS --fail-with-body \
    -H "Authorization: Bearer $BARKPARK_CLOUD_TOKEN" \
    "$BARKPARK_API/v1/sites/$BARKPARK_SITE/deployments/$BARKPARK_DEPLOYMENT_ID")"
  status="$(printf '%s' "$dep" | jq -r '.deployment.status // ""')"
  echo "  $status"
  case "$status" in
    live)
      printf '%s' "$dep" | jq -r '"live at " + (.deployment.url // "(no url)")'
      exit 0
      ;;
    failed|cancelled|canceled|deferred)
      echo "deploy ended $status" >&2
      printf '%s\n' "$dep" >&2
      exit 1
      ;;
  esac
  if [ "$(date +%s)" -ge "$deadline" ]; then
    echo "deploy did not reach a terminal status within 15 minutes (last: ${status:-unknown})" >&2
    exit 1
  fi
  sleep 5
done`)

	return strings.TrimRight(b.String(), "\n")
}

// runMakeWorkflow is `bp make workflow <site> [--dist <dir>] [--branch <name>]
// [--out <file>]`. A PURE local builder, like `bp make schema`: no network, no
// manifest, no credential read.
func runMakeWorkflow(out *writer, args []string) int {
	o := workflowOptions{}
	outFile := ""
	i := 1
	for i < len(args) {
		a := args[i]
		key, inlineVal, hasInline := splitFlagToken(a)
		switch key {
		case "--out", "--dist", "--branch":
			v, ni, err := flagValue(args, i, inlineVal, hasInline, key)
			if err != nil {
				return usageErrf(out, func() { usageMake(out, false) }, "%v", err)
			}
			switch key {
			case "--out":
				outFile = v
			case "--dist":
				o.Dist = v
			case "--branch":
				o.Branch = v
			}
			i = ni
		default:
			if strings.HasPrefix(a, "-") && a != "-" {
				return usageErrf(out, func() { usageMake(out, false) }, "unknown make flag %q", a)
			}
			if o.Site == "" {
				o.Site = a
			} else {
				return usageErrf(out, func() { usageMake(out, false) }, "too many arguments; usage: bp make workflow <site>")
			}
			i++
		}
	}

	if o.Site == "" {
		out.userErr("make workflow needs a <site> — the slug you deploy (e.g. bp make workflow my-site)")
		usageMake(out, false)
		return exitUsage
	}
	if err := validateSiteSlugArg(o.Site); err != nil {
		out.userErr("%v", err)
		return exitUsage
	}

	yaml := renderDeployWorkflow(o)
	if outFile != "" {
		if werr := os.WriteFile(outFile, []byte(yaml+"\n"), 0o644); werr != nil {
			out.userErr("write %q: %v", outFile, werr)
			return exitGeneric
		}
		out.errf("wrote the %s deploy workflow to %s", o.Site, outFile)
		return exitOK
	}
	out.outf("%s", yaml)
	return exitOK
}

// validateSiteSlugArg keeps a shell metacharacter or a path segment out of a
// value that is pasted into a YAML env block and then interpolated into a URL.
// The site ref is a slug or a uuid in every path that reaches the deploy routes.
func validateSiteSlugArg(v string) error {
	for _, r := range v {
		ok := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '-' || r == '_'
		if !ok {
			return fmt.Errorf("site %q must be a slug or id ([A-Za-z0-9-_]) — it is pasted into a workflow env block and interpolated into a URL", v)
		}
	}
	return nil
}
