defmodule Barkpark.Tasks.Edges do
  @moduledoc """
  W7a step 2 — typed dependency graph (CRUD over `task_edges`), extracted
  from `Barkpark.Tasks` (behaviour-preserving facade split).

  Owns the edge read/write surface: `add_dep/3`, `remove_dep/3`,
  `dependencies/2`, `dependents/2`, `edges/2`, and `edge_kinds/0`. The
  ready-queue's inline `NOT EXISTS` blocker subquery still lives in
  `Barkpark.Tasks` (it reads the `Edge` schema directly); everything else
  routes through here. `Barkpark.Tasks` `defdelegate`s the public functions.
  """

  import Ecto.Query, only: [from: 2]

  alias Barkpark.Content.Document
  alias Barkpark.Repo
  alias Barkpark.Tasks.Edge

  @doc """
  Edge kinds in this codebase today. `blocks` is the ready-query primitive;
  `discovered-from` records walk-back / derivation lineage between tasks.
  """
  @spec edge_kinds() :: [String.t()]
  def edge_kinds, do: Edge.kinds()

  @doc """
  Add a dependency edge: `child` blocks on `parent`.

  The FIRST argument depends on the SECOND. The edge is stored as
  `from_id = child_id, to_id = parent_id`
  so the W7-03 ready query can scan a candidate's outbound `blocks` edges
  to find its blockers.

  ## Arguments
    * `child`  — the dependent document (the task that's blocked on
      something): the `%Document{}` the caller resolved, or its binary_id.
    * `parent` — the blocker document, same two shapes.
    * `kind`   — `:blocks` (default), `:"discovered-from"`, or the
      string form `"blocks"` / `"discovered-from"`. Other strings are
      rejected by the changeset.

  ## Endpoint shape decides canonicalisation

  Pass the `%Document{}` structs and a `drafts.<id>` endpoint is swapped for
  its same-scope PUBLISHED twin (see `canonical_endpoint/1`). Pass a bare
  uuid and it is stored AS GIVEN — no twin lookup, and no read of any kind:
  this function never fetches a document by primary key, because a by-PK
  read carries no tenant clause and the only thing it could learn (the row's
  scope) is what the caller already holds in the struct
  (`scripts/tenant-scope-check.sh`, `by-pk-document-get`). The one production
  writer, `TasksController.add_edge/2`, resolves both endpoints through the
  scoped `find_task_by_doc_id` pre-flight and passes the structs.

  ## Idempotency

  Re-adding the same `(from, to, kind)` triple is a no-op — the migration's
  unique index plus `on_conflict: :nothing` swallows the duplicate without
  raising. The returned `{:ok, edge}` carries the EXISTING edge when the
  insert was a no-op (fetched in a second query so callers always get a
  populated struct).

  Returns `{:ok, %Edge{}}` on success, `{:error, %Ecto.Changeset{}}` on
  validation failure (missing FK target, self-edge, unknown kind).
  """
  @type endpoint :: Document.t() | binary()

  @spec add_dep(endpoint(), endpoint(), atom() | String.t()) ::
          {:ok, Edge.t()} | {:error, Ecto.Changeset.t()}
  def add_dep(child, parent, kind \\ :blocks) do
    kind_str = normalize_kind(kind)

    # TWIN-EDGE CANONICALISATION (task-85bba5cb33dbd59b).
    #
    # `task_edges` FKs reference `documents.id` — a PER-ROW uuid — so an edge
    # binds to ONE twin. The ready query's twin-collapse axis then surfaces the
    # PUBLISHED row, so a `blocks` edge filed onto the DRAFT twin's uuid did not
    # gate the row anybody can actually claim: a blocker that silently does not
    # block. `queue.ex` documents the gap and names this cure — "canonicalizing
    # edge endpoints to the published uuid is the real fix".
    #
    # WHY THE WRITE PATH AND NOT THE READ. The read fix would mean joining both
    # endpoints through doc_id/published_id inside the ready query, and that
    # query's own moduledoc records what that costs when it goes wrong there: a
    # CTE form that removed 1,320,188 rows by a join filter on a 12k corpus, and
    # a `NOT EXISTS` the planner flattens into an anti-join priced at 25 ms on a
    # custom plan and 2.5 s on the GENERIC plan pooled connections settle into.
    # This path is COLD — once per edge — and normalising here leaves the hot
    # query byte-identical.
    #
    # ONE CHOKEPOINT, verified rather than assumed: every task-edge writer
    # reaches this function (`Tasks.add_dep/4` -> `Fence.add_dep/4` -> here).
    # `Barkpark.Content.Edges` writes a DIFFERENT table.
    child_id = canonical_endpoint(child)
    parent_id = canonical_endpoint(parent)

    attrs = %{from_id: child_id, to_id: parent_id, kind: kind_str}
    changeset = Edge.changeset(%Edge{}, attrs)

    if changeset.valid? do
      # `on_conflict: :nothing` + the unique index = idempotent insert.
      # When the row already exists Postgres skips the INSERT but Ecto still
      # returns `{:ok, %Edge{}}` with the changeset's would-be values (the
      # `id` is the autogenerated one Ecto stamped on the cast struct, NOT
      # the existing row's id). To return the canonical edge — same id on
      # repeat calls — we always read the row back by its unique tuple.
      case Repo.insert(changeset,
             on_conflict: :nothing,
             conflict_target: [:from_id, :to_id, :kind]
           ) do
        {:ok, %Edge{}} ->
          {:ok, fetch_edge!(child_id, parent_id, kind_str)}

        {:error, %Ecto.Changeset{} = cs} ->
          {:error, cs}
      end
    else
      {:error, changeset}
    end
  end

  @doc """
  Remove the `(child_id, parent_id, kind)` edge. Always returns `:ok` —
  removing an absent edge is a no-op, keeping the close-time
  `unblock_dependents` flow simple in W7-04.
  """
  @spec remove_dep(binary(), binary(), atom() | String.t()) :: :ok
  def remove_dep(child_id, parent_id, kind) do
    kind_str = normalize_kind(kind)

    from(e in Edge,
      where: e.from_id == ^child_id and e.to_id == ^parent_id and e.kind == ^kind_str
    )
    |> Repo.delete_all()

    :ok
  end

  @doc """
  The documents `task_id` depends on — the blockers, the `to_id` side of
  every outbound edge. The W7-03 ready query is a `NOT EXISTS` over this
  set; this function is the higher-level read for orchestrator surfaces
  (build pre-flight and dependency inspection).

  ## Options
    * `:kind` — filter to one kind (atom or string). Default: `:blocks`.
      Pass `:all` to return edges of every kind.

  Returns a list of `%Document{}` in insertion order of the edge.
  """
  @spec dependencies(binary(), keyword()) :: [Document.t()]
  def dependencies(task_id, opts \\ []) do
    kind_opt = Keyword.get(opts, :kind, :blocks)

    from(d in Document,
      join: e in Edge,
      as: :edge,
      on: e.to_id == d.id,
      where: e.from_id == ^task_id,
      order_by: e.inserted_at,
      select: d
    )
    |> maybe_filter_edge_kind(kind_opt)
    |> Repo.all()
  end

  @doc """
  The documents that depend on `task_id` — the dependents, the `from_id`
  side of every inbound edge. Called when `task_id` closes, to find which
  rows might be newly ready (the W7-04 close→unblock sweep).

  ## Options
    * `:kind` — filter to one kind (atom or string). Default: `:blocks`.
      Pass `:all` to return edges of every kind.
  """
  @spec dependents(binary(), keyword()) :: [Document.t()]
  def dependents(task_id, opts \\ []) do
    kind_opt = Keyword.get(opts, :kind, :blocks)

    from(d in Document,
      join: e in Edge,
      as: :edge,
      on: e.from_id == d.id,
      where: e.to_id == ^task_id,
      order_by: e.inserted_at,
      select: d
    )
    |> maybe_filter_edge_kind(kind_opt)
    |> Repo.all()
  end

  @doc """
  Low-level query: every edge touching `task_id` on either side.

  ## Options
    * `:direction` — `:outbound` (default — `from_id == task_id`),
      `:inbound` (`to_id == task_id`), or `:both`.
    * `:kind` — filter to one kind (atom or string), or `:all` (default).
  """
  @spec edges(binary(), keyword()) :: [Edge.t()]
  def edges(task_id, opts \\ []) do
    direction = Keyword.get(opts, :direction, :outbound)
    kind_opt = Keyword.get(opts, :kind, :all)

    base =
      case direction do
        :outbound ->
          from(e in Edge, as: :edge, where: e.from_id == ^task_id)

        :inbound ->
          from(e in Edge, as: :edge, where: e.to_id == ^task_id)

        :both ->
          from(e in Edge,
            as: :edge,
            where: e.from_id == ^task_id or e.to_id == ^task_id
          )
      end

    base
    |> maybe_filter_edge_kind(kind_opt)
    |> Repo.all()
  end

  defp maybe_filter_edge_kind(query, :all), do: query

  defp maybe_filter_edge_kind(query, kind) do
    kind_str = normalize_kind(kind)
    from([edge: e] in query, where: e.kind == ^kind_str)
  end

  # The caller may pass `:blocks` / `:"discovered-from"` / `"blocks"` /
  # `"discovered-from"` — internally we always use the string column value.
  defp normalize_kind(kind) when is_atom(kind), do: Atom.to_string(kind)
  defp normalize_kind(kind) when is_binary(kind), do: kind

  defp fetch_edge!(from_id, to_id, kind) do
    Repo.one!(
      from(e in Edge,
        where: e.from_id == ^from_id and e.to_id == ^to_id and e.kind == ^kind
      )
    )
  end

  # Resolve an endpoint to its CANONICAL twin's uuid: if the document is a
  # `drafts.<id>` shadow and a published `<id>` exists in the SAME scope
  # (type + dataset + workspace + project), return the published row's uuid.
  #
  # Everything else is returned UNCHANGED — a row that is already published,
  # and a draft with NO published twin. That last case is deliberate: an
  # unpaired draft is admitted to the ready queue AS ITSELF (queue.ex axis 3
  # suppresses a draft only when a published twin exists), so its edges must
  # keep binding to it or the blocker would vanish entirely.
  #
  # The scope the twin lookup needs comes off the STRUCT the caller resolved.
  # This clause never reads the endpoint back by primary key: `Repo.get(
  # Document, id)` has no tenant clause, and every production caller already
  # holds the row (task-8f9d3ea8926f387f). A bare uuid therefore takes the
  # last clause and is stored as given — canonicalisation is something the
  # caller opts into by handing over the document, not something this module
  # can recover from an id alone.
  defp canonical_endpoint(%Document{id: id, doc_id: doc_id} = doc) do
    with true <- String.starts_with?(doc_id, "drafts."),
         published_id <- String.replace_prefix(doc_id, "drafts.", ""),
         %Document{id: canonical} <- fetch_twin(doc, published_id) do
      canonical
    else
      _ -> id
    end
  end

  defp canonical_endpoint(id), do: id

  # The twin lookup is scoped on every axis the uniqueness index carries, so a
  # same-slug row in ANOTHER dataset or another tenant can never be adopted as
  # this row's twin. `limit: 1` because `(doc_id, type, dataset_id)` is unique
  # and a bare `Repo.one/1` here would raise on the one shape that is supposed
  # to be impossible — the same fork that made `bp task claim` 500
  # (task-ca05dd6a02a0b55f).
  defp fetch_twin(%Document{} = doc, published_id) do
    from(d in Document,
      where:
        d.doc_id == ^published_id and d.type == ^doc.type and
          d.dataset == ^doc.dataset,
      limit: 1
    )
    |> scope_twin(:workspace_id, doc.workspace_id)
    |> scope_twin(:project_id, doc.project_id)
    |> Repo.one()
  end

  defp scope_twin(query, field, nil),
    do: from(d in query, where: is_nil(field(d, ^field)))

  defp scope_twin(query, field, value),
    do: from(d in query, where: field(d, ^field) == ^value)

  @doc """
  Re-point every existing `task_edges` endpoint that binds a DRAFT twin at the
  PUBLISHED twin of the same slug, and return `%{from: {moved, deduped}, to:
  {moved, deduped}}`.

  `add_dep/3` canonicalises NEW edges; this repairs the ones written before it.
  It lives HERE rather than inside the migration for two reasons: a migration
  body needs a runner process and so cannot be driven from a test, and an
  operator needs a re-runnable arm for edges written by an older release still
  in flight. Migration
  `20260905160000_backfill_twin_canonical_task_edges` is a thin caller.

  IDEMPOTENT: after a run there are no draft-bound endpoints left with a
  published twin, so a second run matches nothing.

  COLLISIONS ARE DELETED, NOT UPDATED, and the ordering is the trick.
  `task_edges` is unique on `(from_id, to_id, kind)`. If the canonical edge
  already exists, re-pointing its draft-bound sibling onto the same triple would
  violate that index and abort the whole run — so each side DELETEs the
  redundant row FIRST and only then UPDATEs what remains. The deleted row is not
  lost information; it is the same dependency stated twice.

  SET-BASED, never per-row (slow-migration law): two DELETEs and two UPDATEs in
  total, whatever the corpus size.
  """
  @spec backfill_twin_canonical_edges() :: %{
          from: {integer(), integer()},
          to: {integer(), integer()}
        }
  def backfill_twin_canonical_edges do
    from_deduped = delete_colliding_from_edges()
    from_moved = repoint_from_edges()
    to_deduped = delete_colliding_to_edges()
    to_moved = repoint_to_edges()

    %{from: {from_moved, from_deduped}, to: {to_moved, to_deduped}}
  end

  # ── FOUR LITERAL STATEMENTS, NOT ONE INTERPOLATED PAIR ──────────────────
  #
  # An earlier shape built these from `side`/`other` variables interpolated
  # into the SQL string. It was safe — both were internal column atoms, never
  # caller input — but Sobelow's SQL.Query check cannot see that, and it read
  # the interpolation as two NEW Low findings on `api/lib/barkpark/tasks/edges.ex`
  # (`variable "side and side"`, `variable "side and side and other and other"`),
  # which reddened the required Security gate.
  #
  # The fix is at the cause rather than a baseline waiver: `from_id` and `to_id`
  # are a closed set of two, so the four statements are written out in full and
  # NO variable reaches any SQL string. A waiver would have asked every future
  # reader to re-derive that `side` is uninterpolatable; four literals ask
  # nothing. The duplication is four lines of WHERE clause, which is cheaper
  # than a fingerprint in a baseline file.
  #
  # THE SHARED PREDICATE, spelled once here and repeated verbatim below:
  # `LIKE 'drafts.%'` confines the join to shadow rows; `substring(d.doc_id
  # from 8)` strips the literal "drafts." (7 chars, so the remainder starts at
  # 8); the join is scoped on every axis the `(doc_id, type, dataset_id)`
  # uniqueness index carries, with `IS NOT DISTINCT FROM` so an untenanted row
  # matches only another untenanted row — a looser join would silently move a
  # blocker across a tenancy boundary, which is worse than the unenforced
  # blocker being fixed. An UNPAIRED draft finds no published row and is left
  # alone, which queue.ex axis 3 requires: it serves such a draft as itself, so
  # its edges must keep pointing at it.

  defp delete_colliding_from_edges do
    %{num_rows: n} =
      Repo.query!("""
      DELETE FROM task_edges e
      USING documents d, documents pub
      WHERE e.from_id = d.id
        AND d.doc_id LIKE 'drafts.%'
        AND pub.doc_id = substring(d.doc_id from 8)
        AND pub.type = d.type
        AND pub.dataset = d.dataset
        AND pub.workspace_id IS NOT DISTINCT FROM d.workspace_id
        AND pub.project_id IS NOT DISTINCT FROM d.project_id
        AND EXISTS (
          SELECT 1 FROM task_edges c
          WHERE c.from_id = pub.id
            AND c.to_id = e.to_id
            AND c.kind = e.kind
        )
      """)

    n
  end

  defp delete_colliding_to_edges do
    %{num_rows: n} =
      Repo.query!("""
      DELETE FROM task_edges e
      USING documents d, documents pub
      WHERE e.to_id = d.id
        AND d.doc_id LIKE 'drafts.%'
        AND pub.doc_id = substring(d.doc_id from 8)
        AND pub.type = d.type
        AND pub.dataset = d.dataset
        AND pub.workspace_id IS NOT DISTINCT FROM d.workspace_id
        AND pub.project_id IS NOT DISTINCT FROM d.project_id
        AND EXISTS (
          SELECT 1 FROM task_edges c
          WHERE c.to_id = pub.id
            AND c.from_id = e.from_id
            AND c.kind = e.kind
        )
      """)

    n
  end

  defp repoint_from_edges do
    %{num_rows: n} =
      Repo.query!("""
      UPDATE task_edges e
      SET from_id = pub.id
      FROM documents d, documents pub
      WHERE e.from_id = d.id
        AND d.doc_id LIKE 'drafts.%'
        AND pub.doc_id = substring(d.doc_id from 8)
        AND pub.type = d.type
        AND pub.dataset = d.dataset
        AND pub.workspace_id IS NOT DISTINCT FROM d.workspace_id
        AND pub.project_id IS NOT DISTINCT FROM d.project_id
      """)

    n
  end

  defp repoint_to_edges do
    %{num_rows: n} =
      Repo.query!("""
      UPDATE task_edges e
      SET to_id = pub.id
      FROM documents d, documents pub
      WHERE e.to_id = d.id
        AND d.doc_id LIKE 'drafts.%'
        AND pub.doc_id = substring(d.doc_id from 8)
        AND pub.type = d.type
        AND pub.dataset = d.dataset
        AND pub.workspace_id IS NOT DISTINCT FROM d.workspace_id
        AND pub.project_id IS NOT DISTINCT FROM d.project_id
      """)

    n
  end
end
