defmodule BarkparkWeb.Studio.InspectorSummonedDestinationTest do
  @moduledoc """
  studio-space-priority-desk successor `inspector-narrow-destination-surface` —
  the summoned destination, and the abolition of dimming underneath it.

  ## What this file locks

  At `narrow` and `phone` a user-opened Document inspector becomes a
  DESTINATION at the full width of the content pane, and the overlay scrim
  renders in ZERO rows for that state. Both halves need locking for the same
  reason: neither is observable by any other test in this suite.

  The geometry half is a plain literal pin, same idiom as
  `wide_geometry_lock_test.exs` — expectations are hardcoded strings copied out
  of the stylesheet, never values re-derived from it. A pin that reads its own
  subject cannot fail from the only thing it purports to guard (charter D94).

  The scrim half CANNOT be a literal pin, and that is the whole difficulty.
  "The scrim does not render" is not a property of any one rule: the scrim is
  generated by a `::after` inside `@container panel (max-width: 860px)` and
  suppressed by later rules with `content: none` — the b29 guard, D170's wide
  kill switch, the narrow/phone destination rules, and the D175 standard
  suppressor — so the honest question is which declaration WINS for a given
  desk state. Asserting "a suppression rule
  exists" would go green against a suppression that never matches — the exact
  vacuity this epic has been bitten by twice (charter D39/D40: two measure
  criteria declared met on floors that had never once applied).

  So this file evaluates a CASCADE. It parses every scrim rule out of the
  sheet, derives each one's matching CONDITIONS from the selector text itself
  (never from a hand-written expectation), and computes the winning `content`
  value for a modelled desk state. The conditions come from the sheet, so a
  rule whose scope changes changes what this test concludes.

  ### The model's limits, stated

  ExUnit has no CSS engine. The specificity comparison here counts class and
  attribute tokens across the whole selector, including inside `:not()` and
  `:has()` — which is exactly the real rule for both, since every argument in
  this sheet is a single compound selector. Every scrim rule carries the same
  `::after` pseudo-element and no id selectors, so ordering by that count is
  faithful for this rule set and would need revisiting if an id or a
  multi-compound `:has()` ever landed here. Ties break on source order, as CSS
  does.

  ### Non-vacuity, and the mutation control

  Two guards keep the verdict from being free:

    * every "no scrim" row asserts that the scrim-GENERATING rule genuinely
      matched that state first. "No scrim because nothing matched" is not the
      claim being made; "no scrim because the suppression beat the generator"
      is.
    * `the suppression is what abolishes it` deletes the new rule from the
      source string and re-runs the identical evaluation, asserting the scrim
      comes back. The mutation is run in-process so the guarantee does not
      depend on anyone repeating it by hand.

  This slice OWNS `root.html.heex` this round (D16/D160). It stays file-disjoint
  from `wide_geometry_lock_test.exs` and `measure_parity_test.exs`; the small
  parsing helpers below are duplicated on purpose rather than shared, so this
  lock cannot be weakened by an edit aimed at either of those files.
  """
  use ExUnit.Case, async: true

  @moduletag :studio_summoned_destination

  @root Path.expand("../../../lib/barkpark_web/layouts/root.html.heex", __DIR__)

  # The two bucket-scoped selectors this slice added, verbatim.
  @narrow ~S|html[data-width-bucket="narrow"] .bp-doc-sidebar.is-open[data-user-opened]|
  @phone ~S|html[data-width-bucket="phone"] .bp-doc-sidebar.is-open[data-user-opened]|

  # The Tier-3 exit (D167) — the same two buckets, the same `[data-user-opened]`
  # qualifier, applied to the one control that closes the destination.
  @narrow_exit @narrow <> " .bp-doc-sidebar__collapse"
  @phone_exit @phone <> " .bp-doc-sidebar__collapse"

  describe "the summoned destination takes the whole content pane" do
    test "narrow and phone are declared together and carry full-pane geometry" do
      block = block!([@narrow, @phone])

      # `absolute` + `inset: 0` against `.editor-panel`'s `position: relative`
      # IS "the full width of the content pane" — the pane is the containing
      # block, so the panel's box is the pane's box.
      assert value!(block, "position") == "absolute"

      assert value!(block, "inset") == "0",
             """
             The summoned inspector no longer fills its containing block.

             `inset: 0` against `.editor-panel`'s `position: relative` is what
             makes this a DESTINATION rather than a wider overlay. The whole
             argument for it (charter D113) is that at these widths there is no
             split of the pane in which the document survives: a 300px dock at
             viewport 800 leaves the reader 376px against the overlay's measured
             396.9px. Partially covering the pane re-opens exactly that.
             """

      assert value!(block, "width") == "auto",
             """
             A width is back on the summoned panel.

             The `@container panel (max-width: 860px)` block sets `width: 300px`
             on `.bp-doc-sidebar.is-open`. This rule must neutralise it, or the
             destination is a 300px overlay again with `inset: 0` fighting it.
             """

      # The overlay block raises this and z-index applies whatever the
      # position, so it is restated rather than inherited by luck.
      assert value!(block, "z-index") == "5"

      # Nothing shows through to cast a shadow onto, and nothing sits beside
      # the border.
      assert value!(block, "box-shadow") == "none"
      assert value!(block, "border-left") == "0"
    end

    test "the rule is bucket-scoped: it cannot match at wide or standard" do
      block = block!([@narrow, @phone])
      refute block == nil

      for bucket <- ~w(wide standard) do
        refute String.contains?(@narrow <> @phone, ~s|data-width-bucket="#{bucket}"|),
               """
               The summoned-destination rule names the `#{bucket}` bucket.

               At `wide` the inspector docks and costs the reader nothing — epic
               criterion 2 is measured there and the round-2 floor slice takes
               its input from those rows, so this rule may not move one pixel
               there (charter D92). `standard` is ruled by its own SCRIM
               suppressor (D175) — its inspector still docks, so the
               destination geometry may not reach it either.
               """
      end
    end

    test "the b29/D91 default rules are UNTOUCHED and still carve this state out" do
      src = decommented(css())

      # Both halves of the painted-closed default still exempt the asked-for
      # panel. If either lost its carve-out, the default would start fighting
      # the destination rule instead of yielding to it.
      assert src =~
               ~S|html:not([data-width-bucket="wide"]) .bp-doc-sidebar.is-open:not([data-user-opened])|,
             "the b29/D91 geometry default lost its `:not([data-user-opened])` carve-out"

      assert src =~
               ~S|.editor-with-preview:has(.bp-doc-sidebar.is-open:not([data-user-opened]))::after|,
             "the b29/D91 scrim guard lost its `:not([data-user-opened])` carve-out"
    end

    test "the Tier-3 exit is a 44px touch target, scoped so no docked tier can reach it" do
      # The exit earns its own lock because the destination is useless without
      # it: at Tier 3 the panel covers 100% of the content pane, so this button
      # is the ONLY way back to the document. Un-tripwired it regressed to a
      # 16x16 icon box — under every touch-target floor there is — and nothing
      # in this file noticed.
      block = block!([@narrow_exit, @phone_exit])

      assert value!(block, "min-width") == "44px"
      assert value!(block, "min-height") == "44px"

      # Without this the 16px glyph sits at the flex-start edge of its new 44px
      # box and the visual mark is 14px from where the finger is aimed.
      assert value!(block, "justify-content") == "center"

      # DISJOINT FROM THE PAINTED-CLOSED STRIP BY CONSTRUCTION. The strip is
      # `.is-open:not([data-user-opened])`; this rule requires
      # `[data-user-opened]`. No element satisfies both, so the strip's own 16px
      # button — and every docked tier — is structurally unreachable from here.
      # That is what lets a 44px minimum ship without moving a docked pixel.
      for sel <- [@narrow_exit, @phone_exit] do
        assert String.contains?(sel, "[data-user-opened]"),
               "the Tier-3 exit lost its `[data-user-opened]` qualifier — it can now " <>
                 "reach the painted-closed strip, whose 16px button is deliberate"
      end

      # And scoped by ENUMERATION, never negation: `:not([data-width-bucket="wide"])`
      # would also catch `standard`, whose inspector still docks.
      refute String.contains?(block!([@narrow_exit, @phone_exit]), "wide")

      for bucket <- ~w(wide standard) do
        refute String.contains?(@narrow_exit <> @phone_exit, ~s|data-width-bucket="#{bucket}"|),
               "the Tier-3 exit reaches the `#{bucket}` bucket, whose inspector docks"
      end
    end

    test "the crumb trail is VISIBLE at narrow, not merely emitted there (D168)" do
      # THE HALF-SHIPPED FEATURE THIS CATCHES. The markup half of D168 widened
      # `desk_crumbs/1` from phone-only to `in ["narrow","phone"]`, so the desk
      # now EMITS a breadcrumb nav at narrow — and that nav carries the document
      # crumb, which is the trail's way back out of the summoned destination.
      # This sheet's rule was written when the trail was a phone-drill
      # affordance and read `.bp-desk-crumbs { display: none }` with a single
      # phone override, so the narrow markup landed inside a `display: none`.
      #
      # A server emitting an escape route no reader can see is worse than not
      # emitting it: the DOM then asserts an affordance the desk does not
      # offer, and AT announces a link out of a trap that does not exist.
      block =
        block!([
          ~S|html[data-width-bucket="narrow"] .bp-desk-crumbs|,
          ~S|html[data-width-bucket="phone"] .bp-desk-crumbs|
        ])

      assert value!(block, "display") == "flex",
             "the narrow crumb trail is emitted by desk_crumbs/1 but not painted by this sheet"

      # And the base rule still hides it everywhere else — the trail is opt-in
      # per bucket, so `standard` and `wide` (whose inspectors dock beside a
      # document that never leaves the screen) keep their unchanged chrome.
      assert value!(block!([".bp-desk-crumbs"]), "display") == "none"
    end

    test "no motion property is introduced on the summoned panel" do
      block = block!([@narrow, @phone])

      for prop <-
            ~w(transition animation transform filter will-change backdrop-filter perspective) do
        refute Regex.match?(~r/(?:^|;)\s*#{prop}\s*:/, block),
               """
               `#{prop}` landed on the summoned-destination rule.

               A fade spends its whole duration painting a translucent panel
               over live prose — a transient re-run of the dimming this slice
               abolishes — and `transform` plants a containing block for fixed
               descendants inside the pane whose containment hazard has its own
               tripwire (`editor_panel_containment_test.exs`). If motion is
               wanted here later it needs a scoped
               `@media (prefers-reduced-motion: reduce)` block that nulls the
               TRANSITION property itself, not merely an animation.
               """
      end
    end
  end

  describe "dimming is ABOLISHED for the summoned state — zero rendered scrims" do
    # Pane widths on both sides of the 860px overlay threshold. `narrow` runs
    # to 1023px, so a desk whose list panes have collapsed to 44px strips
    # really does present a pane wider than 860 inside this bucket — the
    # verdict has to hold in both.
    @pane_widths [700, 900]

    test "narrow + phone, user-opened: the winning `content` is `none` at every pane width" do
      for bucket <- ~w(narrow phone), pane <- @pane_widths do
        state = %{bucket: bucket, user_opened: true, pane: pane}
        matched = matching_scrim_rules(state)

        # NON-VACUITY FIRST. "No scrim because nothing matched" is not the
        # claim; "no scrim because the suppression beat the generator" is.
        assert Enum.any?(matched, fn r -> r.content == ~s|""| end) or pane > 860,
               """
               No scrim-GENERATING rule matches #{bucket}/user-opened at a #{pane}px
               pane, so the "no scrim" verdict below is free.

               The generator is the `::after` inside
               `@container panel (max-width: 860px)`. If it stopped matching,
               this test proves nothing about the suppression that follows it —
               re-derive the row rather than accepting the green.
               """

        assert matched != [], "no scrim rule of any kind matches #{bucket}/#{pane}px"

        assert winning_content(state) == "none",
               """
               THE SCRIM STILL RENDERS at bucket=#{bucket}, pane=#{pane}px, with the
               inspector user-opened.

               The winning `content` is `#{inspect(winning_content(state))}`, so the desk
               paints a 55%-black box over a document that is already completely
               covered by the summoned panel. That is the half-suspended read
               charter D127 ruled a DEFECT: at viewport 1024 the layout metric
               RISES 599->640px while the human LOSES 219px (599->380), and the
               prose is dimmed rather than hidden. Dimming is abolished here,
               not tuned.

               Rules that matched this state, in source order:
               #{inspect(Enum.map(matched, & &1.selector), pretty: true)}
               """
      end
    end

    test "the suppression is what abolishes it — mutation control" do
      # Delete the new suppression rule from the source and re-run the
      # identical evaluation. If the verdict does not flip, the assertion above
      # is not measuring this slice's change.
      mutated =
        Regex.replace(
          ~r/html\[data-width-bucket="narrow"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after,\s*html\[data-width-bucket="phone"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after \{[^}]*\}/,
          decommented(css()),
          ""
        )

      refute mutated == decommented(css()),
             "the mutation matched nothing — the control below is vacuous and the " <>
               "suppression rule has been reshaped without this test noticing"

      state = %{bucket: "narrow", user_opened: true, pane: 700}

      assert winning_content(state, mutated) == ~s|""|,
             """
             With the suppression rule deleted the scrim STILL does not render,
             so something other than this slice is suppressing it and the
             verdict above is not this slice's to claim.
             """
    end

    test "the wide scrim is ABOLISHED too — D170 retires this file's old wide row" do
      # THIS ROW USED TO ASSERT THE OPPOSITE. It read "the scrim is untouched
      # where it is still wanted — wide", on the assumption that a wide pane
      # squeezed under 860px overlays a document that stays visible beside it.
      # Wave-11 measured that assumption and it does not hold: the state is
      # reachable by arithmetic and unreachable in fact. Papers route to a fixed
      # [44,260] shell, so `.editor-panel` is `vw - 304` at every wide viewport —
      # 976 at 1280 and 1136 at 1440, both clear of the 860px generator by more
      # than 100px. The rule dimmed nothing; it only kept a carve-out alive.
      for user_opened <- [true, false] do
        assert winning_content(%{bucket: "wide", user_opened: user_opened, pane: 700}) == "none",
               """
               The wide scrim is back (user_opened=#{user_opened}).

               D170 abolished it unconditionally at `wide`: both a
               server-defaulted and a user-summoned inspector sit in the same
               [44,260] shell, so neither can bring the pane under 860 and
               neither earns a scrim.
               """
      end

      # And the b29 default (below wide, never asked for) stays suppressed —
      # the strip is invisible, so dimming under it was always nonsense.
      assert winning_content(%{bucket: "narrow", user_opened: false, pane: 700}) == "none"
    end

    test "abolishing wide is THIS rule's doing — mutation control" do
      mutated =
        Regex.replace(
          ~r/html\[data-width-bucket="wide"\]\s*\.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\)::after \{[^}]*\}/,
          decommented(css()),
          ""
        )

      refute mutated == decommented(css()),
             "the mutation matched nothing — the wide-abolition control is vacuous"

      assert winning_content(%{bucket: "wide", user_opened: true, pane: 700}, mutated) == ~s|""|,
             """
             With the wide suppression deleted the scrim STILL does not render,
             so the row above is not measuring D170's rule.
             """
    end

    test "standard + user-opened: the D175 compound state is suppressed at every pane width" do
      # THE ONE STATE THE SHEET STILL PAINTED (charter D175/D187). A clean
      # standard desk never crosses the 860px generator — panel = vw - 44
      # crosses 860 only at viewport <= 904, inside `narrow` — but with a
      # 360px secondary pane carried in from a task (`Scope.select/2` is
      # push_patch, so `secondary_doc` survives the navigation), the pane at
      # standard/1024 is 620 = 1024 - 44 - 360 EXACTLY. The generator matched,
      # no suppressor covered standard + [data-user-opened] — b29 excludes
      # user-opened, narrow/phone is bucket-scoped away, D170's is wide-only —
      # and it PAINTED on the deployed build: mean luminance over the reading
      # column 240.493 -> 175.104 (delta 65.389). The exact D127 defect,
      # reached through an orthogonal feature.
      state = %{bucket: "standard", user_opened: true, pane: 620}
      matched = matching_scrim_rules(state)

      # NON-VACUITY FIRST. The generator genuinely matches this state, so the
      # verdict below is "the suppression beat it", never "nothing matched".
      assert Enum.any?(matched, fn r -> r.content == ~s|""| end),
             """
             No scrim-GENERATING rule matches standard/user-opened at a 620px
             pane, so the "no scrim" verdict below is free.

             The generator is the `::after` inside
             `@container panel (max-width: 860px)`. If it stopped matching,
             this test proves nothing about the suppression that follows it —
             re-derive the row rather than accepting the green.
             """

      assert winning_content(state) == "none",
             """
             THE SCRIM STILL RENDERS at bucket=standard, pane=620px, with the
             inspector user-opened and a secondary pane eating the width.

             The winning `content` is `#{inspect(winning_content(state))}`, so the desk
             paints a 55%-black box over prose the reader is actively reading,
             with the inspector genuinely docked beside it — the half-suspended
             read charter D127 ruled a DEFECT, reproduced and photographed on
             the deployed build (D187). Dimming is abolished here, not tuned.

             Rules that matched this state, in source order:
             #{inspect(Enum.map(matched, & &1.selector), pretty: true)}
             """

      # And unbounded by pane width, deliberately: the suppressor sits OUTSIDE
      # the 860px @container, so no pane composition — today's 560px
      # server-default compound, tomorrow's — can slip back under the
      # threshold and re-dim.
      for pane <- [560, 860] do
        assert winning_content(%{state | pane: pane}) == "none",
               "the standard suppressor stopped covering a #{pane}px pane"
      end
    end

    test "suppressing standard is THIS rule's doing — mutation control" do
      # Delete the standard suppressor from the source and re-run the
      # identical evaluation. If the scrim does not come back, the verdict
      # above is not this slice's to claim.
      mutated =
        Regex.replace(
          ~r/html\[data-width-bucket="standard"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after \{[^}]*\}/,
          decommented(css()),
          ""
        )

      refute mutated == decommented(css()),
             "the mutation matched nothing — the control below is vacuous and the " <>
               "standard suppressor has been reshaped without this test noticing"

      assert winning_content(%{bucket: "standard", user_opened: true, pane: 620}, mutated) ==
               ~s|""|,
             """
             With the standard suppressor deleted the scrim STILL does not
             render, so something other than this slice is suppressing the
             D175 compound state and the verdict above is not measuring this
             slice's rule.
             """
    end

    test "THE POSITIVE CONTROL: the generator is live code, not a rule we killed everywhere" do
      # D153's positive control has moved TWICE, each time because a
      # suppression honestly retired its last live row: first off `wide`
      # (D170), then off plain standard/user-opened — the row this test held
      # until the D175 suppressor shipped and flipped BOTH of its old
      # assertions (860: "" -> "none"; 861: nil -> "none", the suppressor
      # being pane-unbounded outside the @container). Every bucket x
      # user-opened state is now suppressed, so no winning-content cell in the
      # live sheet witnesses the generator any more. The honest witness is the
      # FORCED-CONTAINER form D176 mandates, run in-memory: strip ONLY the
      # standard suppressor and exercise the generator's OWN 860px threshold
      # in the one cell that still discriminates it (D176: standard +
      # user-opened is the single discriminating cell; at wide the reading is
      # byte-identical with the generator present and deleted).
      unsuppressed =
        Regex.replace(
          ~r/html\[data-width-bucket="standard"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after \{[^}]*\}/,
          decommented(css()),
          ""
        )

      refute unsuppressed == decommented(css()),
             "the forced-container mutation matched nothing — the witness below is vacuous"

      assert winning_content(%{bucket: "standard", user_opened: true, pane: 860}, unsuppressed) ==
               ~s|""|,
             """
             NOTHING in this sheet generates a scrim any more.

             With the standard suppressor stripped, the generator should have
             this cell to itself and paint. If it does not, every
             `content: none` above is free: the suppressions are not beating a
             generator, they are decorating a dead rule. Re-derive before
             accepting any green in this file.
             """

      # …and one pixel the other side of the generator's own threshold, nothing
      # matches at all — which is what makes the row above a threshold test.
      assert winning_content(%{bucket: "standard", user_opened: true, pane: 861}, unsuppressed) ==
               nil
    end
  end

  describe "negative control — the evaluator itself" do
    test "it finds more than one scrim rule, and reads their conditions" do
      rules = scrim_rules()

      assert length(rules) >= 3,
             """
             Only #{length(rules)} scrim rule(s) parsed out of the sheet.

             There are at least three: the generator inside
             `@container panel (max-width: 860px)`, the b29/D91 guard, and this
             slice's narrow/phone suppression. A parser that sees fewer has
             stopped reading the sheet and every cascade verdict above is
             computed over a fiction.
             """

      assert Enum.any?(rules, &(&1.content == ~s|""|)), "no scrim GENERATOR parsed"
      assert Enum.any?(rules, &(&1.content == "none")), "no scrim SUPPRESSION parsed"

      assert Enum.any?(rules, &(&1.max_pane == 860)),
             "the generator's `@container panel (max-width: 860px)` condition was not read — " <>
               "every pane-width row above is then evaluated without its own threshold"
    end

    test "a zero-match selector fails LOUDLY rather than returning an empty block" do
      assert_raise ExUnit.AssertionError, ~r/no-such-summoned-rule/, fn ->
        block!([".bp-doc-sidebar.no-such-summoned-rule"])
      end
    end

    test "a missing property fails LOUDLY rather than comparing nil" do
      block = block!([@narrow, @phone])

      assert_raise ExUnit.AssertionError, ~r/border-radius/, fn ->
        value!(block, "border-radius")
      end
    end

    test "specificity ordering counts tokens inside :has() and :not()" do
      # Both pseudo-classes take the specificity of their argument, and the
      # cascade verdict above depends on the narrow/phone suppression (a bucket
      # attribute + `.editor-with-preview` + a three-token `:has()`) outranking
      # the generator (`.editor-with-preview` + a two-token `:has()`).
      assert specificity(~S|.editor-with-preview:has(.bp-doc-sidebar.is-open)::after|) == 3

      assert specificity(
               ~S|html[data-width-bucket="narrow"] .editor-with-preview:has(.bp-doc-sidebar.is-open[data-user-opened])::after|
             ) == 5
    end
  end

  # --- the cascade evaluator -------------------------------------------

  # Every rule in the sheet that generates or suppresses the inspector scrim,
  # in source order, with the conditions it imposes DERIVED FROM ITS OWN
  # SELECTOR TEXT. Nothing here is hand-declared: a rule whose scope is edited
  # changes what this evaluator concludes, which is the point.
  defp scrim_rules(source \\ nil) do
    src = source || decommented(css())
    container_spans = container_spans(src)

    ~r/([^{}]*::after)\s*\{([^{}]*)\}/
    |> Regex.scan(src, return: :index)
    |> Enum.map(fn [{_, _}, sel_at, body_at] ->
      {selector, body} = {normalise(slice(src, sel_at)), slice(src, body_at)}
      {sel_start, _} = sel_at
      {selector, body, sel_start}
    end)
    # A comma-separated list is N rules, not one. Keeping it as one chunk would
    # read only the FIRST selector's conditions and silently drop the rest —
    # this slice's suppression is declared `narrow, phone`, so the phone rows
    # would evaluate against a rule that does not exist.
    |> Enum.flat_map(fn {chunk, body, at} ->
      chunk
      |> String.split(",")
      |> Enum.map(&normalise/1)
      |> Enum.reject(&(&1 == ""))
      |> Enum.map(&{&1, body, at})
    end)
    |> Enum.filter(fn {selector, _body, _at} ->
      String.contains?(selector, ".editor-with-preview") and
        String.contains?(selector, ".bp-doc-sidebar.is-open")
    end)
    |> Enum.map(fn {selector, body, at} ->
      %{
        selector: selector,
        content: content_of(body),
        order: at,
        specificity: specificity(selector),
        max_pane: enclosing_max_pane(container_spans, at),
        bucket_is: capture(selector, ~r/html\[data-width-bucket="([a-z]+)"\]/),
        bucket_is_not: capture(selector, ~r/html:not\(\[data-width-bucket="([a-z]+)"\]\)/),
        user_opened: user_opened_condition(selector)
      }
    end)
    |> Enum.sort_by(& &1.order)
  end

  defp user_opened_condition(selector) do
    cond do
      String.contains?(selector, ":not([data-user-opened])") -> false
      String.contains?(selector, "[data-user-opened]") -> true
      true -> :any
    end
  end

  defp matching_scrim_rules(state, source \\ nil) do
    Enum.filter(scrim_rules(source), fn rule ->
      (rule.max_pane == nil or state.pane <= rule.max_pane) and
        (rule.bucket_is == nil or rule.bucket_is == state.bucket) and
        (rule.bucket_is_not == nil or rule.bucket_is_not != state.bucket) and
        (rule.user_opened == :any or rule.user_opened == state.user_opened)
    end)
  end

  # The winner: highest specificity, ties broken by source order — CSS's own
  # rule. Returns the `content` value the browser would compute, or nil when
  # no rule matches at all (in which case there is no `::after` box either).
  defp winning_content(state, source \\ nil) do
    state
    |> matching_scrim_rules(source)
    |> Enum.sort_by(&{&1.specificity, &1.order})
    |> List.last()
    |> case do
      nil -> nil
      rule -> rule.content
    end
  end

  # Class and attribute tokens across the whole selector, INCLUDING inside
  # `:not()` and `:has()` — both take their argument's specificity, and every
  # argument in this sheet is a single compound selector. See the moduledoc for
  # where this stops being faithful.
  defp specificity(selector) do
    length(Regex.scan(~r/\.[A-Za-z][\w-]*/, selector)) +
      length(Regex.scan(~r/\[[^\]]+\]/, selector))
  end

  defp content_of(body) do
    case Regex.run(~r/(?:^|;)\s*content\s*:\s*([^;}]+)/, body, capture: :all_but_first) do
      [value] -> normalise(value)
      _ -> nil
    end
  end

  defp capture(text, regex) do
    case Regex.run(regex, text, capture: :all_but_first) do
      [value] -> value
      _ -> nil
    end
  end

  # `{start, end}` byte spans of every `@container panel (max-width: N)` block,
  # with N — brace-matched, because the 860px block nests a `:has()` rule and a
  # naive scan to the first `}` would truncate it and lose the scrim entirely.
  defp container_spans(src) do
    ~r/@container\s+panel\s*\(\s*max-width:\s*(\d+)px\s*\)\s*\{/
    |> Regex.scan(src, return: :index)
    |> Enum.map(fn [{match_start, match_len}, n_at] ->
      open_at = match_start + match_len - 1
      {open_at, balanced_end(src, open_at + 1, 1), String.to_integer(slice(src, n_at))}
    end)
  end

  defp enclosing_max_pane(spans, at) do
    spans
    |> Enum.filter(fn {open_at, close_at, _n} -> at > open_at and at < close_at end)
    |> Enum.map(fn {_o, _c, n} -> n end)
    |> case do
      [] -> nil
      widths -> Enum.min(widths)
    end
  end

  defp balanced_end(src, i, depth) do
    case :binary.at(src, i) do
      ?{ -> balanced_end(src, i + 1, depth + 1)
      ?} when depth == 1 -> i
      ?} -> balanced_end(src, i + 1, depth - 1)
      _ -> balanced_end(src, i + 1, depth)
    end
  end

  # --- parsing ---------------------------------------------------------

  defp css, do: File.read!(@root)

  # Comments first: this sheet's design prose quotes nearly every selector and
  # value below it, and a pin satisfiable by a comment is not a pin.
  defp decommented(src), do: Regex.replace(~r|/\*.*?\*/|s, src, "")

  defp slice(src, {at, len}), do: binary_part(src, at, len)

  # The one declaration block whose selector list is EXACTLY these selectors,
  # in this order. Zero matches raises here, naming them, rather than returning
  # an empty block that every assertion below passes against vacuously.
  defp block!(selectors) do
    esc = selectors |> Enum.map(&Regex.escape/1) |> Enum.join(~S|,\s*|)

    case Regex.scan(~r/(?:^|\})\s*#{esc}\s*\{([^{}]*)\}/, decommented(css()),
           capture: :all_but_first
         ) do
      [[one]] ->
        one

      [] ->
        flunk("""
        SELECTOR LIST MATCHED ZERO RULES:

        #{Enum.join(selectors, ",\n")}

        root.html.heex declares no rule with that selector list. Nothing below
        can be trusted — comparisons against an empty block pass vacuously,
        which is how this epic declared a measure criterion met twice on floors
        that had never once applied (charter D39/D40). Either the rule was
        renamed (repoint this constant and say so) or it was deleted, in which
        case the geometry it carried is GONE and that is the bug.
        """)

      many ->
        flunk(
          "that selector list now has #{length(many)} rules — the winner is source-order dependent"
        )
    end
  end

  defp value!(block, prop) do
    case Regex.scan(~r/(?:^|;)\s*#{Regex.escape(prop)}\s*:\s*([^;}]+)/, block,
           capture: :all_but_first
         ) do
      [[one]] ->
        normalise(one)

      [] ->
        flunk("the summoned-destination rule no longer declares `#{prop}` — its geometry is gone")

      many ->
        flunk(
          "`#{prop}` is declared #{length(many)} times — the winner is source-order dependent"
        )
    end
  end

  defp normalise(value) do
    value
    |> String.trim()
    |> String.replace(~r/\s*,\s*/, ", ")
    |> String.replace(~r/\s+/, " ")
  end
end
