defmodule BarkparkWeb.Studio.InspectorSummonedDestinationTest do
  @moduledoc """
  studio-space-priority-desk successor `inspector-narrow-destination-surface` —
  the summoned destination, and the abolition of dimming underneath it.

  ## What this file locks

  At `narrow` and `phone` a user-opened Document inspector becomes a
  DESTINATION at the full width of the content pane, and the overlay scrim
  renders in ZERO rows for that state. Both halves need locking for the same
  reason: neither is observable by any other test in this suite.

  The geometry half is a plain literal pin, same idiom as
  `wide_geometry_lock_test.exs` — expectations are hardcoded strings copied out
  of the stylesheet, never values re-derived from it. A pin that reads its own
  subject cannot fail from the only thing it purports to guard (charter D94).

  The scrim half CANNOT be a literal pin, and that is the whole difficulty.
  "The scrim does not render" is not a property of any one rule: the scrim is
  generated by a `::after` inside `@container panel (max-width: 860px)` and
  suppressed by two later rules with `content: none`, so the honest question is
  which declaration WINS for a given desk state. Asserting "a suppression rule
  exists" would go green against a suppression that never matches — the exact
  vacuity this epic has been bitten by twice (charter D39/D40: two measure
  criteria declared met on floors that had never once applied).

  So this file evaluates a CASCADE. It parses every scrim rule out of the
  sheet, derives each one's matching CONDITIONS from the selector text itself
  (never from a hand-written expectation), and computes the winning `content`
  value for a modelled desk state. The conditions come from the sheet, so a
  rule whose scope changes changes what this test concludes.

  ### The model's limits, stated

  ExUnit has no CSS engine. The specificity comparison here counts class and
  attribute tokens across the whole selector, including inside `:not()` and
  `:has()` — which is exactly the real rule for both, since every argument in
  this sheet is a single compound selector. Every scrim rule carries the same
  `::after` pseudo-element and no id selectors, so ordering by that count is
  faithful for this rule set and would need revisiting if an id or a
  multi-compound `:has()` ever landed here. Ties break on source order, as CSS
  does.

  ### Non-vacuity, and the mutation control

  Two guards keep the verdict from being free:

    * every "no scrim" row asserts that the scrim-GENERATING rule genuinely
      matched that state first. "No scrim because nothing matched" is not the
      claim being made; "no scrim because the suppression beat the generator"
      is.
    * `the suppression is what abolishes it` deletes the new rule from the
      source string and re-runs the identical evaluation, asserting the scrim
      comes back. The mutation is run in-process so the guarantee does not
      depend on anyone repeating it by hand.

  This slice OWNS `root.html.heex` this round (D16/D160). It stays file-disjoint
  from `wide_geometry_lock_test.exs` and `measure_parity_test.exs`; the small
  parsing helpers below are duplicated on purpose rather than shared, so this
  lock cannot be weakened by an edit aimed at either of those files.
  """
  use ExUnit.Case, async: true

  @moduletag :studio_summoned_destination

  @root Path.expand("../../../lib/barkpark_web/layouts/root.html.heex", __DIR__)

  # The two bucket-scoped selectors this slice added, verbatim.
  @narrow ~S|html[data-width-bucket="narrow"] .bp-doc-sidebar.is-open[data-user-opened]|
  @phone ~S|html[data-width-bucket="phone"] .bp-doc-sidebar.is-open[data-user-opened]|

  describe "the summoned destination takes the whole content pane" do
    test "narrow and phone are declared together and carry full-pane geometry" do
      block = block!([@narrow, @phone])

      # `absolute` + `inset: 0` against `.editor-panel`'s `position: relative`
      # IS "the full width of the content pane" — the pane is the containing
      # block, so the panel's box is the pane's box.
      assert value!(block, "position") == "absolute"

      assert value!(block, "inset") == "0",
             """
             The summoned inspector no longer fills its containing block.

             `inset: 0` against `.editor-panel`'s `position: relative` is what
             makes this a DESTINATION rather than a wider overlay. The whole
             argument for it (charter D113) is that at these widths there is no
             split of the pane in which the document survives: a 300px dock at
             viewport 800 leaves the reader 376px against the overlay's measured
             396.9px. Partially covering the pane re-opens exactly that.
             """

      assert value!(block, "width") == "auto",
             """
             A width is back on the summoned panel.

             The `@container panel (max-width: 860px)` block sets `width: 300px`
             on `.bp-doc-sidebar.is-open`. This rule must neutralise it, or the
             destination is a 300px overlay again with `inset: 0` fighting it.
             """

      # The overlay block raises this and z-index applies whatever the
      # position, so it is restated rather than inherited by luck.
      assert value!(block, "z-index") == "5"

      # Nothing shows through to cast a shadow onto, and nothing sits beside
      # the border.
      assert value!(block, "box-shadow") == "none"
      assert value!(block, "border-left") == "0"
    end

    test "the rule is bucket-scoped: it cannot match at wide or standard" do
      block = block!([@narrow, @phone])
      refute block == nil

      for bucket <- ~w(wide standard) do
        refute String.contains?(@narrow <> @phone, ~s|data-width-bucket="#{bucket}"|),
               """
               The summoned-destination rule names the `#{bucket}` bucket.

               At `wide` the inspector docks and costs the reader nothing — epic
               criterion 2 is measured there and the round-2 floor slice takes
               its input from those rows, so this rule may not move one pixel
               there (charter D92). `standard`'s answer is a different slice's
               to give.
               """
      end
    end

    test "the b29/D91 default rules are UNTOUCHED and still carve this state out" do
      src = decommented(css())

      # Both halves of the painted-closed default still exempt the asked-for
      # panel. If either lost its carve-out, the default would start fighting
      # the destination rule instead of yielding to it.
      assert src =~
               ~S|html:not([data-width-bucket="wide"]) .bp-doc-sidebar.is-open:not([data-user-opened])|,
             "the b29/D91 geometry default lost its `:not([data-user-opened])` carve-out"

      assert src =~ ~S|.editor-with-preview:has(.bp-doc-sidebar.is-open:not([data-user-opened]))::after|,
             "the b29/D91 scrim guard lost its `:not([data-user-opened])` carve-out"
    end

    test "no motion property is introduced on the summoned panel" do
      block = block!([@narrow, @phone])

      for prop <- ~w(transition animation transform filter will-change backdrop-filter perspective) do
        refute Regex.match?(~r/(?:^|;)\s*#{prop}\s*:/, block),
               """
               `#{prop}` landed on the summoned-destination rule.

               A fade spends its whole duration painting a translucent panel
               over live prose — a transient re-run of the dimming this slice
               abolishes — and `transform` plants a containing block for fixed
               descendants inside the pane whose containment hazard has its own
               tripwire (`editor_panel_containment_test.exs`). If motion is
               wanted here later it needs a scoped
               `@media (prefers-reduced-motion: reduce)` block that nulls the
               TRANSITION property itself, not merely an animation.
               """
      end
    end
  end

  describe "dimming is ABOLISHED for the summoned state — zero rendered scrims" do
    # Pane widths on both sides of the 860px overlay threshold. `narrow` runs
    # to 1023px, so a desk whose list panes have collapsed to 44px strips
    # really does present a pane wider than 860 inside this bucket — the
    # verdict has to hold in both.
    @pane_widths [700, 900]

    test "narrow + phone, user-opened: the winning `content` is `none` at every pane width" do
      for bucket <- ~w(narrow phone), pane <- @pane_widths do
        state = %{bucket: bucket, user_opened: true, pane: pane}
        matched = matching_scrim_rules(state)

        # NON-VACUITY FIRST. "No scrim because nothing matched" is not the
        # claim; "no scrim because the suppression beat the generator" is.
        assert Enum.any?(matched, fn r -> r.content == ~s|""| end) or pane > 860,
               """
               No scrim-GENERATING rule matches #{bucket}/user-opened at a #{pane}px
               pane, so the "no scrim" verdict below is free.

               The generator is the `::after` inside
               `@container panel (max-width: 860px)`. If it stopped matching,
               this test proves nothing about the suppression that follows it —
               re-derive the row rather than accepting the green.
               """

        assert matched != [], "no scrim rule of any kind matches #{bucket}/#{pane}px"

        assert winning_content(state) == "none",
               """
               THE SCRIM STILL RENDERS at bucket=#{bucket}, pane=#{pane}px, with the
               inspector user-opened.

               The winning `content` is `#{inspect(winning_content(state))}`, so the desk
               paints a 55%-black box over a document that is already completely
               covered by the summoned panel. That is the half-suspended read
               charter D127 ruled a DEFECT: at viewport 1024 the layout metric
               RISES 599->640px while the human LOSES 219px (599->380), and the
               prose is dimmed rather than hidden. Dimming is abolished here,
               not tuned.

               Rules that matched this state, in source order:
               #{inspect(Enum.map(matched, & &1.selector), pretty: true)}
               """
      end
    end

    test "the suppression is what abolishes it — mutation control" do
      # Delete the new suppression rule from the source and re-run the
      # identical evaluation. If the verdict does not flip, the assertion above
      # is not measuring this slice's change.
      mutated =
        Regex.replace(
          ~r/html\[data-width-bucket="narrow"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after,\s*html\[data-width-bucket="phone"\] \.editor-with-preview:has\(\.bp-doc-sidebar\.is-open\[data-user-opened\]\)::after \{[^}]*\}/,
          decommented(css()),
          ""
        )

      refute mutated == decommented(css()),
             "the mutation matched nothing — the control below is vacuous and the " <>
               "suppression rule has been reshaped without this test noticing"

      state = %{bucket: "narrow", user_opened: true, pane: 700}

      assert winning_content(state, mutated) == ~s|""|,
             """
             With the suppression rule deleted the scrim STILL does not render,
             so something other than this slice is suppressing it and the
             verdict above is not this slice's to claim.
             """
    end

    test "the scrim is untouched where it is still wanted — wide, and the b29 default" do
      # A wide-bucket pane narrow enough to overlay still dims: there the
      # inspector is a 300px overlay over a document that remains visible
      # beside and under it, which is precisely when a scrim earns its keep.
      assert winning_content(%{bucket: "wide", user_opened: true, pane: 700}) == ~s|""|,
             """
             The wide bucket lost its scrim.

             This slice is scoped to `narrow` and `phone`. A wide pane squeezed
             under 860px still overlays a VISIBLE document, which is the one
             state where dimming is the honest signal rather than an
             indeterminate half-suspension.
             """

      # And the b29 default (below wide, never asked for) stays suppressed —
      # the strip is invisible, so dimming under it was always nonsense.
      assert winning_content(%{bucket: "narrow", user_opened: false, pane: 700}) == "none"
    end
  end

  describe "negative control — the evaluator itself" do
    test "it finds more than one scrim rule, and reads their conditions" do
      rules = scrim_rules()

      assert length(rules) >= 3,
             """
             Only #{length(rules)} scrim rule(s) parsed out of the sheet.

             There are at least three: the generator inside
             `@container panel (max-width: 860px)`, the b29/D91 guard, and this
             slice's narrow/phone suppression. A parser that sees fewer has
             stopped reading the sheet and every cascade verdict above is
             computed over a fiction.
             """

      assert Enum.any?(rules, &(&1.content == ~s|""|)), "no scrim GENERATOR parsed"
      assert Enum.any?(rules, &(&1.content == "none")), "no scrim SUPPRESSION parsed"

      assert Enum.any?(rules, &(&1.max_pane == 860)),
             "the generator's `@container panel (max-width: 860px)` condition was not read — " <>
               "every pane-width row above is then evaluated without its own threshold"
    end

    test "a zero-match selector fails LOUDLY rather than returning an empty block" do
      assert_raise ExUnit.AssertionError, ~r/no-such-summoned-rule/, fn ->
        block!([".bp-doc-sidebar.no-such-summoned-rule"])
      end
    end

    test "a missing property fails LOUDLY rather than comparing nil" do
      block = block!([@narrow, @phone])

      assert_raise ExUnit.AssertionError, ~r/border-radius/, fn ->
        value!(block, "border-radius")
      end
    end

    test "specificity ordering counts tokens inside :has() and :not()" do
      # Both pseudo-classes take the specificity of their argument, and the
      # cascade verdict above depends on the narrow/phone suppression (a bucket
      # attribute + `.editor-with-preview` + a three-token `:has()`) outranking
      # the generator (`.editor-with-preview` + a two-token `:has()`).
      assert specificity(~S|.editor-with-preview:has(.bp-doc-sidebar.is-open)::after|) == 3

      assert specificity(
               ~S|html[data-width-bucket="narrow"] .editor-with-preview:has(.bp-doc-sidebar.is-open[data-user-opened])::after|
             ) == 5
    end
  end

  # --- the cascade evaluator -------------------------------------------

  # Every rule in the sheet that generates or suppresses the inspector scrim,
  # in source order, with the conditions it imposes DERIVED FROM ITS OWN
  # SELECTOR TEXT. Nothing here is hand-declared: a rule whose scope is edited
  # changes what this evaluator concludes, which is the point.
  defp scrim_rules(source \\ nil) do
    src = source || decommented(css())
    container_spans = container_spans(src)

    ~r/([^{}]*::after)\s*\{([^{}]*)\}/
    |> Regex.scan(src, return: :index)
    |> Enum.map(fn [{_, _}, sel_at, body_at] ->
      {selector, body} = {normalise(slice(src, sel_at)), slice(src, body_at)}
      {sel_start, _} = sel_at
      {selector, body, sel_start}
    end)
    # A comma-separated list is N rules, not one. Keeping it as one chunk would
    # read only the FIRST selector's conditions and silently drop the rest —
    # this slice's suppression is declared `narrow, phone`, so the phone rows
    # would evaluate against a rule that does not exist.
    |> Enum.flat_map(fn {chunk, body, at} ->
      chunk
      |> String.split(",")
      |> Enum.map(&normalise/1)
      |> Enum.reject(&(&1 == ""))
      |> Enum.map(&{&1, body, at})
    end)
    |> Enum.filter(fn {selector, _body, _at} ->
      String.contains?(selector, ".editor-with-preview") and
        String.contains?(selector, ".bp-doc-sidebar.is-open")
    end)
    |> Enum.map(fn {selector, body, at} ->
      %{
        selector: selector,
        content: content_of(body),
        order: at,
        specificity: specificity(selector),
        max_pane: enclosing_max_pane(container_spans, at),
        bucket_is: capture(selector, ~r/html\[data-width-bucket="([a-z]+)"\]/),
        bucket_is_not: capture(selector, ~r/html:not\(\[data-width-bucket="([a-z]+)"\]\)/),
        user_opened: user_opened_condition(selector)
      }
    end)
    |> Enum.sort_by(& &1.order)
  end

  defp user_opened_condition(selector) do
    cond do
      String.contains?(selector, ":not([data-user-opened])") -> false
      String.contains?(selector, "[data-user-opened]") -> true
      true -> :any
    end
  end

  defp matching_scrim_rules(state, source \\ nil) do
    Enum.filter(scrim_rules(source), fn rule ->
      (rule.max_pane == nil or state.pane <= rule.max_pane) and
        (rule.bucket_is == nil or rule.bucket_is == state.bucket) and
        (rule.bucket_is_not == nil or rule.bucket_is_not != state.bucket) and
        (rule.user_opened == :any or rule.user_opened == state.user_opened)
    end)
  end

  # The winner: highest specificity, ties broken by source order — CSS's own
  # rule. Returns the `content` value the browser would compute, or nil when
  # no rule matches at all (in which case there is no `::after` box either).
  defp winning_content(state, source \\ nil) do
    state
    |> matching_scrim_rules(source)
    |> Enum.sort_by(&{&1.specificity, &1.order})
    |> List.last()
    |> case do
      nil -> nil
      rule -> rule.content
    end
  end

  # Class and attribute tokens across the whole selector, INCLUDING inside
  # `:not()` and `:has()` — both take their argument's specificity, and every
  # argument in this sheet is a single compound selector. See the moduledoc for
  # where this stops being faithful.
  defp specificity(selector) do
    length(Regex.scan(~r/\.[A-Za-z][\w-]*/, selector)) +
      length(Regex.scan(~r/\[[^\]]+\]/, selector))
  end

  defp content_of(body) do
    case Regex.run(~r/(?:^|;)\s*content\s*:\s*([^;}]+)/, body, capture: :all_but_first) do
      [value] -> normalise(value)
      _ -> nil
    end
  end

  defp capture(text, regex) do
    case Regex.run(regex, text, capture: :all_but_first) do
      [value] -> value
      _ -> nil
    end
  end

  # `{start, end}` byte spans of every `@container panel (max-width: N)` block,
  # with N — brace-matched, because the 860px block nests a `:has()` rule and a
  # naive scan to the first `}` would truncate it and lose the scrim entirely.
  defp container_spans(src) do
    ~r/@container\s+panel\s*\(\s*max-width:\s*(\d+)px\s*\)\s*\{/
    |> Regex.scan(src, return: :index)
    |> Enum.map(fn [{match_start, match_len}, n_at] ->
      open_at = match_start + match_len - 1
      {open_at, balanced_end(src, open_at + 1, 1), String.to_integer(slice(src, n_at))}
    end)
  end

  defp enclosing_max_pane(spans, at) do
    spans
    |> Enum.filter(fn {open_at, close_at, _n} -> at > open_at and at < close_at end)
    |> Enum.map(fn {_o, _c, n} -> n end)
    |> case do
      [] -> nil
      widths -> Enum.min(widths)
    end
  end

  defp balanced_end(src, i, depth) do
    case :binary.at(src, i) do
      ?{ -> balanced_end(src, i + 1, depth + 1)
      ?} when depth == 1 -> i
      ?} -> balanced_end(src, i + 1, depth - 1)
      _ -> balanced_end(src, i + 1, depth)
    end
  end

  # --- parsing ---------------------------------------------------------

  defp css, do: File.read!(@root)

  # Comments first: this sheet's design prose quotes nearly every selector and
  # value below it, and a pin satisfiable by a comment is not a pin.
  defp decommented(src), do: Regex.replace(~r|/\*.*?\*/|s, src, "")

  defp slice(src, {at, len}), do: binary_part(src, at, len)

  # The one declaration block whose selector list is EXACTLY these selectors,
  # in this order. Zero matches raises here, naming them, rather than returning
  # an empty block that every assertion below passes against vacuously.
  defp block!(selectors) do
    esc = selectors |> Enum.map(&Regex.escape/1) |> Enum.join(~S|,\s*|)

    case Regex.scan(~r/(?:^|\})\s*#{esc}\s*\{([^{}]*)\}/, decommented(css()),
           capture: :all_but_first
         ) do
      [[one]] ->
        one

      [] ->
        flunk("""
        SELECTOR LIST MATCHED ZERO RULES:

        #{Enum.join(selectors, ",\n")}

        root.html.heex declares no rule with that selector list. Nothing below
        can be trusted — comparisons against an empty block pass vacuously,
        which is how this epic declared a measure criterion met twice on floors
        that had never once applied (charter D39/D40). Either the rule was
        renamed (repoint this constant and say so) or it was deleted, in which
        case the geometry it carried is GONE and that is the bug.
        """)

      many ->
        flunk("that selector list now has #{length(many)} rules — the winner is source-order dependent")
    end
  end

  defp value!(block, prop) do
    case Regex.scan(~r/(?:^|;)\s*#{Regex.escape(prop)}\s*:\s*([^;}]+)/, block,
           capture: :all_but_first
         ) do
      [[one]] ->
        normalise(one)

      [] ->
        flunk("the summoned-destination rule no longer declares `#{prop}` — its geometry is gone")

      many ->
        flunk("`#{prop}` is declared #{length(many)} times — the winner is source-order dependent")
    end
  end

  defp normalise(value) do
    value
    |> String.trim()
    |> String.replace(~r/\s*,\s*/, ", ")
    |> String.replace(~r/\s+/, " ")
  end
end
