// Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write

package semrole

import "github.com/charmbracelet/lipgloss"

// Generated CLI/TUI chrome roles (design/tokens.json color.cliChrome → hex).
// Nine NEW hex roles + five REUSE references resolved to their target role's
// hex (chrome-primary-cta = evergreen --primary; chrome-on-primary = --primary-fg).
var (
	GenChromeAccent        = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenChromeDim           = lipgloss.AdaptiveColor{Light: "#a1a1aa", Dark: "#52525b"}
	GenChromeInk           = lipgloss.AdaptiveColor{Light: "#18181b", Dark: "#e4e4e7"}
	GenChromeTextSecondary = lipgloss.AdaptiveColor{Light: "#3f3f46", Dark: "#a1a1aa"}
	GenChromeSelectionBg   = lipgloss.AdaptiveColor{Light: "#e9eeec", Dark: "#141c1b"}
	GenChromeSelectionFg   = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#92d3bd"}
	GenChromeFieldBorder   = lipgloss.AdaptiveColor{Light: "#d4d4d8", Dark: "#3f3f46"}
	GenChromeToolbarBg     = lipgloss.AdaptiveColor{Light: "#fafafa", Dark: "#0a0a0a"}
	GenChromeCursorBg      = lipgloss.AdaptiveColor{Light: "#f4f4f5", Dark: "#18181b"}
	GenChromeBorder        = lipgloss.AdaptiveColor{Light: "#e4e4e7", Dark: "#27272a"}
	GenChromeBorderActive  = lipgloss.AdaptiveColor{Light: "#3b82f6", Dark: "#3b82f6"}
	GenChromeLabel         = lipgloss.AdaptiveColor{Light: "#71717a", Dark: "#a1a1aa"}
	GenChromePrimaryCta    = lipgloss.AdaptiveColor{Light: "#1e5243", Dark: "#75c7ac"}
	GenChromeOnPrimary     = lipgloss.AdaptiveColor{Light: "#ffffff", Dark: "#0b1e18"}
)

// GenChrome maps a cliChrome role name to its adaptive colour.
var GenChrome = map[string]lipgloss.AdaptiveColor{
	"chrome-accent":         GenChromeAccent,
	"chrome-dim":            GenChromeDim,
	"chrome-ink":            GenChromeInk,
	"chrome-text-secondary": GenChromeTextSecondary,
	"chrome-selection-bg":   GenChromeSelectionBg,
	"chrome-selection-fg":   GenChromeSelectionFg,
	"chrome-field-border":   GenChromeFieldBorder,
	"chrome-toolbar-bg":     GenChromeToolbarBg,
	"chrome-cursor-bg":      GenChromeCursorBg,
	"chrome-border":         GenChromeBorder,
	"chrome-border-active":  GenChromeBorderActive,
	"chrome-label":          GenChromeLabel,
	"chrome-primary-cta":    GenChromePrimaryCta,
	"chrome-on-primary":     GenChromeOnPrimary,
}

// ThemeChrome bundles one theme's CLI/TUI chrome role map. Keyed off the same
// DefaultTheme const (tokens_gen.go); ResolveChrome defaults to evergreen for an
// unknown/empty id so ChromeColorFor never returns a partial palette.
type ThemeChrome struct {
	Chrome map[string]lipgloss.AdaptiveColor
}

// genChrome keys each theme's chrome map by id (evergreen REFERENCES GenChrome).
var genChrome = map[string]ThemeChrome{
	"evergreen": {Chrome: GenChrome},
}

// ResolveChrome returns a theme's chrome role map, defaulting to evergreen.
func ResolveChrome(theme string) ThemeChrome {
	if c, ok := genChrome[theme]; ok {
		return c
	}
	return genChrome[DefaultTheme]
}

// GenProviderMark is the generated cloud-provider IDENTITY palette
// (design/tokens.json color.provider → hex). Identity ONLY (Decision 7):
// tint a chip mark or a chip/row border, NEVER a pill background — the
// status roles stay the only state voice. Unconsumed until a later wave
// threads it through the CLI provider-chip / table renderers.
var GenProviderMark = map[string]lipgloss.AdaptiveColor{
	"hetzner": {Light: "#c4123a", Dark: "#f0728a"},
	"azure":   {Light: "#0f6cbd", Dark: "#4aa3e0"},
}

// GenInstanceLifecycleToken mirrors one design/tokens.json instanceLifecycle
// state. Hue is the state's status-role tone resolved to hex (role "" → the
// muted-text neutral); the CLI reads colour THROUGH the role, never a bespoke
// per-state hue (Decision 7).
type GenInstanceLifecycleToken struct {
	Glyph      string
	ASCIIGlyph string
	Role       string
	HueLight   string
	HueDark    string
}

// GenInstanceLifecycle is the generated 1:1 mirror of tokens.instanceLifecycle
// (glyph + role + role-derived hue).
var GenInstanceLifecycle = map[string]GenInstanceLifecycleToken{
	"provisioning":   {Glyph: "◌", ASCIIGlyph: "~", Role: "info", HueLight: "#3b82f6", HueDark: "#3b82f6"},
	"live":           {Glyph: "●", ASCIIGlyph: "*", Role: "ok", HueLight: "#137236", HueDark: "#45c474"},
	"degraded":       {Glyph: "◐", ASCIIGlyph: "!", Role: "warn", HueLight: "#ba7008", HueDark: "#f8ab25"},
	"stopped":        {Glyph: "○", ASCIIGlyph: "o", Role: "", HueLight: "#71717a", HueDark: "#a1a1aa"},
	"archived":       {Glyph: "▢", ASCIIGlyph: "#", Role: "", HueLight: "#71717a", HueDark: "#a1a1aa"},
	"decommissioned": {Glyph: "✕", ASCIIGlyph: "x", Role: "danger", HueLight: "#b42222", HueDark: "#ef6161"},
	"adopted":        {Glyph: "◈", ASCIIGlyph: "+", Role: "info", HueLight: "#3b82f6", HueDark: "#3b82f6"},
}

// GenInstanceLifecycleOrder is the canonical emission order (matches source).
var GenInstanceLifecycleOrder = []string{"provisioning", "live", "degraded", "stopped", "archived", "decommissioned", "adopted"}
