defmodule BarkparkWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :barkpark

  require Logger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_barkpark_key",
    signing_salt: "czq4X2DQ",
    same_site: "Lax"
  ]

  # `:peer_data` + `:x_headers` are what make an IP-keyed budget on a LiveView
  # mount real. `BarkparkWeb.QuizHostLive` is an ANONYMOUS door that STARTS a
  # process per visitor-supplied pin; without these two keys its connect_info
  # carries no address at all, every spawn bills ONE shared fallback bucket,
  # and `Barkpark.Quiz.SpawnBudget` degrades from a per-visitor brake into a
  # global one — the exact shape the budget replaced. Declared on BOTH
  # transports: longpoll is a real fallback, not a curiosity, and a limiter
  # that only holds on websocket is a limiter with a documented bypass.
  # The trust boundary is NOT here — both fields go to
  # `Barkpark.RateLimiter.client_ip/1`, which decides which to believe.
  #
  # `max_frame_size` is the websock_adapter default (10 MB), stated here on
  # purpose (owner ruling #39): it is the LiveView door's half of the
  # per-document size cap, and leaving it implicit hid the limit from review.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [:peer_data, :x_headers, session: @session_options],
      max_frame_size: 10_000_000
    ],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Public realtime socket — carries SearchChannel for per-keystroke live search
  # (browser → API direct, one persistent connection, no per-keystroke TLS/Vercel
  # hop). No per-socket `check_origin` override on purpose: the websocket inherits
  # the endpoint-level allowlist from runtime.exs (barkpark.cloud + *.vercel.app +
  # BARKPARK_EXTRA_ORIGINS). Overriding it here is the Past-Mistake-#11 landmine —
  # a private list that drifts from the LiveView one and silently 403s. longpoll
  # off: a search keystroke stream has no use for the fallback transport.
  # `connect_info` is what makes the per-IP half of `UserSocket`'s connect
  # budget real: without it `connect/3` receives `%{}` and the budget can only
  # key on the token row, which every visitor of one flagship site shares.
  # `:peer_data` is the verified TCP peer and `:x_headers` the forwarded chain;
  # BOTH are handed to `Barkpark.RateLimiter.client_ip/1`, which decides which
  # one to believe — the header is never trusted on its own. check_origin
  # inheritance is unchanged (no per-socket override, Past-Mistake-#11), and
  # longpoll stays off.
  socket "/socket", BarkparkWeb.UserSocket,
    websocket: [connect_info: [:peer_data, :x_headers]],
    longpoll: false

  # Anonymous realtime socket for Pulse channels (Shared Storm) — subscribe-only
  # strike feed; every gate lives at channel join. Same check_origin inheritance
  # as /socket above (no per-socket override — Past-Mistake-#11): embedding
  # sites are added via BARKPARK_EXTRA_ORIGINS.
  socket "/v1/plugins/pulse/socket", BarkparkWeb.PulseSocket,
    websocket: true,
    longpoll: false

  # Hyperquiz player socket — ANONYMOUS (no token; players join a room by PIN
  # with a nickname, Kahoot-style). Carries QuizChannel on "quiz:room:<pin>".
  # THE one irreducible core edit for the quiz plugin: Phoenix `socket/3` is a
  # compile-time macro with no plugin callback, so — like the Pulse socket above
  # — the plugin hand-adds its socket here. Inherits the endpoint-level
  # check_origin allowlist (NO per-socket override — Past-Mistake-#11). The
  # QuizChannel/QuizSocket carry the routes/workers via the plugin; a disabled
  # quiz plugin leaves this socket dormant with no reachable channel.
  socket "/quiz", BarkparkWeb.QuizSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # `no-cache` ≠ "don't cache": it means REVALIDATE every time — the browser
  # keeps the bytes but must ask (`If-None-Match`), and Plug.Static answers 304
  # off the etag when unchanged. Without it these unversioned assets shipped a
  # bare `cache-control: public`, so browsers heuristically served a STALE
  # Studio shell after a deploy until a hard refresh (the same live bug the
  # cloud console already fixed).
  #
  # BOTH keys are required — each covers a branch of
  # `Plug.Static.serve_static/5` the other cannot reach, mutation-proven, not
  # assumed. `cache_control_for_etags:` (default `"public"`) is the ONLY cache
  # header a 304 carries: the `{:fresh, conn}` branch sends without merging
  # `headers:`, so without this key every revalidation answers `public`.
  # `headers:` is merged on the 200 branch and is what overrides the
  # `?vsn=`-request header, which comes from a SEPARATE clause of
  # `put_cache_header/6` and defaults to `public, max-age=31536000, immutable`
  # — a fingerprinted URL would otherwise ship a year of immutable caching.
  # Same two-key discipline as
  # `cloud/lib/barkpark_cloud/web/router.ex:370-375` / `:415-422`.
  #
  # Stated cost, accepted: Plug.Static's etag is `phash2({size, mtime})`, so
  # every deploy mints fresh etags and the first post-deploy load is full 200s.
  # That IS the fix — the stale shell is what we are paying to lose.
  #
  # DO NOT add an etag-based freshness comparison here: the etag is a hash of
  # the served FILE's size+mtime, never content identity, so it cannot witness
  # staleness (cch charter D139). DO NOT drop `gzip:` — with zero `.gz`
  # siblings it is a byte no-op today, but removing it also drops
  # `vary: Accept-Encoding`.
  plug Plug.Static,
    at: "/",
    from: :barkpark,
    gzip: not code_reloading?,
    only: BarkparkWeb.static_paths(),
    raise_on_missing_only: code_reloading?,
    headers: %{"cache-control" => "no-cache"},
    cache_control_for_etags: "no-cache"

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :barkpark
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # A NEW REQUEST STARTS WITH AN EMPTY READ MEMO (task-43754c756edf2af6).
  # Bandit serves every request on a keep-alive HTTP/1.1 connection in ONE
  # process, so the per-request memo `WriteScope.request_memo/3` keeps in the
  # process dictionary would otherwise answer request 2 with request 1's
  # dataset / schema resolutions — measured: after one request the memo key
  # was still set when the next request on the same process began.
  plug :reset_request_memo

  # P7 safe external sharing: when BARKPARK_SHARE_HOST (a tunnel domain) is set,
  # any request NOT from a local/LAN host may reach ONLY the public read/share
  # surfaces; everything else 404s. No-op (default-OFF) when unset. Runs after
  # Plug.Static (real assets served regardless) and before body parsing + Router.
  plug BarkparkWeb.Plugs.PublicShareGuard

  plug :parse_body

  plug Plug.MethodOverride
  plug Plug.Head
  # LOW-15: the session cookie is marked `Secure` when the endpoint is served
  # over HTTPS (driven by PHX_SCHEME at runtime via :barkpark, :session_secure),
  # so it is never sent back over plaintext HTTP. We deliberately do NOT
  # force_ssl (Golden Rule #5 — it causes 301 redirect loops on prod-HTTP); we
  # only flip the cookie flag. Resolved at request time so config/runtime.exs
  # wins without a recompile. The LiveView socket keeps the base @session_options
  # (the Secure flag is irrelevant to reading a presented cookie).
  plug :secure_session
  plug BarkparkWeb.Plugs.DatasetCors

  plug BarkparkWeb.Router

  defp reset_request_memo(conn, _opts) do
    Barkpark.Content.WriteScope.begin_request()
    conn
  end

  defp secure_session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  @doc """
  The runtime session options: the base `@session_options` plus `secure: true`
  when `:barkpark, :session_secure` is set (PHX_SCHEME=https in prod). Public so
  it can be asserted in tests.
  """
  def session_options do
    if Application.get_env(:barkpark, :session_secure, false) do
      Keyword.put(@session_options, :secure, true)
    else
      @session_options
    end
  end

  # ── Low-trust doors cap the body AT THE PARSER (Run-4 Lane B) ─────────────
  #
  # The general cap is 100 MB (media uploads, imports). Two doors are reachable
  # by callers with no account: the ANONYMOUS form-submission door and the
  # OUTSIDER ticket door (`bptk_` keys). Their real caps — 64 KiB per form
  # body, 64 KiB per ticket message, 10 MiB per attachment — lived only in the
  # controllers, which run AFTER this parse, and a chunked request carries no
  # `content-length` for a pre-check to read. So one anonymous client could
  # make the server decode ~100 MB per request before the rate limit or the key
  # check ran. These caps stop the read at the door's own ceiling (plus
  # multipart slack for attachments); an oversize body gets the same enveloped
  # 413 `payload_too_large` the general cap answers. Pinned by
  # `test/barkpark_web/endpoint_low_trust_body_cap_test.exs`.
  @general_body_length 100_000_000
  @forms_submission_body_length 64 * 1024
  @ticket_attachment_body_length 11 * 1024 * 1024
  @ticket_body_length 1_000_000

  defp body_length(%Plug.Conn{
         path_info: ["v1", "plugins", "forms", "w", _, "p", _, "d", _, "sites", _, "submissions"]
       }),
       do: @forms_submission_body_length

  defp body_length(%Plug.Conn{path_info: ["v1", "tickets", _id, "attachments"]}),
    do: @ticket_attachment_body_length

  defp body_length(%Plug.Conn{path_info: ["v1", "tickets" | _]}), do: @ticket_body_length

  # The document data routes (owner ruling #39). One document is capped by
  # `Barkpark.Content.DocumentSize` in the changeset; the body cap stops the
  # server reading and decoding a 100 MB batch first. Three documents at the cap
  # fit in one request; a bigger batch is split by the caller.
  defp body_length(%Plug.Conn{path_info: ["v1", "data" | _]}), do: data_body_length()

  defp body_length(%Plug.Conn{path_info: ["w", _ws, "p", _proj, "v1", "data" | _]}),
    do: data_body_length()

  defp body_length(_conn), do: @general_body_length

  defp data_body_length do
    case Barkpark.Content.DocumentSize.max_bytes() do
      nil -> @general_body_length
      cap -> min(cap * 3, @general_body_length)
    end
  end

  defp parse_body(conn, _opts) do
    try do
      Plug.Parsers.call(
        conn,
        Plug.Parsers.init(
          parsers: [:urlencoded, :multipart, :json],
          pass: ["*/*"],
          json_decoder: Phoenix.json_library(),
          length: body_length(conn),
          # Tee the RAW body into conn.assigns[:raw_body] ONLY on the GitHub
          # webhook path, so BarkparkWeb.Plugs.GithubWebhookSignature can verify
          # the HMAC over the exact bytes GitHub signed. Every other path reads
          # straight through with no buffering — see the plug's @moduledoc.
          body_reader: {BarkparkWeb.Plugs.CacheBodyReader, :read_body, []}
        )
      )
    rescue
      Plug.Parsers.ParseError ->
        conn
        |> parse_error_json(400, %{code: "malformed", message: "invalid request body"})

      # A body over the 100 MB `length` cap raises RequestTooLargeError. Without
      # this branch it escapes parse_body → a generic 413 that is NOT the
      # canonical {error:{code,message,request_id}} envelope. Mirror the
      # ParseError branch so an oversize upload returns a typed, enveloped 413.
      #
      # The limit named in the message and hint is the one THIS route applied
      # (`body_length/1`): the code-keyed default hint says "100 MB", which told
      # an anonymous form poster refused at 64 KB to keep their 200 KB body.
      Plug.Parsers.RequestTooLargeError ->
        limit = format_bytes(body_length(conn))

        BarkparkWeb.ErrorResponse.emit_custom(
          conn,
          413,
          "payload_too_large",
          "request body exceeds the maximum allowed size (#{limit} for this route)",
          %{},
          "Reduce the request body — this route accepts at most #{limit}. Upload a smaller file or split the request."
        )
    end
  end

  defp format_bytes(bytes) when bytes >= 1_000_000 and rem(bytes, 1_000_000) == 0,
    do: "#{div(bytes, 1_000_000)} MB"

  defp format_bytes(bytes) when bytes >= 1024 * 1024,
    do: "#{Float.round(bytes / (1024 * 1024), 1)} MiB"

  defp format_bytes(bytes) when bytes >= 1024, do: "#{div(bytes, 1024)} KiB"
  defp format_bytes(bytes), do: "#{bytes} bytes"

  # Emit a canonical §9 error envelope from parse_body's rescue (it runs before
  # any controller, so there's no action_fallback here). Routes through the ONE
  # shared emitter, which stamps hint + request_id via Content.Errors and halts —
  # retiring this path's inline copy of the request_id logic.
  defp parse_error_json(conn, status, %{code: code, message: message}) do
    BarkparkWeb.ErrorResponse.emit_custom(conn, status, code, message)
  end
end
