defmodule BarkparkWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :barkpark

  require Logger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_barkpark_key",
    signing_salt: "czq4X2DQ",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Public realtime socket — carries SearchChannel for per-keystroke live search
  # (browser → API direct, one persistent connection, no per-keystroke TLS/Vercel
  # hop). No per-socket `check_origin` override on purpose: the websocket inherits
  # the endpoint-level allowlist from runtime.exs (barkpark.cloud + *.vercel.app +
  # BARKPARK_EXTRA_ORIGINS). Overriding it here is the Past-Mistake-#11 landmine —
  # a private list that drifts from the LiveView one and silently 403s. longpoll
  # off: a search keystroke stream has no use for the fallback transport.
  socket "/socket", BarkparkWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Anonymous realtime socket for Pulse channels (Shared Storm) — subscribe-only
  # strike feed; every gate lives at channel join. Same check_origin inheritance
  # as /socket above (no per-socket override — Past-Mistake-#11): embedding
  # sites are added via BARKPARK_EXTRA_ORIGINS.
  socket "/v1/plugins/pulse/socket", BarkparkWeb.PulseSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :barkpark,
    gzip: not code_reloading?,
    only: BarkparkWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :barkpark
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # P7 safe external sharing: when BARKPARK_SHARE_HOST (a tunnel domain) is set,
  # any request NOT from a local/LAN host may reach ONLY the public read/share
  # surfaces; everything else 404s. No-op (default-OFF) when unset. Runs after
  # Plug.Static (real assets served regardless) and before body parsing + Router.
  plug BarkparkWeb.Plugs.PublicShareGuard

  plug :parse_body

  plug Plug.MethodOverride
  plug Plug.Head
  # LOW-15: the session cookie is marked `Secure` when the endpoint is served
  # over HTTPS (driven by PHX_SCHEME at runtime via :barkpark, :session_secure),
  # so it is never sent back over plaintext HTTP. We deliberately do NOT
  # force_ssl (Golden Rule #5 — it causes 301 redirect loops on prod-HTTP); we
  # only flip the cookie flag. Resolved at request time so config/runtime.exs
  # wins without a recompile. The LiveView socket keeps the base @session_options
  # (the Secure flag is irrelevant to reading a presented cookie).
  plug :secure_session
  plug BarkparkWeb.Plugs.DatasetCors

  plug BarkparkWeb.Router

  defp secure_session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  @doc """
  The runtime session options: the base `@session_options` plus `secure: true`
  when `:barkpark, :session_secure` is set (PHX_SCHEME=https in prod). Public so
  it can be asserted in tests.
  """
  def session_options do
    if Application.get_env(:barkpark, :session_secure, false) do
      Keyword.put(@session_options, :secure, true)
    else
      @session_options
    end
  end

  defp parse_body(conn, _opts) do
    try do
      Plug.Parsers.call(
        conn,
        Plug.Parsers.init(
          parsers: [:urlencoded, :multipart, :json],
          pass: ["*/*"],
          json_decoder: Phoenix.json_library(),
          length: 100_000_000
        )
      )
    rescue
      Plug.Parsers.ParseError ->
        conn
        |> parse_error_json(400, %{code: "malformed", message: "invalid request body"})

      # A body over the 100 MB `length` cap raises RequestTooLargeError. Without
      # this branch it escapes parse_body → a generic 413 that is NOT the
      # canonical {error:{code,message,request_id}} envelope. Mirror the
      # ParseError branch so an oversize upload returns a typed, enveloped 413.
      Plug.Parsers.RequestTooLargeError ->
        conn
        |> parse_error_json(413, %{
          code: "payload_too_large",
          message: "request body exceeds the maximum allowed size"
        })
    end
  end

  # Emit a canonical §9 error envelope from parse_body's rescue (it runs before
  # any controller, so there's no action_fallback here). Stamps the request_id
  # when Logger metadata carries one, then halts the pipeline.
  defp parse_error_json(conn, status, err) do
    err =
      case Logger.metadata()[:request_id] do
        id when is_binary(id) and id != "" -> Map.put(err, :request_id, id)
        _ -> err
      end

    conn
    |> Plug.Conn.put_status(status)
    |> Phoenix.Controller.json(%{error: err})
    |> Plug.Conn.halt()
  end
end
