defmodule BarkparkWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :barkpark

  require Logger

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_barkpark_key",
    signing_salt: "czq4X2DQ",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Public realtime socket — carries SearchChannel for per-keystroke live search
  # (browser → API direct, one persistent connection, no per-keystroke TLS/Vercel
  # hop). No per-socket `check_origin` override on purpose: the websocket inherits
  # the endpoint-level allowlist from runtime.exs (barkpark.cloud + *.vercel.app +
  # BARKPARK_EXTRA_ORIGINS). Overriding it here is the Past-Mistake-#11 landmine —
  # a private list that drifts from the LiveView one and silently 403s. longpoll
  # off: a search keystroke stream has no use for the fallback transport.
  # `connect_info` is what makes the per-IP half of `UserSocket`'s connect
  # budget real: without it `connect/3` receives `%{}` and the budget can only
  # key on the token row, which every visitor of one flagship site shares.
  # `:peer_data` is the verified TCP peer and `:x_headers` the forwarded chain;
  # BOTH are handed to `Barkpark.RateLimiter.client_ip/1`, which decides which
  # one to believe — the header is never trusted on its own. check_origin
  # inheritance is unchanged (no per-socket override, Past-Mistake-#11), and
  # longpoll stays off.
  socket "/socket", BarkparkWeb.UserSocket,
    websocket: [connect_info: [:peer_data, :x_headers]],
    longpoll: false

  # Anonymous realtime socket for Pulse channels (Shared Storm) — subscribe-only
  # strike feed; every gate lives at channel join. Same check_origin inheritance
  # as /socket above (no per-socket override — Past-Mistake-#11): embedding
  # sites are added via BARKPARK_EXTRA_ORIGINS.
  socket "/v1/plugins/pulse/socket", BarkparkWeb.PulseSocket,
    websocket: true,
    longpoll: false

  # Hyperquiz player socket — ANONYMOUS (no token; players join a room by PIN
  # with a nickname, Kahoot-style). Carries QuizChannel on "quiz:room:<pin>".
  # THE one irreducible core edit for the quiz plugin: Phoenix `socket/3` is a
  # compile-time macro with no plugin callback, so — like the Pulse socket above
  # — the plugin hand-adds its socket here. Inherits the endpoint-level
  # check_origin allowlist (NO per-socket override — Past-Mistake-#11). The
  # QuizChannel/QuizSocket carry the routes/workers via the plugin; a disabled
  # quiz plugin leaves this socket dormant with no reachable channel.
  socket "/quiz", BarkparkWeb.QuizSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # `no-cache` ≠ "don't cache": it means REVALIDATE every time — the browser
  # keeps the bytes but must ask (`If-None-Match`), and Plug.Static answers 304
  # off the etag when unchanged. Without it these unversioned assets shipped a
  # bare `cache-control: public`, so browsers heuristically served a STALE
  # Studio shell after a deploy until a hard refresh (the same live bug the
  # cloud console already fixed).
  #
  # BOTH keys are required — each covers a branch of
  # `Plug.Static.serve_static/5` the other cannot reach, mutation-proven, not
  # assumed. `cache_control_for_etags:` (default `"public"`) is the ONLY cache
  # header a 304 carries: the `{:fresh, conn}` branch sends without merging
  # `headers:`, so without this key every revalidation answers `public`.
  # `headers:` is merged on the 200 branch and is what overrides the
  # `?vsn=`-request header, which comes from a SEPARATE clause of
  # `put_cache_header/6` and defaults to `public, max-age=31536000, immutable`
  # — a fingerprinted URL would otherwise ship a year of immutable caching.
  # Same two-key discipline as
  # `cloud/lib/barkpark_cloud/web/router.ex:370-375` / `:415-422`.
  #
  # Stated cost, accepted: Plug.Static's etag is `phash2({size, mtime})`, so
  # every deploy mints fresh etags and the first post-deploy load is full 200s.
  # That IS the fix — the stale shell is what we are paying to lose.
  #
  # DO NOT add an etag-based freshness comparison here: the etag is a hash of
  # the served FILE's size+mtime, never content identity, so it cannot witness
  # staleness (cch charter D139). DO NOT drop `gzip:` — with zero `.gz`
  # siblings it is a byte no-op today, but removing it also drops
  # `vary: Accept-Encoding`.
  plug Plug.Static,
    at: "/",
    from: :barkpark,
    gzip: not code_reloading?,
    only: BarkparkWeb.static_paths(),
    raise_on_missing_only: code_reloading?,
    headers: %{"cache-control" => "no-cache"},
    cache_control_for_etags: "no-cache"

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :barkpark
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # P7 safe external sharing: when BARKPARK_SHARE_HOST (a tunnel domain) is set,
  # any request NOT from a local/LAN host may reach ONLY the public read/share
  # surfaces; everything else 404s. No-op (default-OFF) when unset. Runs after
  # Plug.Static (real assets served regardless) and before body parsing + Router.
  plug BarkparkWeb.Plugs.PublicShareGuard

  plug :parse_body

  plug Plug.MethodOverride
  plug Plug.Head
  # LOW-15: the session cookie is marked `Secure` when the endpoint is served
  # over HTTPS (driven by PHX_SCHEME at runtime via :barkpark, :session_secure),
  # so it is never sent back over plaintext HTTP. We deliberately do NOT
  # force_ssl (Golden Rule #5 — it causes 301 redirect loops on prod-HTTP); we
  # only flip the cookie flag. Resolved at request time so config/runtime.exs
  # wins without a recompile. The LiveView socket keeps the base @session_options
  # (the Secure flag is irrelevant to reading a presented cookie).
  plug :secure_session
  plug BarkparkWeb.Plugs.DatasetCors

  plug BarkparkWeb.Router

  defp secure_session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  @doc """
  The runtime session options: the base `@session_options` plus `secure: true`
  when `:barkpark, :session_secure` is set (PHX_SCHEME=https in prod). Public so
  it can be asserted in tests.
  """
  def session_options do
    if Application.get_env(:barkpark, :session_secure, false) do
      Keyword.put(@session_options, :secure, true)
    else
      @session_options
    end
  end

  defp parse_body(conn, _opts) do
    try do
      Plug.Parsers.call(
        conn,
        Plug.Parsers.init(
          parsers: [:urlencoded, :multipart, :json],
          pass: ["*/*"],
          json_decoder: Phoenix.json_library(),
          length: 100_000_000,
          # Tee the RAW body into conn.assigns[:raw_body] ONLY on the GitHub
          # webhook path, so BarkparkWeb.Plugs.GithubWebhookSignature can verify
          # the HMAC over the exact bytes GitHub signed. Every other path reads
          # straight through with no buffering — see the plug's @moduledoc.
          body_reader: {BarkparkWeb.Plugs.CacheBodyReader, :read_body, []}
        )
      )
    rescue
      Plug.Parsers.ParseError ->
        conn
        |> parse_error_json(400, %{code: "malformed", message: "invalid request body"})

      # A body over the 100 MB `length` cap raises RequestTooLargeError. Without
      # this branch it escapes parse_body → a generic 413 that is NOT the
      # canonical {error:{code,message,request_id}} envelope. Mirror the
      # ParseError branch so an oversize upload returns a typed, enveloped 413.
      Plug.Parsers.RequestTooLargeError ->
        conn
        |> parse_error_json(413, %{
          code: "payload_too_large",
          message: "request body exceeds the maximum allowed size"
        })
    end
  end

  # Emit a canonical §9 error envelope from parse_body's rescue (it runs before
  # any controller, so there's no action_fallback here). Routes through the ONE
  # shared emitter, which stamps hint + request_id via Content.Errors and halts —
  # retiring this path's inline copy of the request_id logic.
  defp parse_error_json(conn, status, %{code: code, message: message}) do
    BarkparkWeb.ErrorResponse.emit_custom(conn, status, code, message)
  end
end
