import Config

# Configure your database
config :barkpark, Barkpark.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "barkpark_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Preview-JWT dev signing secret (throwaway). Prod reads PREVIEW_JWT_SECRET in
# runtime.exs; kept OUT of config.exs so Sobelow Config.Secrets stays clean
# (dev.exs is in Sobelow's config skip-list). Merges with the ttl_seconds/issuer
# base set in config.exs.
config :barkpark, :preview, secret: "dev-preview-secret-change-in-prod-please-32-chars"

# Stable local-only key for the immutable Cycle release-proof anchor. Production
# still requires an independently generated BARKPARK_RELEASE_CAPTURE_HMAC_SECRET
# in runtime.exs; this value exists so a clean local install can migrate and boot
# without secret provisioning before the user has enabled any cloud capture.
config :barkpark,
       :cycle_release_capture_hmac_secret,
       "barkpark-local-release-capture-secret-do-not-use-in-production"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :barkpark, BarkparkWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Port honors the PORT env var (default 4000) so a busy port can be overridden
  # without editing config — used by scripts/setup-windows.ps1 -Port.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "j57gydAzyK6dSNxOUtz2vtqI/eKWiA88IPjenqUlT/YzTtLrf8mdhuG4CZu/iG/S",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :barkpark, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :barkpark, :default_cors_origins, ["http://localhost:3000", "http://localhost:5173"]

# Local paper-ingest secret. Set BARKPARK_INGEST_TOKEN to override the default.
config :barkpark,
       :ingest_token,
       System.get_env("BARKPARK_INGEST_TOKEN", "barkpark-dev-ingest-token")

# Seeded by priv/repo/seeds.exs — injected into Studio LiveViews so local
# media upload works without visiting /login first.
config :barkpark, :dev_browser_token, "barkpark-dev-token"

# SSRF guard escape hatch (Barkpark.Net.SafeOutbound). Local webhooks commonly
# point at localhost during development; prod/runtime leaves this false.
config :barkpark, :allow_private_outbound, true

# Anonymous browsers may enter the Default workspace's Studio (the public
# demo / no-login dev posture). OFF by default in prod — see runtime.exs
# (BARKPARK_PUBLIC_DEMO_STUDIO) and config.exs for the fail-closed base.
# Set BARKPARK_PUBLIC_DEMO_STUDIO=0 to run the local Studio authenticated —
# admin-gated surfaces that HARD-REFUSE public-demo hosts (tmux console,
# Claude chat) are invisible in the default dev posture.
config :barkpark,
       :public_demo_studio,
       System.get_env("BARKPARK_PUBLIC_DEMO_STUDIO", "1") not in ["0", "false", "no", "off"]
