# Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
# Regenerate: node design/emit.mjs --write

defmodule Barkpark.PortableDoc.Render.TokensGen do
  @moduledoc """
  Unified Aesthetic tokens for the paper render surface (emails + article
  palettes), generated from design/tokens.json. Regenerate with
  `node design/emit.mjs --write`; never hand-edit. Additive until wave 2,
  when palettes.ex adopts it (email indigo → evergreen brand; article accent
  → tokenized terracotta).
  """

  # Evergreen brand — the paper/email accent, its foreground, and the hairline.
  def brand, do: "#1e5243"
  def brand_text, do: "#ffffff"
  def rule, do: "#e4e4e7"

  # Semantic status tones (design/tokens.json color.status, light theme → hex).
  def tone_ok, do: "#137236"
  def tone_info, do: "#3b82f6"
  def tone_warn, do: "#ba7008"
  def tone_danger, do: "#b42222"

  # Warm reading accent — the paper terracotta, tokenized.
  def reading_accent, do: "#a23925"

  # Reading type (design/tokens.json font.reading / type.reading).
  def reading_font, do: "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Charter, Georgia, \"Source Serif 4\", serif"
  def reading_heading_weight, do: 600
  def reading_body_size, do: 18
end
