# Code generated by design/emit.mjs from design/tokens.json. DO NOT EDIT.
# Regenerate: node design/emit.mjs --write

defmodule Barkpark.PortableDoc.Render.TokensGen do
  @moduledoc """
  Unified Aesthetic tokens for the paper render surface (emails + article
  palettes), generated from design/tokens.json. Regenerate with
  `node design/emit.mjs --write`; never hand-edit. Emits the verbatim
  paper-email skin (email_* — consumed by palettes.ex / data_viz.ex), the
  callout tone tints (callout/2 — util.ex tone_palette/1), the semantic
  status tones, and the tokenized reading accent + reading type. The email
  brand/rule are the verbatim email_* hex, NOT color.primary/border (those
  HSL-derived slots are drifted from the byte-locked email golden; w3
  reconciles the two).

  ## Theme-keying (charter D28)

  Every COLOUR-bearing token is theme-keyed: the value lives in a per-theme
  map and the accessor takes an optional `theme` defaulting `:evergreen`.
  `evergreen` is the only theme this wave; an unknown / empty / binary theme
  resolves to `:evergreen` (Resolve semantics). Adding theme N+1 is one more
  key in each map — no accessor changes. Non-colour tokens (reading_font /
  heading weight / body size) are theme-INVARIANT and stay plain.
  """

  # Known theme ids (evergreen only this wave). resolve/1 folds an unknown /
  # empty / binary theme onto :evergreen so every accessor is total.
  @themes [:evergreen, :charple, :ember, :fjord, :iris]
  @doc "Known theme ids (evergreen this wave)."
  def themes, do: @themes
  defp resolve(theme) when theme in @themes, do: theme

  defp resolve(theme) when is_binary(theme),
    do: Enum.find(@themes, :evergreen, &(Atom.to_string(&1) == theme))

  defp resolve(_), do: :evergreen

  # Semantic status tones (design/tokens.json color.status, light theme → hex).
  @status %{
    evergreen: %{ok: "#137236", info: "#3b82f6", warn: "#ba7008", danger: "#b42222"},
    charple: %{ok: "#31854a", info: "#4a6ebd", warn: "#986600", danger: "#b74840"},
    ember: %{ok: "#36844c", info: "#4c6fb9", warn: "#986600", danger: "#b54b43"},
    fjord: %{ok: "#4d7f58", info: "#5871a5", warn: "#91692d", danger: "#a35a52"},
    iris: %{ok: "#05893e", info: "#406bce", warn: "#986600", danger: "#c53732"}
  }
  def tone_ok(theme \\ :evergreen), do: @status[resolve(theme)].ok
  def tone_info(theme \\ :evergreen), do: @status[resolve(theme)].info
  def tone_warn(theme \\ :evergreen), do: @status[resolve(theme)].warn
  def tone_danger(theme \\ :evergreen), do: @status[resolve(theme)].danger

  # Warm reading accent — the paper terracotta, tokenized.
  @reading_accent %{
    evergreen: "#a23925",
    charple: "#302ba5",
    ember: "#bf321d",
    fjord: "#0f8299",
    iris: "#3692e6"
  }
  def reading_accent(theme \\ :evergreen), do: @reading_accent[resolve(theme)]

  # Reading type (design/tokens.json font.reading / type.reading). Theme-INVARIANT.
  @reading_font "\"Iowan Old Style\", \"Palatino Linotype\", Palatino, Charter, Georgia, \"Source Serif 4\", serif"
  def reading_font, do: @reading_font
  def reading_heading_weight, do: 600
  def reading_body_size, do: 18

  # Paper email surface — verbatim hand hex (light-only; email has no dark mode).
  @email %{
    evergreen: %{
      brand: "#1e5347",
      brand_text: "#ffffff",
      rule: "#dde7e2",
      page_bg: "#eaf1ee",
      paper: "#ffffff",
      text: "#15211d",
      muted: "#55635e",
      code_bg: "#eaf1ee"
    },
    charple: %{
      brand: "#7b3a96",
      brand_text: "#ffffff",
      rule: "#e0dde1",
      page_bg: "#f0ecf3",
      paper: "#f8f8fc",
      text: "#241e27",
      muted: "#565059",
      code_bg: "#f0ecf3"
    },
    ember: %{
      brand: "#b34e1e",
      brand_text: "#ffffff",
      rule: "#e2dcda",
      page_bg: "#f4ece9",
      paper: "#fdfcfb",
      text: "#291d19",
      muted: "#5b504c",
      code_bg: "#f4ece9"
    },
    fjord: %{
      brand: "#0e6e85",
      brand_text: "#ffffff",
      rule: "#d9dfe1",
      page_bg: "#e7f0f2",
      paper: "#fcfcfd",
      text: "#162327",
      muted: "#495559",
      code_bg: "#e7f0f2"
    },
    iris: %{
      brand: "#5b46d6",
      brand_text: "#ffffff",
      rule: "#dddee2",
      page_bg: "#ecedf5",
      paper: "#ffffff",
      text: "#1f1f2a",
      muted: "#51525b",
      code_bg: "#ecedf5"
    }
  }
  @doc "The whole per-theme email skin map (palettes.ex / data_viz.ex read it in one shot)."
  def email_skin(theme \\ :evergreen), do: @email[resolve(theme)]
  def email_brand(theme \\ :evergreen), do: email_skin(theme).brand
  def email_brand_text(theme \\ :evergreen), do: email_skin(theme).brand_text
  def email_rule(theme \\ :evergreen), do: email_skin(theme).rule
  def email_page_bg(theme \\ :evergreen), do: email_skin(theme).page_bg
  def email_paper(theme \\ :evergreen), do: email_skin(theme).paper
  def email_text(theme \\ :evergreen), do: email_skin(theme).text
  def email_muted(theme \\ :evergreen), do: email_skin(theme).muted
  def email_code_bg(theme \\ :evergreen), do: email_skin(theme).code_bg

  # Callout tone tints — verbatim {bg, fg} pairs (util.ex tone_palette/1).
  @callout %{
    evergreen: %{
      success: %{bg: "#e7f2ec", fg: "#1e6b52"},
      warning: %{bg: "#f7f0df", fg: "#8a6420"},
      danger: %{bg: "#f7e9e6", fg: "#a63a2e"},
      info: %{bg: "#e9eff7", fg: "#2d5e8f"},
      neutral: %{bg: "#edf0ee", fg: "#4a544f"}
    },
    charple: %{
      success: %{bg: "#def6e2", fg: "#276438"},
      warning: %{bg: "#feecd4", fg: "#734c00"},
      danger: %{bg: "#ffe9e6", fg: "#823e38"},
      info: %{bg: "#e7efff", fg: "#3a538a"},
      neutral: %{bg: "#efeef0", fg: "#565457"}
    },
    ember: %{
      success: %{bg: "#dff6e3", fg: "#2a6339"},
      warning: %{bg: "#fdecd5", fg: "#724d0a"},
      danger: %{bg: "#ffe9e6", fg: "#803f39"},
      info: %{bg: "#e7efff", fg: "#3b5487"},
      neutral: %{bg: "#f0eeee", fg: "#585453"}
    },
    fjord: %{
      success: %{bg: "#e4f4e6", fg: "#3b5f42"},
      warning: %{bg: "#f9eddd", fg: "#6a502b"},
      danger: %{bg: "#ffe9e6", fg: "#754742"},
      info: %{bg: "#e7efff", fg: "#435579"},
      neutral: %{bg: "#edeff0", fg: "#525657"}
    },
    iris: %{
      success: %{bg: "#daf8df", fg: "#0f662f"},
      warning: %{bg: "#ffecd2", fg: "#734c00"},
      danger: %{bg: "#ffe9e6", fg: "#8b3630"},
      info: %{bg: "#e7efff", fg: "#335296"},
      neutral: %{bg: "#eeeff0", fg: "#555558"}
    }
  }
  def callout(tone, theme \\ :evergreen)
  def callout(:success, theme), do: @callout[resolve(theme)].success
  def callout(:warning, theme), do: @callout[resolve(theme)].warning
  def callout(:danger, theme), do: @callout[resolve(theme)].danger
  def callout(:info, theme), do: @callout[resolve(theme)].info
  def callout(:neutral, theme), do: @callout[resolve(theme)].neutral
end
