#!/usr/bin/env bash
#
# Ratchet: every entry in api/.sobelow-skips must still point at a real
# construct of its own declared detector type.
#
# WHY THIS EXISTS SEPARATELY FROM sobelow-inline-overlap-check.sh. That check
# is SPAN-BASED and BASELINE-DRIVEN: it asks "is a baseline row also covered by
# an inline annotation?". It therefore PASSES in exactly the situations this
# wave creates — a row that drifted OUT of its annotation span, a row whose
# file was moved or deleted, a file that grew annotations and has zero baseline
# rows. Those are all "no overlap", so it says PASS. This check is orthogonal:
# it never looks at annotations at all. It asks the one question a fingerprint
# baseline can never answer by itself — does `file:line` still hold a call of
# the kind the entry claims to waive?
#
# A baseline entry whose line no longer holds its construct is not a waiver any
# more; it is a dead promise. Sobelow will not match it, so the finding it was
# drawn to cover comes back as NEW (and, in the advisory job, quietly). Worse,
# a dead entry is indistinguishable from a live one by eye, so the reviewed
# baseline slowly stops being reviewed.
#
# NO BEAM, NO DEPS, NO NETWORK. Pure text over the baseline plus the sources it
# names — ~1s — which is why it runs in the BLOCKING job next to the overlap
# ratchet, not in the advisory Sobelow job. Its `--selftest` blocks there
# today; the run against the real baseline is REPORTING-ONLY until the residue
# reaches zero (50 stale on main 2026-07-28, 31 after wave 23 S1), because a
# step that reds on arrival would turn a green, meaningful job permanently red.
# The flip condition and its tracking task are on the workflow step itself.
#
# ANCHOR TOKENS ARE DERIVED, NOT HAND-WRITTEN. The map from detector type to
# the function tokens that type matches is generated by `--derive` directly out
# of the Sobelow detector modules (each detector's
# `Parse.get_fun_vars_and_meta(fun, _, :token, _)` call sites, plus the
# `@..._funs` atom lists a detector iterates when it passes a variable). The
# generated table is embedded below between markers so the blocking job needs
# no deps; `--verify-tokens DIR` regenerates from a real Sobelow checkout and
# reds on any drift, and runs in the advisory Sobelow job where deps exist.
#
# TYPES WITH NO PER-LINE ANCHOR ARE SKIPPED, NEVER PASSED. Config.CSRF,
# Config.Headers and Config.HTTPS are whole-file/whole-router findings — their
# detectors have no per-line token, so there is nothing at `:LINE` to look for.
# They are reported as SKIPPED and excluded from the checked population. A type
# missing from the table entirely is an ERROR (exit 2), not a skip: an unknown
# detector must never be silently waved through.
#
# DIRECTION OF ERROR. The line test is a text match for a call-shaped
# occurrence of the token, so an unrelated line that happens to contain
# `write(` reads as "still resolves". This check is therefore CONSERVATIVE: it
# can miss a stale entry, it cannot invent one. A red here is always real.
#
# EXIT CODES
#   0  every checkable entry still resolves
#   1  one or more entries no longer resolve (listed on stdout)
#   2  fail-closed: usage error, unknown detector type, or ZERO checkable
#      entries. A checker with an empty population has not passed — it has
#      failed to run.

set -euo pipefail

usage() {
  cat <<'USAGE'
usage: sobelow-baseline-staleness-check.sh [--baseline FILE] [--api-dir DIR]
                                           [--derive DIR] [--verify-tokens DIR]
                                           [--selftest]

  --baseline FILE      baseline to check (default: api/.sobelow-skips)
  --api-dir DIR        root the baseline's paths are relative to (default: api/)
  --derive DIR         print the anchor-token table derived from a Sobelow
                       source tree (e.g. api/deps/sobelow) and exit
  --verify-tokens DIR  regenerate from that tree and diff against the table
                       embedded in this script; exit 1 on any drift
  --selftest           run the mutation fixtures that prove this checker can
                       fail, then exit; does not touch the tracked tree
USAGE
}

API_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
BASELINE="$API_DIR/.sobelow-skips"
ROOT_DIR="$API_DIR"
DERIVE_DIR=""
VERIFY_DIR=""
SELFTEST=0

while [[ $# -gt 0 ]]; do
  case $1 in
    --baseline)
      [[ $# -ge 2 ]] || { echo "error: --baseline needs a value" >&2; exit 2; }
      BASELINE=$2
      shift 2
      ;;
    --api-dir)
      [[ $# -ge 2 ]] || { echo "error: --api-dir needs a value" >&2; exit 2; }
      ROOT_DIR=$2
      shift 2
      ;;
    --derive)
      [[ $# -ge 2 ]] || { echo "error: --derive needs a value" >&2; exit 2; }
      DERIVE_DIR=$2
      shift 2
      ;;
    --verify-tokens)
      [[ $# -ge 2 ]] || { echo "error: --verify-tokens needs a value" >&2; exit 2; }
      VERIFY_DIR=$2
      shift 2
      ;;
    --selftest)
      SELFTEST=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

# --- the derived table -------------------------------------------------------
# GENERATED by `--derive api/deps/sobelow` (sobelow 0.14.1). Do not hand-edit:
# `--verify-tokens api/deps/sobelow` reds if these lines and the detector
# modules disagree. One line per detector: `TYPE<TAB>token token ...`; a type
# with no tokens has no per-line anchor and is SKIPPED by the check.
read -r -d '' ANCHOR_TOKENS <<'TOKENS' || true
CI.OS	cmd
CI.System	cmd	shell
Config.CSP
Config.CSRF
Config.CSRFRoute
Config.CSWH
Config.HSTS
Config.HTTPS
Config.Headers
Config.Secrets
DOS.BinToAtom	binary_to_atom
DOS.ListToAtom	to_atom
DOS.StringToAtom	to_atom
Misc.BinToTerm	binary_to_term
RCE.CodeModule	eval_file	eval_quoted	eval_string
RCE.EEx	eval_file	eval_string
SQL.Query	query	query!
SQL.Stream	stream
Traversal.FileModule	chmod	chmod!	chown	chown!	copy	copy!	cp	cp!	cp_r	cp_r!	ln	ln!	ln_s	ln_s!	mkdir	mkdir!	mkdir_p	mkdir_p!	open	open!	read	read!	rm	rm!	rm_rf	stream	stream!	write	write!
Traversal.SendDownload	send_download
Traversal.SendFile	send_file
Vuln.Coherence
Vuln.Ecto
Vuln.HeaderInject
Vuln.Plug
Vuln.PlugNull
Vuln.Redirect
XSS.ContentType	put_resp_content_type
XSS.HTML	html
XSS.Raw	raw
XSS.SendResp	send_resp
TOKENS
# --- end derived table -------------------------------------------------------

# Derive the table straight from a Sobelow source tree. Two shapes, both taken
# from the detector modules themselves:
#   * a literal token — `get_fun_vars_and_meta(fun, N, :to_atom, ...)`
#   * a variable token — `get_fun_vars_and_meta(fun, N, file_func, ...)`, where
#     the detector iterates one of its own `@..._funs`/`@..._funcs` atom lists
# A detector with neither has no per-line anchor and is emitted token-less.
derive_tokens() {
  local tree=$1
  if [[ ! -d $tree ]]; then
    echo "error: sobelow source tree not found: $tree" >&2
    return 2
  fi

  local found=0 out
  out=$(
    find "$tree" -type f -name '*.ex' -print0 |
      LC_ALL=C sort -z |
      while IFS= read -r -d '' file; do
        LC_ALL=C awk '
          /@finding_type[[:space:]]+"/ {
            if (type == "") {
              s = $0
              match(s, /"[^:]+:/)
              if (RSTART > 0) type = substr(s, RSTART + 1, RLENGTH - 2)
            }
          }
          # Atom lists the module may iterate: `@code_funs [:a, :b]`,
          # `@file_funcs [...]`, possibly spread over several lines. Collected
          # for every attribute list, used only when a detector passes a
          # variable token (over-collecting only ever widens the match, which
          # is the conservative direction).
          /^[[:space:]]*@[a-z_]+[[:space:]]*\[/ { inlist = 1 }
          inlist {
            rest = $0
            while (match(rest, /:[a-z_][a-zA-Z0-9_]*[!?]?/)) {
              attrs[substr(rest, RSTART + 1, RLENGTH - 1)] = 1
              rest = substr(rest, RSTART + RLENGTH)
            }
            if ($0 ~ /\]/) inlist = 0
          }
          /get_(erlang_)?fun_vars_and_meta\(/ {
            s = $0
            sub(/.*get_(erlang_)?fun_vars_and_meta\(/, "", s)
            n = split(s, arg, ",")
            if (n >= 3) {
              tok = arg[3]
              gsub(/^[[:space:]]+|[[:space:]]+$/, "", tok)
              if (tok ~ /^:[a-z_]/) literal[substr(tok, 2)] = 1
              else needs_attrs = 1
            }
          }
          END {
            if (type == "") exit 0
            out = type
            n = 0
            for (t in literal) toks[++n] = t
            if (needs_attrs) for (t in attrs) toks[++n] = t
            # insertion sort: token order must be stable across awk builds
            for (i = 2; i <= n; i++) {
              v = toks[i]
              for (j = i - 1; j >= 1 && toks[j] > v; j--) toks[j + 1] = toks[j]
              toks[j + 1] = v
            }
            for (i = 1; i <= n; i++)
              if (i == 1 || toks[i] != toks[i - 1]) out = out "\t" toks[i]
            print out
          }
        ' "$file"
      done | LC_ALL=C sort
  )

  [[ -n $out ]] && found=1
  if [[ $found -eq 0 ]]; then
    echo "error: derived ZERO detector types from $tree — refusing to emit an empty table" >&2
    return 2
  fi
  printf '%s\n' "$out"
}

verify_tokens() {
  local tree=$1 fresh
  fresh=$(derive_tokens "$tree") || return $?
  if [[ $fresh == "$ANCHOR_TOKENS" ]]; then
    printf 'PASS: embedded anchor-token table matches the detector modules in %s\n' "$tree"
    return 0
  fi
  echo "FAIL: the embedded anchor-token table has drifted from $tree" >&2
  diff <(printf '%s\n' "$ANCHOR_TOKENS") <(printf '%s\n' "$fresh") >&2 || true
  echo "      Regenerate: api/scripts/sobelow-baseline-staleness-check.sh --derive $tree" >&2
  return 1
}

# --- the check ---------------------------------------------------------------

run_check() {
  if [[ ! -f $BASELINE ]]; then
    echo "error: baseline not found: $BASELINE" >&2
    return 2
  fi
  if [[ ! -d $ROOT_DIR ]]; then
    echo "error: source root not found: $ROOT_DIR" >&2
    return 2
  fi

  local status=0
  awk -v root="${ROOT_DIR%/}" -v baseline="$BASELINE" '
    # Pass 1 (stdin): the derived anchor-token table.
    {
      known[$1] = 1
      line = $0
      sub(/^[^\t]*\t?/, "", line)
      tokens[$1] = line
      next
    }
    function call_regex(toks,   n, i, parts, re) {
      n = split(toks, parts, "\t")
      re = ""
      for (i = 1; i <= n; i++) {
        if (parts[i] == "") continue
        re = (re == "" ? "" : re "|") parts[i]
      }
      if (re == "") return ""
      # A call-shaped occurrence: token preceded by a non-identifier character
      # (start of line, `.`, `|>`, whitespace) and followed by `(`.
      return "(^|[^A-Za-z0-9_])(" re ")[[:space:]]*\\("
    }
    END {
      entries = 0; checked = 0; skipped = 0; stale = 0
      nfiles = 0

      while ((getline row < baseline) > 0) {
        if (row ~ /^[[:space:]]*$/) continue
        entries++

        # `TYPE: human description,relative/path.ex:LINE,FINGERPRINT`
        # The description may contain commas, so anchor on the tail.
        if (match(row, /,[^,]+:[0-9]+,[0-9A-Fa-f]+[[:space:]]*$/) == 0) {
          printf "MALFORMED %s\n", row
          stale++
          continue
        }
        tail = substr(row, RSTART + 1)
        sub(/,[0-9A-Fa-f]+[[:space:]]*$/, "", tail)
        split(tail, loc, ":")
        colon = index(row, ":")
        if (colon == 0) { printf "MALFORMED %s\n", row; stale++; continue }

        e_type[entries] = substr(row, 1, colon - 1)
        e_file[entries] = loc[1]
        e_line[entries] = loc[2] + 0
        # The detector-emitted description often names the exact construct in
        # backticks (`File.write`, `String.to_atom`). When its last segment is
        # one of the type tokens, prefer it — a precise anchor beats the whole
        # family. Otherwise (`XSS`, `System`) fall back to the family.
        desc = substr(row, colon + 1)
        e_hint[entries] = ""
        if (match(desc, /`[A-Za-z_][A-Za-z0-9_.]*[!?]?`/)) {
          hint = substr(desc, RSTART + 1, RLENGTH - 2)
          sub(/^.*\./, "", hint)
          e_hint[entries] = hint
        }

        if (!((e_file[entries] SUBSEP) in seen_file)) {
          seen_file[e_file[entries] SUBSEP] = 1
          files[++nfiles] = e_file[entries]
        }
      }
      close(baseline)

      if (entries == 0) {
        print "error: scanned ZERO baseline entries — refusing to report a pass" > "/dev/stderr"
        exit 2
      }

      # Read every named file once; keep the whole text keyed by line number.
      for (f = 1; f <= nfiles; f++) {
        path = root "/" files[f]
        n = 0
        while ((getline l < path) > 0) { n++; text[files[f], n] = l }
        close(path)
        nlines[files[f]] = n
      }

      for (i = 1; i <= entries; i++) {
        type = e_type[i]
        if (type == "") continue
        if (!(type in known)) {
          printf "error: unknown detector type %s (regenerate the anchor-token table) \n", type > "/dev/stderr"
          exit 2
        }
        re = call_regex(tokens[type])
        if (re == "") {
          if (!(type in skipnote)) {
            skipnote[type] = 1
            printf "SKIP  %s — whole-file/router finding, no per-line anchor to check\n", type
          }
          skipped++
          continue
        }

        checked++
        file = e_file[i]; ln = e_line[i]
        if (nlines[file] == 0) {
          printf "STALE %s:%d %s — file not found under %s\n", file, ln, type, root
          stale++
          continue
        }
        if (ln < 1 || ln > nlines[file]) {
          printf "STALE %s:%d %s — line is past end of file (%d lines)\n",
                 file, ln, type, nlines[file]
          stale++
          continue
        }

        src = text[file, ln]
        hint = e_hint[i]
        if (hint != "" && tokens[type] ~ ("(^|\t)" hint "(\t|$)"))
          want = "(^|[^A-Za-z0-9_])" hint "[[:space:]]*\\("
        else
          want = re

        if (src !~ want) {
          printf "STALE %s:%d %s — line holds no %s call: %s\n",
                 file, ln, type, (hint != "" ? hint : "matching"),
                 substr(src, 1, 80)
          stale++
        }
      }

      if (checked == 0) {
        print "error: ZERO checkable baseline entries — refusing to report a pass" > "/dev/stderr"
        exit 2
      }

      printf "checked %d of %d baseline entries (%d skipped: no per-line anchor)\n",
             checked, entries, skipped
      if (stale > 0) {
        printf "FAIL: %d baseline entries no longer point at a construct of their own type.\n", stale > "/dev/stderr"
        print  "      Each one is a dead waiver: Sobelow will not match it, so the finding" > "/dev/stderr"
        print  "      it was drawn to cover comes back as NEW. Migrate the call site to an" > "/dev/stderr"
        print  "      inline `# sobelow_skip [\"Type\"]` annotation and drop the entry, or" > "/dev/stderr"
        print  "      regenerate on the pinned CI toolchain (sobelow-baseline-reconcile.sh)." > "/dev/stderr"
        exit 1
      }
      print "PASS: every checkable baseline entry still points at a construct of its own type"
    }
  ' <<< "$ANCHOR_TOKENS" || status=$?
  return "$status"
}

# --- selftest: prove the checker can fail, in every direction ----------------

selftest_fixture() {
  local dir=$1
  mkdir -p "$dir/lib/barkpark" "$dir/lib/barkpark_web"
  cat > "$dir/lib/barkpark/fixture.ex" <<'FIXTURE'
defmodule Barkpark.Fixture do
  def resolves(path) do
    File.read!(path)
  end

  def atomize(name) do
    String.to_atom(name)
  end

  def drifted(name) do
    # the construct used to live here
    name
  end
end
FIXTURE
  cat > "$dir/lib/barkpark_web/router.ex" <<'ROUTER'
defmodule BarkparkWeb.Router do
  scope "/" do
    get("/", PageController, :index)
  end
end
ROUTER
}

expect_status() {
  local label=$1 want=$2
  shift 2
  local got=0 out
  out=$("$@" 2>&1) || got=$?
  if [[ $got -ne $want ]]; then
    printf 'SELFTEST FAIL: %s — expected exit %d, got %d\n%s\n' "$label" "$want" "$got" "$out" >&2
    return 1
  fi
  printf '  ok  %-40s exit %d\n' "$label" "$got"
}

run_selftest() {
  local tmp
  tmp=$(mktemp -d "${TMPDIR:-/tmp}/sobelow-staleness-selftest.XXXXXX")
  # shellcheck disable=SC2064
  trap "rm -rf -- '$tmp'" RETURN
  selftest_fixture "$tmp"

  # File.read! is at line 3, String.to_atom at line 7.
  local live="$tmp/live" shifted="$tmp/shifted" moved="$tmp/moved"
  local past="$tmp/past" skiponly="$tmp/skiponly" empty="$tmp/empty"
  local unknown="$tmp/unknown"
  printf '%s\n' \
    'Traversal.FileModule: Directory Traversal in `File.read!`,lib/barkpark/fixture.ex:3,AAAAAA' \
    'DOS.StringToAtom: Unsafe `String.to_atom`,lib/barkpark/fixture.ex:7,BBBBBB' \
    'Config.CSRF: Missing CSRF Protections,lib/barkpark_web/router.ex:2,CCCCCC' \
    > "$live"
  # ONE line off — the entry now lands on `def atomize`, not the call.
  printf '%s\n' \
    'Traversal.FileModule: Directory Traversal in `File.read!`,lib/barkpark/fixture.ex:3,AAAAAA' \
    'DOS.StringToAtom: Unsafe `String.to_atom`,lib/barkpark/fixture.ex:6,BBBBBB' \
    > "$shifted"
  printf '%s\n' \
    'Traversal.FileModule: Directory Traversal in `File.read!`,lib/barkpark/moved_away.ex:3,AAAAAA' \
    > "$moved"
  printf '%s\n' \
    'Traversal.FileModule: Directory Traversal in `File.read!`,lib/barkpark/fixture.ex:9001,AAAAAA' \
    > "$past"
  printf '%s\n' \
    'Config.CSRF: Missing CSRF Protections,lib/barkpark_web/router.ex:2,CCCCCC' \
    > "$skiponly"
  printf '%s\n' \
    'Nope.Invented: Something,lib/barkpark/fixture.ex:3,DDDDDD' \
    > "$unknown"
  : > "$empty"

  echo "selftest: mutation fixtures"
  local failures=0
  local me=${BASH_SOURCE[0]}
  expect_status "every entry resolves" 0 \
    bash "$me" --baseline "$live" --api-dir "$tmp" || failures=1
  expect_status "one entry shifted by ONE line" 1 \
    bash "$me" --baseline "$shifted" --api-dir "$tmp" || failures=1
  expect_status "entry whose file moved away" 1 \
    bash "$me" --baseline "$moved" --api-dir "$tmp" || failures=1
  expect_status "entry past end of file" 1 \
    bash "$me" --baseline "$past" --api-dir "$tmp" || failures=1
  expect_status "only anchorless types fails closed" 2 \
    bash "$me" --baseline "$skiponly" --api-dir "$tmp" || failures=1
  expect_status "zero baseline entries fails closed" 2 \
    bash "$me" --baseline "$empty" --api-dir "$tmp" || failures=1
  expect_status "unknown detector type fails closed" 2 \
    bash "$me" --baseline "$unknown" --api-dir "$tmp" || failures=1

  # The derived table must be derived: an empty tree cannot yield a table.
  expect_status "--derive on a non-tree fails closed" 2 \
    bash "$me" --derive "$tmp/nope" || failures=1

  if [[ $failures -ne 0 ]]; then
    echo "SELFTEST FAILED" >&2
    return 1
  fi
  echo "SELFTEST PASS: the ratchet greens on live entries and reds on a one-line shift, a moved file and a past-EOF line, and fails closed on an unknown type or an empty checkable population"
}

if [[ $SELFTEST -eq 1 ]]; then
  run_selftest
  exit $?
fi

if [[ -n $DERIVE_DIR ]]; then
  derive_tokens "$DERIVE_DIR"
  exit $?
fi

if [[ -n $VERIFY_DIR ]]; then
  verify_tokens "$VERIFY_DIR"
  exit $?
fi

run_check
