#!/usr/bin/env bash
#
# Ratchet: every baseline row whose fingerprint is RECONSTRUCTIBLE FROM THE ROW
# must still hash to the hash it carries.
#
# WHY THIS EXISTS SEPARATELY FROM THE OTHER THREE RATCHETS. Sobelow's --skip
# matches on the HASH ALONE. lib/sobelow.ex:531-546 parses a baseline row as
# [_type, _filename_line_n, fingerprint] — the type and the file:line are bound
# to underscored variables, discarded, and never compared to anything. So field
# 1 and field 2 are pure documentation, and the two failure modes that follow
# are both INVISIBLE to a reader:
#
#   * a row whose hash still matches keeps waiving its finding no matter what
#     its file:line says — editing that text is a NO-OP;
#   * a row whose hash no longer matches waives NOTHING, while still reading
#     like a reviewed, maintained waiver.
#
# The second one is what this checks. A fingerprint is
#   phash2([type, vuln_source, filename, vuln_line_no]) |> Integer.to_string(16)
# (sobelow 0.14.1, lib/sobelow/finding.ex:53-63), so it embeds the LINE. Any
# insertion above a finding silently orphans its row.
#
# ORTHOGONAL TO THE STALENESS RATCHET BY CONSTRUCTION, NOT BY CONVENTION. That
# ratchet asks "does file:line still hold a CALL of the entry's own type?" and
# answers it with a table of per-line function tokens derived from the detector
# modules. Config.CSRF / Config.HTTPS have no such token, so it reports them
# SKIPPED and excludes them from its population — by its own design, and
# correctly. This check owns EXACTLY that excluded set and nothing else:
#
#   staleness ratchet  ->  rows with a per-line function token   (34 of 41)
#   this ratchet       ->  rows reconstructible from row data    ( 7 of 41)
#
# The two populations partition the baseline; neither is widened into the
# other's territory. Run this checker on a baseline of only token-anchored rows
# and it exits 2 (empty population) — the mirror image of the staleness checker
# exiting 2 on a baseline of only Config.* rows. Each still PASSES on the shape
# the other catches, which is the standing contract for these ratchets.
#
# WHY ONLY SOME ROWS ARE RECONSTRUCTIBLE. vuln_source is the third hashed
# component. For the AST-walking detectors (DOS.*, Traversal.*, XSS.*, RCE.*)
# it is the QUOTED ELIXIR AST NODE of the offending call, carrying line AND
# COLUMN metadata (lib/sobelow/finding.ex:29-43; the parse sets columns: true
# at lib/sobelow/parse.ex:41). That term is not present in the baseline row and
# cannot be recovered from it, so those rows are reported SKIPPED here — never
# passed. Only detectors whose vuln_source is a plain atom or string can be
# recomputed from the row plus the source it names:
#
#   Config.CSRF   vuln_source = the pipeline-name ATOM   (config/csrf.ex:39-50)
#                 vuln_line_no = the line of the pipeline declaration itself
#   Config.HTTPS  vuln_source = a CONSTANT string        (config/https.ex:39-52)
#                 vuln_line_no = the literal 0 — the finding is the ABSENCE of
#                 config, so there is no node to point at. All four components
#                 are constants, which is why that row cannot drift.
#
# A detector type in neither list is an ERROR (exit 2), not a skip — a new type
# entering the baseline must be classified by a human, exactly as the staleness
# ratchet refuses an unknown type rather than waving it through.
#
# WHY IT NEEDS THE BEAM, AND WHY THAT DOES NOT MAKE IT ADVISORY. phash2 is an
# ERTS primitive over term structure; there is no faithful shell reimplementation
# and a lookalike would be a lie. But "needs the BEAM" and "must be advisory"
# are different claims. The sobelow job is advisory because SOBELOW's own
# fingerprints are derived from compiled AST and drift across toolchains. This
# check compiles nothing and runs no Sobelow code — it hashes
# [binary, atom|binary, binary, integer], which is stable: the hashes in this
# repo's baseline were generated by CI on OTP 27 and were reproduced
# byte-exactly on OTP 28 while this checker was written. So it runs in a
# BLOCKING job, in its own job so the BEAM-free ~1s blocking job stays
# BEAM-free. A fingerprint check hosted by a continue-on-error: true job cannot
# red, and a check that cannot red is not a check.
#
# EXIT CODES
#   0  every reconstructible row still hashes to its stored fingerprint
#   1  one or more rows disagree (each named on stderr)
#   2  fail-closed: usage error, unclassified detector type, a row sobelow's own
#      parser would drop, missing elixir, or ZERO reconstructible entries. An
#      empty population has not passed — it has failed to run.

set -euo pipefail

BASELINE="api/.sobelow-skips"
API_DIR="api"
SELFTEST=0

HERE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
CHECKER="$HERE/sobelow-baseline-fingerprint.exs"

usage() {
  cat <<'USAGE'
usage: sobelow-baseline-fingerprint-check.sh [--baseline FILE] [--api-dir DIR]
                                             [--selftest]

  --baseline FILE   baseline to check (default: api/.sobelow-skips)
  --api-dir DIR     root the baseline's paths are relative to (default: api/)
  --selftest        run the mutation fixtures that prove this checker can fail,
                    in both directions, and exit
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --baseline)
      [[ $# -ge 2 ]] || { echo "error: --baseline needs a value" >&2; exit 2; }
      BASELINE=$2; shift 2 ;;
    --api-dir)
      [[ $# -ge 2 ]] || { echo "error: --api-dir needs a value" >&2; exit 2; }
      API_DIR=$2; shift 2 ;;
    --selftest)
      SELFTEST=1; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 2 ;;
  esac
done

command -v elixir >/dev/null 2>&1 || {
  echo "error: elixir not on PATH — this checker recomputes :erlang.phash2 and cannot run without the BEAM" >&2
  exit 2
}

[[ -f "$CHECKER" ]] || {
  echo "error: checker not found next to this script: $CHECKER" >&2
  exit 2
}

# --- selftest: prove the checker can fail, in every direction ----------------

selftest_fixture() {
  local dir=$1
  mkdir -p "$dir/lib/barkpark_web" "$dir/config"
  cat > "$dir/lib/barkpark_web/router.ex" <<'ROUTER'
defmodule BarkparkWeb.Router do
  pipeline :alpha do
    plug(:fetch_session)
  end

  pipeline :beta do
    plug(:accepts, ["json"])
  end
end
ROUTER
  cat > "$dir/config/prod.exs" <<'PRODEXS'
import Config
config :barkpark, BarkparkWeb.Endpoint, url: [host: "example.com"]
PRODEXS
}

expect_status() {
  local label=$1 want=$2
  shift 2
  local got=0 out
  out=$("$@" 2>&1) || got=$?
  if [[ $got -ne $want ]]; then
    printf 'SELFTEST FAIL: %s — expected exit %d, got %d\n%s\n' "$label" "$want" "$got" "$out" >&2
    return 1
  fi
  printf '  ok  %-48s exit %d\n' "$label" "$got"
}

# A selftest that hardcoded its expected hashes would be testing its own
# arithmetic. These are computed the same way the checker computes them, from
# the fixture — so the "live" baseline below is correct BY CONSTRUCTION and
# every mutant is a real departure from it.
fixture_hash() {
  local type=$1 kind=$2 src=$3 file=$4 line=$5
  elixir -e '
    [type, kind, src, file, line] = System.argv()
    s = if kind == "atom", do: String.to_atom(src), else: src
    IO.write([type, s, file, String.to_integer(line)] |> :erlang.phash2() |> Integer.to_string(16))
  ' "$type" "$kind" "$src" "$file" "$line"
}

run_selftest() {
  local tmp
  tmp=$(mktemp -d "${TMPDIR:-/tmp}/sobelow-fingerprint-selftest.XXXXXX")
  # shellcheck disable=SC2064
  trap "rm -rf -- '$tmp'" RETURN
  selftest_fixture "$tmp"

  local csrf="Config.CSRF: Missing CSRF Protections"
  local https="Config.HTTPS: HTTPS Not Enabled"
  local reason='HTTPS configuration details could not be found in `prod.exs`.'
  local router="lib/barkpark_web/router.ex"

  # :alpha is at line 2 of the fixture router, :beta at line 6.
  local h_alpha h_beta h_https
  h_alpha=$(fixture_hash "$csrf" atom alpha "$router" 2)
  h_beta=$(fixture_hash "$csrf" atom beta "$router" 6)
  h_https=$(fixture_hash "$https" string "$reason" "config/prod.exs" 0)

  local live="$tmp/live" bumped="$tmp/bumped" swapped="$tmp/swapped"
  local offconstruct="$tmp/offconstruct" moved="$tmp/moved" past="$tmp/past"
  local astonly="$tmp/astonly" empty="$tmp/empty" unknown="$tmp/unknown"
  local malformed="$tmp/malformed"

  local ast='DOS.StringToAtom: Unsafe `String.to_atom`,lib/barkpark_web/router.ex:3,AAAAAA'

  printf '%s\n' \
    "$csrf,$router:2,$h_alpha" \
    "$csrf,$router:6,$h_beta" \
    "$https,config/prod.exs:0,$h_https" \
    "$ast" \
    > "$live"

  # THE DEFECT THIS RATCHET EXISTS FOR — commit 2a60d013f's exact edit, and the
  # shape #13886 produced on the live baseline: the line moves, the hash does
  # not. The row still names a REAL pipeline line, so a text-only anchor test
  # passes it; only recomputing the fingerprint catches it.
  printf '%s\n' \
    "$csrf,$router:6,$h_alpha" \
    "$ast" \
    > "$bumped"

  # Two rows that each hold a real pipeline line and a real hash — but crossed.
  printf '%s\n' \
    "$csrf,$router:2,$h_beta" \
    "$csrf,$router:6,$h_alpha" \
    "$ast" \
    > "$swapped"

  # Line 3 is plug(:fetch_session) — a real line, but not a declaration. This is
  # the exact shape the six live rows had before this wave re-anchored them.
  printf '%s\n' \
    "$csrf,$router:3,$h_alpha" \
    "$ast" \
    > "$offconstruct"

  printf '%s\n' \
    "$csrf,lib/barkpark_web/gone.ex:2,$h_alpha" \
    "$ast" \
    > "$moved"

  printf '%s\n' \
    "$csrf,$router:9001,$h_alpha" \
    "$ast" \
    > "$past"

  printf '%s\n' "$ast" > "$astonly"
  printf '%s\n' 'Nope.Invented: Something,lib/barkpark_web/router.ex:2,DDDDDD' > "$unknown"
  printf '%s\n' 'Config.CSRF: Missing CSRF Protections,lib/barkpark_web/router.ex:2' > "$malformed"
  : > "$empty"

  echo "selftest: mutation fixtures"
  local failures=0
  local me=${BASH_SOURCE[0]}

  expect_status "every reconstructible row hashes true" 0 \
    bash "$me" --baseline "$live" --api-dir "$tmp" || failures=1
  expect_status "line bumped, hash kept (the named defect)" 1 \
    bash "$me" --baseline "$bumped" --api-dir "$tmp" || failures=1
  expect_status "two rows' hashes swapped" 1 \
    bash "$me" --baseline "$swapped" --api-dir "$tmp" || failures=1
  expect_status "row parked on a plug, not a declaration" 1 \
    bash "$me" --baseline "$offconstruct" --api-dir "$tmp" || failures=1
  expect_status "row whose file moved away" 1 \
    bash "$me" --baseline "$moved" --api-dir "$tmp" || failures=1
  expect_status "row past end of file" 1 \
    bash "$me" --baseline "$past" --api-dir "$tmp" || failures=1
  expect_status "only AST-derived rows fails closed" 2 \
    bash "$me" --baseline "$astonly" --api-dir "$tmp" || failures=1
  expect_status "zero baseline entries fails closed" 2 \
    bash "$me" --baseline "$empty" --api-dir "$tmp" || failures=1
  expect_status "unclassified detector type fails closed" 2 \
    bash "$me" --baseline "$unknown" --api-dir "$tmp" || failures=1
  expect_status "row sobelow's parser would drop fails closed" 2 \
    bash "$me" --baseline "$malformed" --api-dir "$tmp" || failures=1
  expect_status "unknown argument fails closed" 2 \
    bash "$me" --nope || failures=1

  if [[ $failures -ne 0 ]]; then
    echo "SELFTEST FAILED" >&2
    return 1
  fi
  echo "SELFTEST PASS: the ratchet greens on a correct baseline and reds on a bumped line, swapped hashes, a row parked off its declaration, a moved file and a past-EOF line, and fails closed on an unclassified type, a row sobelow would drop, and an empty population"
}

if [[ $SELFTEST -eq 1 ]]; then
  run_selftest
  exit $?
fi

elixir "$CHECKER" "$BASELINE" "$API_DIR"
