// Code generated by design/emit.mjs from design/status-manifest.json. DO NOT EDIT.
// Regenerate: node design/emit.mjs --write
//
// The white ladder (D15) — the ONE task-status vocabulary, shared with the
// Elixir emitters (Render.StatusVocab reads the same manifest at compile time),
// the paper-surface --st-* tone tokens and the Go pdrender board. A manifest
// edit re-emits this file; hand-editing it is caught by design/check.mjs Part A.
//
// The JS-only fail-open `unknown` sentinel (D11) is NOT a manifest role and is
// appended by src/inline.tsx, which owns it.

/** One rung of the status ladder. */
export interface StatusRole {
  role: string
  glyph: string
  spinner: boolean
  label: string
  meaning: string
}

/** The manifest roles, in manifest order. */
export const MANIFEST_STATUS_ROLES: StatusRole[] = [
  { role: 'open', glyph: '○', spinner: false, label: 'open', meaning: 'backlog — not ready yet' },
  {
    role: 'ready',
    glyph: '○',
    spinner: false,
    label: 'ready',
    meaning: 'unchecked — claim it now',
  },
  {
    role: 'progress',
    glyph: '',
    spinner: true,
    label: 'in progress',
    meaning: 'being worked right now',
  },
  {
    role: 'blocked',
    glyph: '!',
    spinner: false,
    label: 'blocked',
    meaning: 'something is required first',
  },
  { role: 'done', glyph: '✓', spinner: false, label: 'done', meaning: 'complete' },
  {
    role: 'cancel',
    glyph: '✕',
    spinner: false,
    label: 'cancelled',
    meaning: 'abandoned or superseded',
  },
  {
    role: 'considering',
    glyph: '◌',
    spinner: false,
    label: 'considering',
    meaning: 'a candidate being weighed',
  },
  {
    role: 'researching',
    glyph: '◎',
    spinner: false,
    label: 'researching',
    meaning: 'under active investigation',
  },
]

/** Stored lifecycle status → ladder role (the manifest `statuses` map, aliases
 *  and terminal states included). */
export const MANIFEST_STATUS_TO_ROLE: Record<string, string> = {
  open: 'open',
  ready: 'ready',
  in_progress: 'progress',
  blocked: 'blocked',
  done: 'done',
  closed: 'done',
  cancelled: 'cancel',
  considering: 'considering',
  researching: 'researching',
}

/** The role an ABSENT/empty status falls back to (the manifest `default_role`). */
export const MANIFEST_DEFAULT_ROLE = 'open'
