// AUTO-GENERATED by scripts/gen-showcase-content.mjs — DO NOT hand-edit.
//
// The full 42-type PortableDocument grammar, one block per registered
// non-plugin type, lifted verbatim from @barkpark/react's pd-golden parity
// fixtures. This is the flagship demo post's body: it renders through the
// canonical PortableDoc renderer (index + post pages) and hydrates its media
// mount points (mermaid diagram + asciicast) via @barkpark/react/client.
//
// Regenerate with: node scripts/gen-showcase-content.mjs

import type { Block } from '@barkpark/react'

/** The 42 canonical block types, concatenated from the parity goldens. */
export const showcaseContent: Block[] = [
  {
    "href": "https://example.com/docs",
    "label": "Read the docs",
    "priority": "primary",
    "type": "action"
  },
  {
    "caption": "A terminal walkthrough",
    "src": "https://example.com/casts/demo.cast",
    "type": "asciicast"
  },
  {
    "items": [
      "Jane Rae",
      "2026-07-16"
    ],
    "type": "byline"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "This is a warning callout body."
      }
    ],
    "title": "Heads up",
    "tone": "warn",
    "type": "callout"
  },
  {
    "slots": {
      "action": [
        {
          "href": "https://example.com/board",
          "label": "Open the board",
          "type": "action"
        }
      ],
      "body": [
        {
          "content": [
            {
              "type": "text",
              "value": "Card body text."
            }
          ],
          "type": "paragraph"
        }
      ],
      "title": [
        {
          "text": "Card title",
          "type": "heading"
        }
      ]
    },
    "tone": "info",
    "type": "card"
  },
  {
    "items": [
      {
        "text": "The first rule body.",
        "title": "Rule one",
        "tone": "info"
      },
      {
        "text": "The second rule body.",
        "title": "Rule two",
        "tone": "warn"
      }
    ],
    "type": "cards"
  },
  {
    "axes": {
      "xLabels": [
        "W1",
        "W2",
        "W3",
        "W4"
      ]
    },
    "caption": "Coverage over time",
    "kind": "line",
    "series": [
      {
        "label": "Covered",
        "points": [
          10,
          20,
          35,
          42
        ]
      }
    ],
    "type": "chart"
  },
  {
    "tokens": 1200,
    "type": "chat-thinking"
  },
  {
    "todos": [
      {
        "content": "Author the array",
        "status": "completed"
      },
      {
        "active_form": "Wiring the generator",
        "content": "Wire the generator",
        "status": "in_progress"
      },
      {
        "content": "Prove parity",
        "status": "pending"
      }
    ],
    "type": "chat-todo"
  },
  {
    "input": {
      "file_path": "lib/foo.ex",
      "new_string": "def hello do\n  :new\nend",
      "old_string": "def hello do\n  :old\nend"
    },
    "type": "chat-tool-diff"
  },
  {
    "type": "code",
    "value": "def hello do\n  :world\nend"
  },
  {
    "columns": [
      [
        {
          "content": [
            {
              "type": "text",
              "value": "Left column body."
            }
          ],
          "type": "paragraph"
        }
      ],
      [
        {
          "content": [
            {
              "type": "text",
              "value": "Right column body."
            }
          ],
          "type": "paragraph"
        }
      ]
    ],
    "type": "columns"
  },
  {
    "caption": "The three-stage pipeline",
    "source": "graph TD; A[Ingest] --> B[Render] --> C[Publish]",
    "type": "diagram"
  },
  {
    "type": "divider"
  },
  {
    "text": "Dispatches",
    "type": "eyebrow"
  },
  {
    "caption": "Figure with a captioned child",
    "child": {
      "content": [
        {
          "type": "text",
          "value": "The figure body."
        }
      ],
      "type": "paragraph"
    },
    "type": "figure"
  },
  {
    "kind": "grill",
    "questions": [
      {
        "id": "q1",
        "prompt": "Ship it?",
        "type": "yesno"
      },
      {
        "id": "q2",
        "options": [
          "Next",
          "Astro",
          "Phoenix"
        ],
        "prompt": "Pick a surface",
        "type": "single"
      },
      {
        "id": "q3",
        "options": [
          "Elixir",
          "Go",
          "JS"
        ],
        "prompt": "Which renderers to keep",
        "type": "multi"
      },
      {
        "id": "q4",
        "prompt": "Confidence",
        "scale": {
          "max": 5,
          "min": 1
        },
        "type": "scale"
      },
      {
        "id": "q5",
        "prompt": "Anything else?",
        "type": "text"
      }
    ],
    "type": "form"
  },
  {
    "level": 2,
    "text": "The render path",
    "type": "heading"
  },
  {
    "cells": [
      [
        0.1,
        0.4,
        0.9
      ],
      [
        0.6,
        0.2,
        0.5
      ]
    ],
    "type": "heatmap"
  },
  {
    "alt": "Cover art",
    "height": 360,
    "src": "https://cdn.example.com/cover.png",
    "type": "image",
    "width": 640
  },
  {
    "content": [
      {
        "type": "text",
        "value": "A lead paragraph that opens the article."
      }
    ],
    "type": "ingress"
  },
  {
    "items": [
      [
        {
          "type": "text",
          "value": "First point"
        }
      ],
      [
        {
          "type": "text",
          "value": "Second point"
        }
      ]
    ],
    "ordered": false,
    "type": "list"
  },
  {
    "label": "Note",
    "lead": "Run-in",
    "text": "A single annotated row.",
    "type": "note"
  },
  {
    "items": [
      {
        "label": "Upgrade",
        "lead": "Instant",
        "text": "The board updates live."
      },
      {
        "label": "Why",
        "lead": "Trust",
        "text": "You always feel progress."
      }
    ],
    "type": "notes"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "A body paragraph with "
      },
      {
        "marks": [
          {
            "type": "bold"
          }
        ],
        "type": "text",
        "value": "bold emphasis"
      },
      {
        "type": "text",
        "value": " inside it."
      }
    ],
    "type": "paragraph"
  },
  {
    "nodes": [
      {
        "detail": "reads the queue",
        "kind": "source",
        "source": true,
        "title": "Ingest"
      },
      {
        "detail": "maps the rows",
        "kind": "emit",
        "source": "queue.ex:42",
        "title": "Transform"
      },
      {
        "detail": "writes the board",
        "kind": "gate",
        "title": "Publish"
      }
    ],
    "type": "pipeline"
  },
  {
    "content": [
      {
        "type": "text",
        "value": "The best interface is no interface."
      }
    ],
    "type": "pullquote"
  },
  {
    "questions": [
      {
        "id": "q1",
        "prompt": "Ready to review?",
        "type": "yesno"
      },
      {
        "id": "q2",
        "prompt": "Notes",
        "type": "text"
      }
    ],
    "type": "questionnaire"
  },
  {
    "scale": [
      "Q1",
      "Q2",
      "Q3"
    ],
    "snapshot": [
      {
        "left": 0,
        "phase_row": true,
        "status": "done",
        "title": "Foundation",
        "width": 40
      },
      {
        "left": 40,
        "status": "in_progress",
        "title": "Ship the board",
        "width": 35
      }
    ],
    "type": "roadmap"
  },
  {
    "blocks": [
      {
        "slots": {
          "title": [
            {
              "text": "Alpha cell",
              "type": "heading"
            }
          ]
        },
        "type": "card"
      },
      {
        "slots": {
          "title": [
            {
              "text": "Beta cell",
              "type": "heading"
            }
          ]
        },
        "span": 2,
        "type": "card"
      }
    ],
    "layout": {
      "gap": "md",
      "mode": "grid",
      "tracks": 2
    },
    "type": "section"
  },
  {
    "ref": "budget-2026",
    "snapshot": {
      "col_widths": [
        12,
        8
      ],
      "head": [
        "Item",
        "Cost"
      ],
      "rows": [
        [
          "Hosting",
          "42"
        ],
        [
          "Domains",
          "18"
        ]
      ]
    },
    "type": "sheet"
  },
  {
    "detail": "checks the criteria",
    "kind": "gate",
    "source": true,
    "title": "Review",
    "type": "stage"
  },
  {
    "items": [
      {
        "label": "Renderers today",
        "value": "5"
      },
      {
        "label": "Renderers target",
        "value": "3"
      }
    ],
    "type": "stat-grid"
  },
  {
    "denom": "118",
    "label": "Blocks covered",
    "max": 118,
    "spark": [
      3,
      5,
      8,
      13,
      21
    ],
    "type": "stat",
    "value": "71"
  },
  {
    "items": [
      {
        "label": "In-scope types",
        "value": "42"
      },
      {
        "label": "Renderers",
        "value": "3"
      }
    ],
    "type": "stats"
  },
  {
    "type": "status-legend"
  },
  {
    "head": [
      [
        {
          "type": "text",
          "value": "Surface"
        }
      ],
      [
        {
          "type": "text",
          "value": "Renderer"
        }
      ]
    ],
    "rows": [
      [
        [
          {
            "type": "text",
            "value": "Phoenix"
          }
        ],
        [
          {
            "type": "text",
            "value": "Elixir"
          }
        ]
      ],
      [
        [
          {
            "type": "text",
            "value": "Next"
          }
        ],
        [
          {
            "type": "text",
            "value": "React"
          }
        ]
      ]
    ],
    "type": "table"
  },
  {
    "snapshot": [
      {
        "status": "open",
        "title": "Backlog groom"
      },
      {
        "priority": "1",
        "status": "ready",
        "title": "Wire the harness"
      },
      {
        "priority": "0",
        "status": "in_progress",
        "title": "Render the board"
      },
      {
        "status": "blocked",
        "title": "Await review"
      },
      {
        "criteria": {
          "met": 2,
          "total": 2
        },
        "status": "done",
        "title": "Ship the legend"
      }
    ],
    "type": "task-board"
  },
  {
    "task": {
      "criteria": [
        {
          "met": true,
          "text": "Gen emits fixtures"
        },
        {
          "met": false,
          "text": "JS realizes the golden"
        }
      ],
      "labels": [
        "parity",
        "w1"
      ],
      "priority": "1",
      "status": "in_progress",
      "timeline": [
        {
          "label": "Filed",
          "status": "open"
        },
        {
          "label": "Building",
          "status": "in_progress"
        },
        {
          "label": "Shipped",
          "status": "done"
        }
      ],
      "title": "Wire the harness"
    },
    "type": "task-detail"
  },
  {
    "snapshot": [
      {
        "status": "ready",
        "title": "Seed the renderer"
      },
      {
        "status": "open",
        "title": "Close the gaps"
      }
    ],
    "type": "task-list"
  },
  {
    "snapshot": [
      {
        "status": "done",
        "title": "Author the array"
      },
      {
        "priority": "0",
        "status": "in_progress",
        "title": "Wire the generator"
      },
      {
        "status": "ready",
        "title": "Prove parity"
      }
    ],
    "type": "tasks"
  },
  {
    "children": [
      {
        "content": [
          {
            "type": "text",
            "value": "Inside the frame."
          }
        ],
        "type": "paragraph"
      }
    ],
    "footer": "q to quit",
    "live": true,
    "title": "bp tasks",
    "type": "terminal"
  }
]

export default showcaseContent
