defmodule Barkpark.Repo.Migrations.CreateChatSessionsAndMessages do
  use Ecto.Migration

  @moduledoc """
  Studio Claude chat — session index + display history (epic studio-claude-chat,
  wave 1, charter D6-D8).

  Two tables, deliberately NOT documents. The doc route is disqualified by
  evidence: a private-schema query gate is any-api-token (query_controller.ex),
  so a read-only worker token could read admin chat transcripts (cwd, tool
  inputs, host paths). These tables get NO HTTP route EVER — admin LiveView
  reads Repo directly (org_admin_live prior art), so they are admin-gated by
  construction.

    * `chat_sessions` — the session INDEX. The `id` is the minted claude session
      UUID (we generate it before the first byte via `--session-id`), so it
      doubles as the `--resume` key: one identity, no cursor column. Denormalised
      `summary` / `message_count` / usage totals let the sidebar render instantly
      without touching `chat_messages`.
    * `chat_messages` — our DISPLAY history (NOT the transcript; the CLI owns the
      transcript in `~/.claude/projects/*.jsonl`, which we never read). One row
      per completed message, `source_markdown` only — re-rendered on read so the
      improving render engine wins. `seq` is monotonic per session; the UNIQUE
      [session_id, seq] is the append race guard.
  """

  def change do
    create table(:chat_sessions, primary_key: false) do
      # The minted claude session UUID — NOT autogenerated. We pin it at spawn
      # via --session-id and reuse it as the --resume key.
      add :id, :uuid, primary_key: true

      add :title, :text, null: false, default: "New chat"
      # "default" (derived/placeholder) | "ai" | "human". The AI-title clobber
      # guard writes only WHERE title_source = 'default'; a human rename is
      # never overwritten (charter D13).
      add :title_source, :text, null: false, default: "default"

      add :cwd, :text
      add :mode, :text
      add :model, :text
      # active | working | exited
      add :status, :text, null: false, default: "active"

      add :last_active_at, :utc_datetime_usec

      # Denormalised sidebar fields — instant render, no message scan.
      add :summary, :text
      add :message_count, :integer, null: false, default: 0
      add :input_tokens, :bigint, null: false, default: 0
      add :output_tokens, :bigint, null: false, default: 0
      add :total_cost_usd, :float, null: false, default: 0.0

      timestamps(type: :utc_datetime_usec)
    end

    # The sidebar query: recency within a status band (PendingApproval > Working
    # > Completed pills read status; ORDER BY last_active_at DESC).
    create index(:chat_sessions, [:status, :last_active_at])

    create table(:chat_messages) do
      add :session_id,
          references(:chat_sessions, type: :uuid, on_delete: :delete_all),
          null: false

      add :seq, :integer, null: false
      add :role, :text, null: false
      # Markdown ONLY, never HTML — re-rendered on read (charter D7).
      add :source_markdown, :text
      add :metadata, :map, null: false, default: %{}

      timestamps(type: :utc_datetime_usec)
    end

    # Append race guard + the replay query (WHERE session_id = ? ORDER BY seq).
    create unique_index(:chat_messages, [:session_id, :seq])
  end
end
