// NOT generated code, despite the .gen.ts name and the header this file used to
// carry ("Code generated by design/emit.mjs … DO NOT EDIT. Regenerate: node
// design/emit.mjs --write"). Both claims were false:
//
//   • design/emit.mjs's ARTIFACTS list (emit.mjs:1979) has 19 entries and NOT
//     ONE is under templates/. The emitted sibling is web/lib/tokens.gen.ts;
//     THAT one is real. `node design/emit.mjs --write` has never written this
//     file and cannot. design/check.mjs contains zero occurrences of
//     "templates", which is why the drift below was never caught.
//   • This file is no longer byte-identical to web/lib/tokens.gen.ts (1637 vs
//     1646 bytes), so it is not even a stale copy of a live artifact.
//
// What it actually is: a hand-maintained snapshot whose values ORIGINATED in
// design/tokens.json. Editing it by hand is legitimate — nothing regenerates
// over you. Re-syncing it to design/tokens.json is a deliberate, reviewed
// change (it moves the flagship's primary green), not a refresh, and is
// deliberately NOT part of stw11-a11y-invariants. The .gen.ts filename is kept
// only because templates/astro-search-starter vendors this path byte-for-byte
// (scripts/check-astro-finder-drift.sh).

/** Light-theme canvas colours for listings-map.tsx, snapshotted from design/tokens.json. */
export const canvas = {
  primary: "hsl(163 46% 22%)",
  mutedText: "hsl(240 3.8% 45%)",
  surface: "hsl(0 0% 100%)",
  primaryFg: "hsl(0 0% 100%)",
  text: "hsl(240 10% 3.9%)",
  mutedSurface: "hsl(240 4.8% 95.9%)",
} as const;

/** Categorical match-quality spectrum (7 ordered stops, fuzzy→exact) for
 *  finder.tsx's HighlightLegend gradient. Theme-invariant data-viz palette,
 *  NOT a status role — mirrors the presence / Sheets-CF categorical sets. */
export const matchQuality = [
  "hsl(0 55% 60%)",
  "hsl(24 70% 56%)",
  "hsl(48 82% 50%)",
  "hsl(72 86% 46%)",
  "hsl(100 88% 42%)",
  "hsl(130 90% 38%)",
  "hsl(162 95% 34%)",
] as const;

/** Paper callout tone tints for portable-doc.tsx (design/tokens.json
 *  color.paperCallout — the web twin of the paper-surface --bp-tone-* pairs).
 *  {bg,fg} hex per tone, light + dark. NOT the status roles — never
 *  substitute color.status for these. */
export const paperCallout = {
  success: { light: { bg: "#e7f2ec", fg: "#1e6b52" }, dark: { bg: "#12241c", fg: "#5fcf9c" } },
  warning: { light: { bg: "#f7f0df", fg: "#8a6420" }, dark: { bg: "#2a2210", fg: "#e3b661" } },
  danger: { light: { bg: "#f7e9e6", fg: "#a63a2e" }, dark: { bg: "#2a1614", fg: "#f08a80" } },
  info: { light: { bg: "#e9eff7", fg: "#2d5e8f" }, dark: { bg: "#172032", fg: "#9db8ff" } },
  neutral: { light: { bg: "#edf0ee", fg: "#4a544f" }, dark: { bg: "#23211e", fg: "#c9c2b6" } },
} as const;
