// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Barkpark contributors

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { beforeAll, describe, expect, it } from 'vitest'
import { generateTypes, schemaEnvelopeSchema } from '../src/index'
import type { BarkparkSchemaJson } from '../src/index'

const here = dirname(fileURLToPath(import.meta.url))
const fixturePath = resolve(here, 'fixtures/production-schema.json')

let envelope: BarkparkSchemaJson
let output: string

beforeAll(async () => {
  const raw = JSON.parse(readFileSync(fixturePath, 'utf8')) as unknown
  envelope = schemaEnvelopeSchema.parse(raw)
  output = await generateTypes(envelope, { dataset: 'production' })
})

describe('generateTypes — full output', () => {
  it('matches the committed snapshot', () => {
    expect(output).toMatchSnapshot()
  })

  it('emits a deterministic banner with the schema hash', () => {
    expect(output).toContain(
      '// Generated by @barkpark/codegen from dataset "production" at schema hash 484ba7aaf4ae48bb. DO NOT EDIT — run barkpark generate.',
    )
  })

  it('is byte-stable across runs (deterministic)', async () => {
    const again = await generateTypes(envelope, { dataset: 'production' })
    expect(again).toBe(output)
  })
})

describe('generateTypes — self-contained prelude', () => {
  it('declares system fields locally with no index signature', () => {
    expect(output).toContain('export interface BarkparkSystemFields {')
    expect(output).toContain('_id: string')
    expect(output).toContain('_type: string')
    expect(output).toContain('_createdAt: string')
    expect(output).toContain('_updatedAt: string')
    expect(output).toContain('_rev: string')
    // Every envelope also carries these (server @reserved + core BarkparkDocument);
    // a codegen-typed `doc._draft` / `doc._publishedId` must type-check.
    expect(output).toContain('_draft: boolean')
    expect(output).toContain('_publishedId: string')
    // The whole point: no escape-hatch index signature on documents/system
    // fields. The one intentional index signature lives on the open-by-design
    // BarkparkPortableTextBlock helper, so exclude that block before asserting.
    const withoutBlock = output.replace(/export interface BarkparkPortableTextBlock \{[^}]*\}/, '')
    expect(withoutBlock).not.toContain('[k: string]: unknown')
    expect(output).not.toMatch(/\[\s*key\s*:\s*string\s*\]/)
  })

  it('declares the value-type aliases inline (no @barkpark/core import)', () => {
    // No real import statement and no dependency on the core package.
    expect(output).not.toMatch(/\bimport\b[^\n]*from/)
    expect(output).not.toContain("'@barkpark/core'")
    expect(output).not.toContain('"@barkpark/core"')
    expect(output).toContain('export interface BarkparkSlug {')
    expect(output).toContain('current: string')
    expect(output).toContain('export interface BarkparkImage {')
    expect(output).toContain('_type: "image"')
    expect(output).toContain('export interface BarkparkReference {')
    expect(output).toContain('_type: "reference"')
  })

  it('every interface extends BarkparkSystemFields', () => {
    const count = (output.match(/extends BarkparkSystemFields/g) ?? []).length
    expect(count).toBe(envelope.schemas.length)
  })
})

describe('generateTypes — per-type mapping spot-checks', () => {
  it('select → sorted string-literal union (Ability.kind)', () => {
    // options: movement, combat, timeControl, utility → sorted union
    expect(output).toMatch(
      /kind\?:\s*"combat"\s*\|\s*"movement"\s*\|\s*"timeControl"\s*\|\s*"utility"/,
    )
  })

  it('codelist → plain string, no union (Book.notificationType)', () => {
    expect(output).toMatch(/notificationType\?:\s*string/)
  })

  it('reference → BarkparkReference, no target generic (Ability.usesTimeState)', () => {
    expect(output).toMatch(/usesTimeState\?:\s*BarkparkReference(?!<)/)
  })

  it('arrayOf composite → Array<{ ... }> (Arena.rimRings)', () => {
    // rimRings: arrayOf of a composite { y: string }
    expect(output).toMatch(/rimRings\?:\s*Array<\{\s*y\?:\s*string\s*\}>/)
  })

  it('array (v1) of string → Array<string> (Goal.papers)', () => {
    expect(output).toMatch(/papers\?:\s*Array<string>/)
  })

  it('image → BarkparkImage (Author.avatar)', () => {
    expect(output).toMatch(/avatar\?:\s*BarkparkImage/)
  })

  it('slug → BarkparkSlug (Author.slug)', () => {
    expect(output).toMatch(/slug\?:\s*BarkparkSlug/)
  })

  it('richText → Array<BarkparkPortableTextBlock> (Page.body)', () => {
    expect(output).toMatch(/body\?:\s*Array<BarkparkPortableTextBlock>/)
  })

  it('localizedText → Partial<Record<langs, string>> (MediaAsset.altText)', () => {
    expect(output).toMatch(/altText\?:\s*Partial<Record<"eng"\s*\|\s*"nob",\s*string>>/)
  })

  it('object → Record<string, unknown> (Event.payload)', () => {
    expect(output).toMatch(/payload\?:\s*Record<string,\s*unknown>/)
  })

  it('optionality: required? === false → emits a `?` modifier', () => {
    // Every field in the fixture is required?:false, so every member is optional.
    // Post.title is a string, declared optional.
    expect(output).toMatch(/title\?:\s*string/)
    // And no required (no-`?`) field members leak through — sanity on a known field.
    expect(output).not.toMatch(/\btitle:\s*string/)
  })
})

describe('generateTypes — completeness', () => {
  it('BarkparkTypeMap lists all 45 schemas', () => {
    expect(envelope.schemas.length).toBe(45)
    const mapBlock = output.slice(output.indexOf('export type BarkparkTypeMap'))
    for (const s of envelope.schemas) {
      const pascal = s.name.charAt(0).toUpperCase() + s.name.slice(1)
      expect(mapBlock).toContain(`${s.name}: ${pascal}`)
    }
  })

  it('BarkparkAnyDocument unions every type, each discriminable by its _type literal', () => {
    const unionBlock = output.slice(output.indexOf('export type BarkparkAnyDocument'))
    expect(unionBlock).toContain('export type BarkparkAnyDocument =')
    for (const s of envelope.schemas) {
      const pascal = s.name.charAt(0).toUpperCase() + s.name.slice(1)
      // every document type is a union member …
      expect(unionBlock).toContain(pascal)
      // … and its interface pins `_type` to the schema-name literal (so
      // `if (d._type === '<name>')` narrows the union to that interface).
      expect(output).toContain(`_type: "${s.name}"`)
    }
  })

  it('no field is silently dropped — every schema field name appears in its interface', () => {
    for (const schema of envelope.schemas) {
      const pascal = schema.name.charAt(0).toUpperCase() + schema.name.slice(1)
      const ifaceStart = output.indexOf(`export interface ${pascal} extends BarkparkSystemFields`)
      expect(ifaceStart, `interface ${pascal} missing`).toBeGreaterThanOrEqual(0)
      // Slice from this interface to the next top-level `export interface`.
      const rest = output.slice(ifaceStart + 1)
      const nextExport = rest.indexOf('\nexport interface ')
      const body = nextExport >= 0 ? rest.slice(0, nextExport) : rest
      for (const field of schema.fields) {
        expect(body, `${pascal}.${field.name} dropped`).toMatch(new RegExp(`\\b${field.name}\\??:`))
      }
    }
  })

  it('produces exactly one interface per schema plus the five fixed interfaces', () => {
    const interfaceCount = (output.match(/export interface /g) ?? []).length
    // 45 schemas + BarkparkSystemFields + BarkparkSlug + BarkparkImage
    // + BarkparkReference + BarkparkPortableTextBlock = 50. BarkparkTypeMap is a
    // `type` (not interface), so it satisfies typedClient<TMap>'s Record
    // constraint; counted separately.
    expect(interfaceCount).toBe(envelope.schemas.length + 5)
    expect(output).toContain('export type BarkparkTypeMap = {')
  })
})

describe('generateTypes — non-identifier field names', () => {
  it('quotes property names that are not valid JS identifiers (else the .ts is invalid)', async () => {
    const env = {
      datasetSchemaHash: 'deadbeef',
      schemas: [
        {
          name: 'post',
          title: 'Post',
          fields: [
            { name: 'my-field', type: 'string' },
            { name: '2col', type: 'number' },
            { name: 'has space', type: 'string' },
            { name: 'normal', type: 'string' },
          ],
        },
      ],
    } as unknown as BarkparkSchemaJson

    // Without quoting, `my-field?: string` is invalid TS and prettier.format()
    // throws here — so a successful generate is itself the regression guard.
    const out = await generateTypes(env, { dataset: 'production' })

    expect(out).toMatch(/['"]my-field['"]\??:/)
    expect(out).toMatch(/['"]2col['"]\??:/)
    expect(out).toMatch(/['"]has space['"]\??:/)
    // a valid identifier stays bare (unquoted)
    expect(out).toMatch(/\n\s*normal\??:/)
    expect(out).not.toMatch(/['"]normal['"]\??:/)
  })

  it('select whose `options` is a non-array (string) falls back to `string`, not a char union (#865)', async () => {
    // A malformed schema where `options` is the string "abc" (strings are
    // iterable): a naive `?? []` would walk characters and emit 'a' | 'b' | 'c'.
    const env = {
      datasetSchemaHash: 'deadbeef',
      schemas: [
        {
          name: 'post',
          title: 'Post',
          fields: [{ name: 'kind', type: 'select', options: 'abc' }],
        },
      ],
    } as unknown as BarkparkSchemaJson

    const out = await generateTypes(env, { dataset: 'production' })

    expect(out).toMatch(/kind\?:\s*string/)
    expect(out).not.toMatch(/'a'\s*\|\s*'b'\s*\|\s*'c'/)
  })

  it('select whose `options` is the old guerrilla object shape {list:[...]} falls back to `string`, not a leaked union (ticket.status precedent)', async () => {
    // The pre-fix guerrilla `ticket.status` field shipped `type:"string"` with
    // `options: {list:['open','closed']}` — an OBJECT, not the array the mapper
    // models. That exact shape is the string-shape guard's structural sibling:
    // `Array.isArray(field.options)` (#865, generate.ts) degrades a non-array
    // `options` to `[]`, so `status` emits plain `string` with no throw and no
    // leaked union or `'list'` literal. This is the JS mirror of Go's
    // `TestLoadSchemasTolerantOptions` — the strict-shape decode class that took
    // down apiclient schema loading (the ticket.status outage, charter §9/§22).
    const env = {
      datasetSchemaHash: 'deadbeef',
      schemas: [
        {
          name: 'ticket',
          title: 'Ticket',
          fields: [{ name: 'status', type: 'select', options: { list: ['open', 'closed'] } }],
        },
      ],
    } as unknown as BarkparkSchemaJson

    const out = await generateTypes(env, { dataset: 'production' })

    expect(out).toMatch(/status\?:\s*string/)
    expect(out).not.toMatch(/'open'\s*\|\s*'closed'/)
    expect(out).not.toMatch(/'list'/)
  })

  it('sanitizes a non-identifier schema name into a valid interface name + quoted map key', async () => {
    const env = {
      datasetSchemaHash: 'deadbeef',
      schemas: [
        { name: 'blog-post', title: 'Blog Post', fields: [{ name: 'title', type: 'string' }] },
      ],
    } as unknown as BarkparkSchemaJson

    // An interface name can't be quoted, so `blog-post` would emit
    // `interface Blog-post` — invalid TS that throws in prettier. A successful
    // generate plus the sanitized name is the regression guard.
    const out = await generateTypes(env, { dataset: 'production' })

    expect(out).toMatch(/export interface Blog_post extends/)
    // map KEY keeps the real schema name (quoted); VALUE is the sanitized interface
    expect(out).toMatch(/['"]blog-post['"]:\s*Blog_post/)
  })
})
